const CMF_LIST = 'https://www.cmfchile.cl/institucional/mercados/consulta.php?Estado=VI&entidad=RGPSF&mercado=O';
const FINTECHILE_MEMBERS = 'https://www.fintechile.org/miembros';
const CMF_DETAIL = (rut:string)=>`https://www.cmfchile.cl/institucional/mercados/entidad.php?control=svs&mercado=O&pestania=1&rut=${rut.replace(/\D/g,'').slice(0,8)}&tipoentidad=RGPSF&vig=VI`;
const UA='ATLAS-Observatorio-Fintech/1.4 (+open-source-monitor)';
function out(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function hex(b:ArrayBuffer){return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256(s:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))}
function entities(s:string){return s.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&aacute;/gi,'á').replace(/&eacute;/gi,'é').replace(/&iacute;/gi,'í').replace(/&oacute;/gi,'ó').replace(/&uacute;/gi,'ú').replace(/&ntilde;/gi,'ñ')}
function strip(s:string){return entities(s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ')).trim()}
function normRut(s:string){return (s||'').toUpperCase().replace(/[^0-9K]/g,'')}
function absolute(href:string|null,base:string){try{return href?new URL(entities(href),base).toString():null}catch{return null}}
function domain(url:string|null){try{return url?new URL(url).hostname.toLowerCase().replace(/^www\./,''):null}catch{return null}}
function decodeLoop(s:string){let x=s;for(let i=0;i<3;i++){try{const y=decodeURIComponent(x);if(y===x)break;x=y}catch{break}}return x}
function brandFrom(imgSrc:string|null,href:string){const host=domain(href)||'';const hostBase=host.split('.')[0]||host;if(!imgSrc)return hostBase;let f=decodeLoop(imgSrc.split('/').pop()||'').replace(/\.[a-z0-9]{2,5}(?:\?.*)?$/i,'');f=f.replace(/^(?:[0-9a-f]{18,}_)+/i,'').replace(/[_-]+/g,' ');f=f.replace(/\b(logo|logotipo|imagotipo|isologo|black|blue|azul|verde|violeta|rgb|main|transparente|recortado|color|colores|dark|fondo|claro|white|bg|formato|alta|original|copia|version|principal|horizontal|grande|webclip)\b/gi,' ').replace(/\b\d{4}\b/g,' ').replace(/\s*\(\d+\)\s*/g,' ').replace(/\s+/g,' ').trim();if(!f||/^(captura|image|img|2)$/i.test(f)||f.length>60||f.split(' ').length>5)return hostBase;if(hostBase&&!f.toLowerCase().includes(hostBase.toLowerCase())&&f.split(' ').length>2)return hostBase;return f}
function parseCmfList(html:string){const rows:any[]=[];for(const m of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const tr=m[1];const tds=[...tr.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>strip(x[1]));if(tds.length<2)continue;const ri=tds.findIndex(c=>/\b\d{7,8}\s*-\s*[0-9K]\b/i.test(c));if(ri<0)continue;const rm=tds[ri].match(/\b(\d{7,8})\s*-\s*([0-9K])\b/i);if(!rm)continue;const rut=`${rm[1]}-${rm[2].toUpperCase()}`;let name='';for(let i=ri+1;i<tds.length;i++){if(tds[i]&&!/^(Vigente|No Vigente)$/i.test(tds[i])){name=tds[i];break}}if(!name)continue;const status=tds.find(c=>/^(Vigente|No Vigente)$/i.test(c))||'Vigente';const hm=tr.match(/href=["']([^"']*entidad\.php[^"']*)["']/i);const sourceUrl=absolute(hm?.[1]||null,CMF_LIST)||CMF_DETAIL(rut);rows.push({source_entity_key:normRut(rut),name,rut,status,source_url:sourceUrl,evidence:{registry:'RPSF',list_status:status}})}const d=new Map<string,any>();for(const r of rows)d.set(r.source_entity_key,r);return [...d.values()]}
function detailMap(html:string){const map=new Map<string,string>();for(const m of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const cs=[...m[1].matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>strip(x[1]));if(cs.length>=2&&cs[0])map.set(cs[0].toLowerCase().replace(/\s+/g,' ').trim(),cs[1]||'')}return map}
function field(map:Map<string,string>,labels:string[]){for(const label of labels){const n=label.toLowerCase();for(const [k,v] of map.entries())if(k.includes(n))return v||null}return null}
function isoDate(s:string|null){if(!s)return null;const m=s.match(/(\d{1,2})\/(\d{1,2})\/(\d{4})/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:null}
async function parseDetail(row:any){const url=row.source_url||CMF_DETAIL(row.rut);const res=await fetch(url,{headers:{'user-agent':UA}});if(!res.ok)return null;const m=detailMap(await res.text());return {rut:row.rut,legal_name:field(m,['razón social','razon social']),fantasy_name:field(m,['nombre de fantasía','nombre de fantasia']),registration_no:field(m,['número de inscripción','numero de inscripcion']),registration_date:isoDate(field(m,['fecha de inscripción','fecha de inscripcion'])),website:field(m,['sitio web']),status:field(m,['vigencia'])||row.status,source_url:url,institution_code:field(m,['código de la institución','codigo de la institucion'])}}
async function fetchCmfDetails(rows:any[]){const all:any[]=[];for(let i=0;i<rows.length;i+=10){const got=await Promise.all(rows.slice(i,i+10).map(r=>parseDetail(r).catch(()=>null)));all.push(...got.filter(Boolean));await new Promise(r=>setTimeout(r,60))}return all}
const VERTICALS:[string,string][]=[['procesamiento','Procesamiento de pagos y remesas'],['finanzas-y-seguros','Infraestructura tecnológica'],['insurtech','Insurtech'],['alternativo','Financiamiento alternativo y préstamos'],['gestion','Gestión de finanzas personales y empresariales'],['negociacion','Negociación de activos financieros y digitales']];
function parseFinteChile(html:string){const rows:any[]=[];for(let i=0;i<VERTICALS.length;i++){const [id,vertical]=VERTICALS[i];const start=html.search(new RegExp(`<section\\s+id=["']${id}["']`,'i'));if(start<0)continue;let end=html.length;for(let j=i+1;j<VERTICALS.length;j++){const pos=html.search(new RegExp(`<section\\s+id=["']${VERTICALS[j][0]}["']`,'i'));if(pos>start){end=pos;break}}const partners=html.search(/<section\s+id=["']partners["']/i);if(partners>start&&partners<end)end=partners;const section=html.slice(start,end);for(const m of section.matchAll(/<a\b([^>]*)class=["'][^"']*link-miembro[^"']*["']([^>]*)>([\s\S]*?)<\/a>/gi)){const attrs=(m[1]||'')+' '+(m[2]||'');const hrefRaw=(attrs.match(/\bhref=["']([^"']+)["']/i)||[])[1]||'';const website=absolute(hrefRaw,FINTECHILE_MEMBERS);if(!website||!/^https?:/i.test(website))continue;const img=(m[3].match(/<img\b[^>]*\bsrc=["']([^"']+)["']/i)||[])[1]||null;const dom=domain(website);if(!dom||dom.includes('fintechile.org'))continue;const brand=brandFrom(img,website);rows.push({brand,website,domain:dom,vertical,source_url:FINTECHILE_MEMBERS,evidence:{membership:'FinteChile',category:vertical,logo_src:img}})}}const d=new Map<string,any>();for(const r of rows){const k=`${r.domain}|${r.vertical}`;if(!d.has(k))d.set(k,r)}return [...d.values()]}
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return out(405,{ok:false,error:'METHOD_NOT_ALLOWED'});try{const sb=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!sb||!key)return out(503,{ok:false,error:'SERVER_CREDENTIALS_UNAVAILABLE'});const headers={apikey:key,authorization:`Bearer ${key}`,'content-type':'application/json'};const rpc=async(name:string,payload:unknown)=>{const r=await fetch(`${sb}/rest/v1/rpc/${name}`,{method:'POST',headers,body:JSON.stringify(payload)});const t=await r.text();if(!r.ok)throw new Error(`${name} HTTP ${r.status}: ${t.slice(0,1200)}`);return t?JSON.parse(t):null};const token=req.headers.get('x-atlas-cron-token')||'';if(!token)return out(401,{ok:false,error:'MISSING_INTERNAL_TOKEN'});if(await rpc('aml_fintech_validate_internal_token',{p_token:token})!==true)return out(401,{ok:false,error:'INVALID_INTERNAL_TOKEN'});
 const cmfRes=await fetch(CMF_LIST,{headers:{'user-agent':UA,accept:'text/html'}});if(!cmfRes.ok)throw new Error(`CMF_RPSF_HTTP_${cmfRes.status}`);const cmfHtml=await cmfRes.text();const cmfSha=await sha256(cmfHtml);const cmfRows=parseCmfList(cmfHtml);if(cmfRows.length<20)throw new Error(`CMF_RPSF_PARSE_TOO_SMALL_${cmfRows.length}`);const cmfIngest=await rpc('aml_fintech_ingest_discovery_rows',{p_source_code:'CMF_RPSF',p_source_url:CMF_LIST,p_source_checksum:cmfSha,p_rows:cmfRows});
 const details=await fetchCmfDetails(cmfRows);const candidateDetails=details.length?await rpc('aml_fintech_ingest_cmf_candidate_details',{p_rows:details}):{updated:0};const entityDetails=details.length?await rpc('aml_fintech_ingest_cmf_details',{p_rows:details}):{updated:0};
 const ftRes=await fetch(FINTECHILE_MEMBERS,{headers:{'user-agent':UA,accept:'text/html'}});if(!ftRes.ok)throw new Error(`FINTECHILE_HTTP_${ftRes.status}`);const ftHtml=await ftRes.text();const ftRows=parseFinteChile(ftHtml);if(ftRows.length<20)throw new Error(`FINTECHILE_PARSE_TOO_SMALL_${ftRows.length}`);const parts:any[]=[];for(let i=0;i<ftRows.length;i+=12){parts.push(await rpc('aml_fintech_ingest_sector_members',{p_source_code:'FINTECHILE_MEMBERS',p_rows:ftRows.slice(i,i+12)}))}const ftIngest=parts.reduce((a:any,p:any)=>({source_code:'FINTECHILE_MEMBERS',rows_seen:(a.rows_seen||0)+(p.rows_seen||0),matched:(a.matched||0)+(p.matched||0),promoted_from_cmf_sii:(a.promoted_from_cmf_sii||0)+(p.promoted_from_cmf_sii||0),unresolved:(a.unresolved||0)+(p.unresolved||0)}),{});
 return out(200,{ok:true,cmf:{source_rows:cmfRows.length,source_sha256:cmfSha,ingest:cmfIngest,details_fetched:details.length,candidate_details:candidateDetails,entity_details:entityDetails},fintechile:{member_rows:ftRows.length,ingest:ftIngest,batches:parts.length,sample:ftRows.slice(0,12)}})
 }catch(e){return out(502,{ok:false,error:'FINTECH_DISCOVERY_FAILED',detail:String((e as Error)?.message||e)})}});