const UA='ATLAS-Fintech-Payments/1.1 (+open-source-monitor)';
const SII='https://www.sii.cl/servicios_online/3532-administradores_operadores.html';
const OPS='https://www.cmfchile.cl/institucional/mercados/consulta.php?Estado=VI&entidad=TPOPE&mercado=B';
const PRE='https://www.cmfchile.cl/institucional/mercados/consulta.php?Estado=VI&entidad=TPEEM&mercado=B';
const CRE='https://www.cmfchile.cl/institucional/mercados/consulta.php?Estado=VI&entidad=TCEEM&mercado=B';
const PSP='https://www.cmfchile.cl/portal/prensa/625/w4-article-91655.html';
function response(status:number,b:unknown){return new Response(JSON.stringify(b),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
function clean(s:string){return s.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function key(s:string){return clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
async function hash(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function parseRows(html:string,url:string,registry:string){const rows:any[]=[];for(const m of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...m[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>clean(x[1]));const ri=cells.findIndex(x=>/\b\d{7,8}\s*-\s*[0-9K]\b/i.test(x));if(ri<0)continue;const rm=cells[ri].match(/\b(\d{7,8})\s*-\s*([0-9K])\b/i);if(!rm)continue;const rut=`${rm[1]}-${rm[2].toUpperCase()}`;let name='';for(let i=ri+1;i<cells.length;i++){if(cells[i]&&!/^(Vigente|No Vigente)$/i.test(cells[i])){name=cells[i];break}}if(!name)continue;const fantasy=(name.match(/\s*\(([^()]*)\)\s*$/)||[])[1]?.trim()||null;if(fantasy)name=name.replace(/\s*\([^()]*\)\s*$/,'').trim();rows.push({source_entity_key:rut,name,rut,status:'VIGENTE',source_url:url,evidence:{registry,fantasy_name:fantasy}})}const d=new Map<string,any>();for(const r of rows)d.set(r.source_entity_key,r);return[...d.values()]}
function parseSii(html:string){const i=html.toLowerCase().indexOf('no vigentes');return parseRows(i>0?html.slice(0,i):html,SII,'SII_PAYMENT_OPERATORS')}
const pspRut=new Map<string,string>([['alps spa','77009327-9'],['ebanx chile limitada','76389778-8'],['inversiones y asesorias integral solutions spa','77066914-6'],['payu chile s a','99584660-8'],['dlocal chile spa','76923783-6'],['bamboo payment systems chile spa','77367796-4'],['pagseguro chile spa','77401986-3'],['payku spa','76584147-K'],['ppro chile spa','76772379-2'],['flow s a','76830014-3'],['pay retailers chile spa','76416659-0'],['kushki chile spa','76693142-1']]);
function parsePsp(html:string){const start=html.toLowerCase().indexOf('proveedores de procesamiento de servicios de pagos');const end=html.toLowerCase().indexOf('cabe recordar',Math.max(start,0));const part=start>=0?html.slice(start,end>start?end:undefined):html;const rows:any[]=[];for(const m of part.matchAll(/<li\b[^>]*>([\s\S]*?)<\/li>/gi)){const name=clean(m[1]);const rut=pspRut.get(key(name))||null;if(!rut)continue;rows.push({source_entity_key:rut,name,rut,status:'HABILITADO_XBORDER',source_url:PSP,evidence:{registry:'CMF_PSP_XBORDER'}})}return rows}
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return response(405,{ok:false,error:'METHOD_NOT_ALLOWED'});try{const sb=Deno.env.get('SUPABASE_URL');const sk=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!sb||!sk)return response(503,{ok:false,error:'SERVER_CONFIG'});const h={apikey:sk,authorization:`Bearer ${sk}`,'content-type':'application/json'};const rpc=async(name:string,payload:unknown={})=>{const r=await fetch(`${sb}/rest/v1/rpc/${name}`,{method:'POST',headers:h,body:JSON.stringify(payload)});const t=await r.text();if(!r.ok)throw new Error(`${name}:${r.status}:${t.slice(0,500)}`);return t?JSON.parse(t):null};const token=req.headers.get('x-atlas-cron-token')||'';if(!token||await rpc('aml_fintech_validate_internal_token',{p_token:token})!==true)return response(401,{ok:false,error:'UNAUTHORIZED'});const specs=[{code:'SII_PAYMENT_OPERATORS',url:SII,min:25,parse:parseSii},{code:'CMF_PAYMENT_OPERATORS',url:OPS,min:5,parse:(x:string)=>parseRows(x,OPS,'PAYMENT_OPERATOR')},{code:'CMF_PREPAID_ISSUERS',url:PRE,min:5,parse:(x:string)=>parseRows(x,PRE,'PREPAID_ISSUER')},{code:'CMF_CREDIT_ISSUERS',url:CRE,min:3,parse:(x:string)=>parseRows(x,CRE,'CREDIT_CARD_ISSUER')},{code:'CMF_PSP_XBORDER',url:PSP,min:5,parse:parsePsp}];const sources:any[]=[];for(const s of specs){const fr=await fetch(s.url,{headers:{'user-agent':UA,accept:'text/html'}});if(!fr.ok)throw new Error(`${s.code}_HTTP_${fr.status}`);const html=await fr.text();const rows=s.parse(html);if(rows.length<s.min)throw new Error(`${s.code}_PARSE_${rows.length}`);const ingest=await rpc('aml_fintech_ingest_discovery_rows',{p_source_code:s.code,p_source_url:s.url,p_source_checksum:await hash(html),p_rows:rows});sources.push({source_code:s.code,rows:rows.length,ingest})}const reconciliation=await rpc('aml_fintech_reconcile_payment_candidates',{});const memberBatch=await rpc('aml_fintech_payment_member_batch',{p_limit:6});return response(200,{ok:true,sources,reconciliation,member_batch:memberBatch})}catch(e){return response(502,{ok:false,error:'PAYMENT_SOURCE_REFRESH_FAILED',detail:String((e as Error)?.message||e)})}});
