import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:CORS});
function publicUrl(raw:string){try{const u=new URL(raw);if(!/^https?:$/.test(u.protocol))return false;const h=u.hostname.toLowerCase();if(h==='localhost'||h.endsWith('.local')||h==='0.0.0.0'||h.startsWith('127.')||h.startsWith('10.')||h.startsWith('192.168.'))return false;const m=h.match(/^172\.(\d+)\./);return !(m&&Number(m[1])>=16&&Number(m[1])<=31)}catch{return false}}
const decode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/gi,' ');
const strip=(h:string)=>decode(h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<(br|\/p|\/div|\/td|\/th|\/tr|\/li|\/h\d)>/gi,'\n').replace(/<[^>]+>/g,' ')).replace(/\r/g,'').replace(/[ \t]+/g,' ');
const title=(h:string)=>{const m=h.match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?decode(m[1].replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()).slice(0,180):null};
function excerpt(text:string,value:string){const lines=text.split('\n').map(x=>x.replace(/\s+/g,' ').trim()).filter(x=>x.length>=3&&x.length<=700);const target=value.trim().toLowerCase(),digits=value.replace(/\D/g,''),needle=digits.length>=6?digits.slice(-6):'';let at=lines.findIndex(l=>l.toLowerCase().includes(target));if(at<0&&needle)at=lines.findIndex(l=>l.replace(/\D/g,'').includes(needle));if(at<0)at=lines.findIndex(l=>/(contacto|tel[eé]fono|correo|email|direcci[oó]n|domicilio|whatsapp|cont[aá]ctanos)/i.test(l));if(at<0)at=0;return lines.slice(Math.max(0,at-1),Math.min(lines.length,at+3)).join(' · ').slice(0,520)}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'method_not_allowed'},405);const auth=req.headers.get('Authorization')||'',url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error:ue}=await uc.auth.getUser();if(ue||!user)return json({error:'unauthorized'},401);const admin=createClient(url,service,{auth:{persistSession:false}});const {data:allowed}=await admin.from('aml_allowed_users').select('user_id').eq('user_id',user.id).eq('enabled',true).maybeSingle();if(!allowed)return json({error:'forbidden'},403);const body=await req.json().catch(()=>({})),id=String(body.contact_id||'').trim();if(!id)return json({error:'contact_id_required'},400);const {data:c,error}=await admin.from('aml_uaf_candidate_contact_osint').select('contact_id,contact_value,source_label,source_url,evidence_note,last_observed_at').eq('contact_id',id).maybeSingle();if(error||!c)return json({error:'contact_not_found'},404);const fallback=String(c.evidence_note||'').trim();if(!c.source_url||!publicUrl(c.source_url))return json({title:c.source_label||'Fuente abierta',excerpt:fallback||'La fuente no permite previsualización automática. Usa la referencia del hallazgo para contrastarla.',source_url:c.source_url,fetched:false});const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),8500);try{const r=await fetch(c.source_url,{signal:ac.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (compatible; ATLAS-AML-Preview/1.0)','accept':'text/html,text/plain;q=0.9,*/*;q=0.1','accept-language':'es-CL,es;q=0.9,en;q=0.6'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const ct=(r.headers.get('content-type')||'').toLowerCase();if(!(ct.includes('text/html')||ct.includes('text/plain')))throw new Error('content_type');const bytes=new Uint8Array(await r.arrayBuffer()),html=new TextDecoder().decode(bytes.slice(0,360000)),txt=strip(html);return json({title:title(html)||c.source_label||'Fuente abierta',excerpt:excerpt(txt,String(c.contact_value||''))||fallback||'La página no entregó texto suficiente para una muestra.',source_url:c.source_url,fetched:true,observed_at:c.last_observed_at})}catch{return json({title:c.source_label||'Fuente abierta',excerpt:fallback||'No fue posible leer una muestra de esta fuente en este momento. El hallazgo sigue disponible para contraste manual.',source_url:c.source_url,fetched:false})}finally{clearTimeout(timer)}});
