import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ICIJ_RECONCILE='https://offshoreleaks.icij.org/api/v1/reconcile';
const OPENSANCTIONS_MATCH='https://api.opensanctions.org/match/default';
const UN_XML='https://scsanctions.un.org/resources/xml/en/name/consolidated.xml';
const OFAC_SDN='https://www.treasury.gov/ofac/downloads/sdn.csv';
const OFAC_ALT='https://www.treasury.gov/ofac/downloads/alt.csv';
const OFAC_CONS='https://www.treasury.gov/ofac/downloads/consolidated/cons_prim.csv';
const OFAC_CONS_ALT='https://www.treasury.gov/ofac/downloads/consolidated/cons_alt.csv';
const UK_CSV='https://sanctionslist.fcdo.gov.uk/docs/UK-Sanctions-List.csv';
const EU_CSV='https://webgate.ec.europa.eu/fsd/fsf/public/files/csvFullSanctionsList_1_1/content?token=dG9rZW4tMjAxNw';
const IDB_API='https://data.iadb.org/es/api/action/datastore_search?resource_id=cd0bd9ac-18c6-44bc-8592-9be468c2efd9';

/* El navegador exige preflight por cualquier cabecera no segura. La app del
 * Observatorio manda x-atlas-client en todas sus peticiones: si no aparece
 * aqui, el preflight se rechaza y el POST nunca sale del navegador. */
const cors={'access-control-allow-origin':'*','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'authorization, x-client-info, apikey, content-type, x-atlas-client','access-control-max-age':'86400','content-type':'application/json; charset=utf-8','cache-control':'no-store'};

function norm(v:any){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function cleanRut(v:any){return String(v||'').replace(/[^0-9kK]/g,'').toUpperCase();}
function arr(v:any):any[]{return Array.isArray(v)?v:(v==null?[]:[v]);}
function unique<T>(xs:T[]):T[]{return [...new Set(xs.filter(Boolean) as T[])];}
function clamp01(v:any){const n=Number(v);if(!Number.isFinite(n))return null;return Math.max(0,Math.min(1,n>1?n/100:n));}
function scoreName(q:string,c:string){const a=norm(q),b=norm(c);if(!a||!b)return 0;if(a===b)return .99;if(b.includes(a)||a.includes(b)){const longer=Math.max(a.length,b.length),shorter=Math.min(a.length,b.length),ratio=shorter/longer;if(ratio>.7)return .90;if(ratio>.55)return .78;return 0;}const qt=unique(a.split(' ').filter(x=>x.length>2)),ct=unique(b.split(' ').filter(x=>x.length>2));if(!qt.length||!ct.length)return 0;const hit=qt.filter(x=>ct.includes(x)).length;if(!hit)return 0;const recall=hit/qt.length,precision=hit/ct.length;if(recall<.5&&precision<.5)return 0;return Math.min(.87,.5*recall+.5*precision);}
function csvLine(line:string,sep=','){const out:string[]=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(ch===sep&&!q){out.push(cur);cur='';}else cur+=ch;}out.push(cur);return out;}
function textFetch(url:string,timeout=14000){return fetch(url,{headers:{'user-agent':'ATLAS-AML/0.53 DirectFallback','accept':'text/plain,text/csv,application/xml,text/xml,*/*'},signal:AbortSignal.timeout(timeout)}).then(async r=>{const t=await r.text();if(!r.ok)throw new Error(`HTTP_${r.status}:${t.slice(0,120)}`);return t;});}
async function jsonFetch(url:string,init:RequestInit,timeout=12000){const r=await fetch(url,{...init,signal:AbortSignal.timeout(timeout)});const text=await r.text();if(!r.ok)throw new Error(`HTTP_${r.status}:${text.slice(0,160)}`);try{return JSON.parse(text);}catch{throw new Error('INVALID_JSON');}}
function mkRecord(code:string,id:string,name:string,score:number,method:string,url:string,summary:string,evidence:any={}){return {source_code:code,source_record_id:id,signal_type:'international_watchlist_candidate',signal_status:'possible_match',match_method:method,match_confidence:score,title:'Posible coincidencia en fuente internacional oficial',summary,related_entity_name:name,relationship_type:'POSIBLE_COINCIDENCIA_LISTA_INTERNACIONAL',event_date:null,source_url:url,evidence:{...evidence,identity_guardrail:'candidate_requires_analyst_review'}};}

async function fetchICIJ(name:string){const checked_at=new Date().toISOString();if(!name)return {status:'no_name',source:'ICIJ_OFFSHORE',records:[],checked_at};try{const body={queries:{entity:{query:name,type:'Entity'},officer:{query:name,type:'Officer'},intermediary:{query:name,type:'Intermediary'}}};const data=await jsonFetch(ICIJ_RECONCILE,{method:'POST',headers:{'content-type':'application/json','accept':'application/json','user-agent':'ATLAS-AML/0.53'},body:JSON.stringify(body)},12000);const buckets=data?.responses||data||{},candidates:any[]=[];for(const [queryType,payload] of Object.entries(buckets)){for(const c of arr((payload as any)?.result||(payload as any)?.results))candidates.push({...c,_queryType:queryType});}const seen=new Set<string>(),records:any[]=[];for(const c of candidates.sort((a,b)=>(Number(b?.score)||0)-(Number(a?.score)||0))){const id=String(c?.id||c?.identifier||'').trim();if(!id||seen.has(id))continue;seen.add(id);const caption=String(c?.name||c?.caption||c?.label||id).trim(),s=clamp01(c?.score),exact=norm(caption)===norm(name),confidence=s==null?(exact?.92:null):Math.min(s,exact?.98:.94);records.push({source_record_id:`icij:${id}`,signal_type:'offshore_database_candidate',signal_status:'possible_match',match_method:exact?'icij_reconciliation_exact_name':'icij_reconciliation_name',match_confidence:confidence,title:'Posible coincidencia en ICIJ Offshore Leaks',summary:`${caption} \u00b7 candidato ${String(c?._queryType||'node')}`,related_entity_name:caption,relationship_type:'POSIBLE_COINCIDENCIA_OFFSHORE',event_date:null,source_url:`https://offshoreleaks.icij.org/nodes/${encodeURIComponent(id)}`,evidence:{icij_node_id:id,query_type:c?._queryType||null,reconciliation_score:c?.score??null,identity_guardrail:'candidate_only_name_reconciliation'}});if(records.length>=8)break;}return {status:'fresh',source:'ICIJ_OFFSHORE',records,checked_at,coverage:{mode:'official_api',endpoint:'ICIJ reconciliation API'}};}catch(e){return {status:'degraded',source:'ICIJ_OFFSHORE',records:[],checked_at,error:String(e)};}}

function atlasSchema(entityType:string){const t=norm(entityType);if(t.includes('persona')||t.includes('natural')||t==='person')return 'Person';if(t.includes('empresa')||t.includes('jurid')||t.includes('company')||t.includes('organization'))return 'Organization';return 'LegalEntity';}
function sourceFamily(datasets:string[]){const d=datasets.map(norm).join(' ');if(d.includes('ofac'))return 'OFAC';if(d.includes('un sc')||d.includes('un sanctions'))return 'UN_SANCTIONS';if(d.includes('eu ')||d.includes('eu_'))return 'EU_SANCTIONS';if(d.includes('uk ')||d.includes('gb_')||d.includes('fcdo'))return 'UK_SANCTIONS';if(d.includes('world bank'))return 'WORLD_BANK';if(d.includes('inter american development bank')||d.includes('iadb')||d.includes('idb'))return 'IDB_SANCTIONS';return 'OPENSANCTIONS';}
async function fetchOpenSanctions(name:string,rut:string,entityType:string){const checked_at=new Date().toISOString(),key=Deno.env.get('OPENSANCTIONS_API_KEY');if(!key)return {status:'credential_missing',source:'OPENSANCTIONS',records:[],checked_at,coverage:{endpoint:'/match/default'}};if(!name&&!rut)return {status:'no_identity',source:'OPENSANCTIONS',records:[],checked_at};try{const properties:any={};if(name)properties.name=[name];if(rut)properties.taxNumber=[cleanRut(rut)];const data=await jsonFetch(OPENSANCTIONS_MATCH,{method:'POST',headers:{'content-type':'application/json','accept':'application/json','authorization':`ApiKey ${key}`,'user-agent':'ATLAS-AML/0.53'},body:JSON.stringify({queries:{atlas:{schema:atlasSchema(entityType),properties}}})},14000);const result=arr(data?.responses?.atlas?.results),records:any[]=[];for(const c of result.slice(0,10)){const s=clamp01(c?.score);if(s!=null&&s<.60)continue;const props=c?.properties||{},topics=unique(arr(props?.topics).map(String)),datasets=unique(arr(c?.datasets||props?.datasets).map(String)),family=sourceFamily(datasets),caption=String(c?.caption||arr(props?.name)[0]||c?.id||'Candidato OpenSanctions');records.push({source_code:family,source_record_id:`opensanctions:${c?.id||caption}`,signal_type:'international_watchlist_candidate',signal_status:'possible_match',match_method:'opensanctions_match_api',match_confidence:s,title:'Posible coincidencia en screening internacional',summary:[caption,topics.slice(0,4).join(', '),datasets.slice(0,3).join(', ')].filter(Boolean).join(' \u00b7 '),related_entity_name:caption,relationship_type:'POSIBLE_COINCIDENCIA_LISTA_INTERNACIONAL',event_date:null,source_url:c?.id?`https://www.opensanctions.org/entities/${encodeURIComponent(c.id)}/`:'https://www.opensanctions.org/',evidence:{opensanctions_id:c?.id||null,topics,datasets,identity_guardrail:'candidate_requires_analyst_review'}});}return {status:'fresh',source:'OPENSANCTIONS',records,checked_at,coverage:{mode:'aggregator',endpoint:'/match/default'}};}catch(e){const msg=String(e);return {status:msg.includes('HTTP_429')?'quota_exhausted':'degraded',source:'OPENSANCTIONS',records:[],checked_at,error:msg};}}

async function directUN(name:string){const checked_at=new Date().toISOString();try{const xml=await textFetch(UN_XML,15000),blocks=[...(xml.match(/<INDIVIDUAL>[\s\S]*?<\/INDIVIDUAL>/g)||[]),...(xml.match(/<ENTITY>[\s\S]*?<\/ENTITY>/g)||[])],records:any[]=[];for(const b of blocks){const val=(tag:string)=>String(b.match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`,'i'))?.[1]||'').replace(/<!\[CDATA\[|\]\]>/g,'').trim();const primary=[val('FIRST_NAME'),val('SECOND_NAME'),val('THIRD_NAME'),val('FOURTH_NAME')].filter(Boolean).join(' ').trim()||val('NAME');const aliases=[...b.matchAll(/<ALIAS_NAME>([\s\S]*?)<\/ALIAS_NAME>/gi)].map(m=>m[1].replace(/<!\[CDATA\[|\]\]>/g,'').trim());for(const cand of [primary,...aliases].filter(Boolean)){const s=scoreName(name,cand);if(s>=.68){const ref=val('REFERENCE_NUMBER')||val('DATAID')||cand;records.push(mkRecord('UN_SANCTIONS',`un:${ref}:${norm(cand)}`,cand,s,'un_official_xml_name_match','https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',`ONU \u00b7 ${ref}`,{reference_number:ref,official_direct:true}));break;}}if(records.length>=12)break;}return {status:'fresh',source:'UN_SANCTIONS',records,checked_at,coverage:{mode:'official_direct',endpoint:UN_XML}};}catch(e){return {status:'degraded',source:'UN_SANCTIONS',records:[],checked_at,error:String(e)};}}

async function directOFAC(name:string){const checked_at=new Date().toISOString();try{const [sdn,alt,cons,calt]=await Promise.all([textFetch(OFAC_SDN),textFetch(OFAC_ALT),textFetch(OFAC_CONS),textFetch(OFAC_CONS_ALT)]),records:any[]=[];const scan=(text:string,kind:string,alias=false)=>{for(const line of text.split(/\r?\n/)){if(!line.trim())continue;const row=csvLine(line),id=String(row[0]||'').trim(),cand=String(alias?row[3]:row[1]||'').trim();if(!cand)continue;const s=scoreName(name,cand);if(s>=.72)records.push(mkRecord('OFAC',`ofac:${kind}:${id}:${norm(cand)}`,cand,s,alias?'ofac_official_alias_csv':'ofac_official_primary_csv','https://ofac.treasury.gov/sanctions-list-service',`OFAC ${kind}${row[3]&&!alias?` \u00b7 ${row[3]}`:''}`,{ofac_id:id,list:kind,official_direct:true}));if(records.length>=14)break;}};scan(sdn,'SDN');scan(alt,'SDN',true);scan(cons,'NON_SDN');scan(calt,'NON_SDN',true);const seen=new Set();return {status:'fresh',source:'OFAC',records:records.filter(r=>{const k=norm(r.related_entity_name);if(seen.has(k))return false;seen.add(k);return true;}).slice(0,14),checked_at,coverage:{mode:'official_direct',endpoint:'OFAC CSV SDN + consolidated'}};}catch(e){return {status:'degraded',source:'OFAC',records:[],checked_at,error:String(e)};}}

async function directUK(name:string){const checked_at=new Date().toISOString();try{const text=await textFetch(UK_CSV),lines=text.split(/\r?\n/).filter(Boolean),head=csvLine(lines.shift()||''),lower=head.map(norm),nameIdx=lower.map((h,i)=>/name/.test(h)?i:-1).filter(i=>i>=0),uidIdx=lower.findIndex(h=>h==='unique id'||h.includes('unique id')),records:any[]=[];for(const line of lines){const row=csvLine(line);const candidates=nameIdx.map(i=>String(row[i]||'').trim()).filter(Boolean);let best='',s=0;for(const c of candidates){const x=scoreName(name,c);if(x>s){s=x;best=c;}}if(s>=.70){const uid=String(row[uidIdx]||best);records.push(mkRecord('UK_SANCTIONS',`uk:${uid}:${norm(best)}`,best,s,'uk_official_csv_name_match','https://www.gov.uk/government/publications/the-uk-sanctions-list',`UK Sanctions List \u00b7 ${uid}`,{unique_id:uid,official_direct:true}));if(records.length>=12)break;}}return {status:'fresh',source:'UK_SANCTIONS',records,checked_at,coverage:{mode:'official_direct',endpoint:UK_CSV}};}catch(e){return {status:'degraded',source:'UK_SANCTIONS',records:[],checked_at,error:String(e)};}}

async function directEU(name:string){const checked_at=new Date().toISOString();try{const text=await textFetch(EU_CSV,18000),lines=text.split(/\r?\n/).filter(Boolean),head=csvLine(lines.shift()||'', ';'),lower=head.map(norm),nameIdx=lower.map((h,i)=>/(whole.?name|namealias|name)/.test(h)?i:-1).filter(i=>i>=0),idIdx=lower.findIndex(h=>h.includes('entity logicalid')||h==='logicalid'),records:any[]=[];for(const line of lines){const row=csvLine(line,';');const candidates=nameIdx.map(i=>String(row[i]||'').trim()).filter(Boolean);let best='',s=0;for(const c of candidates){const x=scoreName(name,c);if(x>s){s=x;best=c;}}if(s>=.70){const id=String(row[idIdx]||best);records.push(mkRecord('EU_SANCTIONS',`eu:${id}:${norm(best)}`,best,s,'eu_official_csv_name_match','https://data.europa.eu/data/datasets/consolidated-list-of-persons-groups-and-entities-subject-to-eu-financial-sanctions',`UE \u00b7 logical id ${id}`,{logical_id:id,official_direct:true}));if(records.length>=12)break;}}return {status:'fresh',source:'EU_SANCTIONS',records,checked_at,coverage:{mode:'official_direct',endpoint:EU_CSV}};}catch(e){return {status:'degraded',source:'EU_SANCTIONS',records:[],checked_at,error:String(e)};}}

async function directIDB(name:string){const checked_at=new Date().toISOString();try{const data=await jsonFetch(`${IDB_API}&limit=100&q=${encodeURIComponent(name)}`,{headers:{accept:'application/json','user-agent':'ATLAS-AML/0.53'}},12000),rows=arr(data?.result?.records),idb:any[]=[],wbg:any[]=[];for(const r of rows){const cand=String(r?.Title||'').trim(),s=scoreName(name,cand);if(s<.68)continue;const src=String(r?.Source||''),isWbg=/WBG|World Bank/i.test(src),code=isWbg?'WORLD_BANK':'IDB_SANCTIONS',rec=mkRecord(code,`${isWbg?'wbg-xd':'idb'}:${r?._id||norm(cand)}`,cand,s,'idb_official_datastore_name_match','https://data.iadb.org/dataset/dataset-of-sanctioned-firms-and-individuals',[src,r?.['Prohibited Practice'],r?.To].filter(Boolean).join(' \u00b7 '),{idb_row_id:r?._id||null,source:src,country:r?.Country||null,nationality:r?.Nationality||null,from:r?.From||null,to:r?.To||null,official_direct:true,cross_debarment_only:isWbg});(isWbg?wbg:idb).push(rec);}return [{status:'fresh',source:'IDB_SANCTIONS',records:idb.slice(0,12),checked_at,coverage:{mode:'official_direct',endpoint:IDB_API}},{status:'fresh',source:'WORLD_BANK',records:wbg.slice(0,12),checked_at,coverage:{mode:'official_cross_debarment_fallback',via:'IDB open data',scope:'WBG cross-debarment only'}}];}catch(e){const x={status:'degraded',records:[],checked_at,error:String(e)};return [{...x,source:'IDB_SANCTIONS'},{...x,source:'WORLD_BANK'}];}}

async function directFallback(name:string){const [un,ofac,uk,eu,idbPair]=await Promise.all([directUN(name),directOFAC(name),directUK(name),directEU(name),directIDB(name)]);return {UN_SANCTIONS:un,OFAC:ofac,UK_SANCTIONS:uk,EU_SANCTIONS:eu,IDB_SANCTIONS:idbPair[0],WORLD_BANK:idbPair[1]};}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({error:'METHOD_NOT_ALLOWED'}),{status:405,headers:cors});try{const body=await req.json(),name=String(body?.name||'').trim(),rut=String(body?.rut||'').trim(),entityType=String(body?.entity_type||body?.entityType||'').trim();if(!name&&!rut)return new Response(JSON.stringify({error:'ENTITY_REQUIRED'}),{status:400,headers:cors});const [icij,openSanctions]=await Promise.all([fetchICIJ(name),fetchOpenSanctions(name,rut,entityType)]);const sources:any={ICIJ_OFFSHORE:icij,OPENSANCTIONS:openSanctions};const osUsable=openSanctions?.status==='fresh';if(osUsable){for(const rec of arr(openSanctions?.records)){const code=String(rec?.source_code||'OPENSANCTIONS');if(code==='OPENSANCTIONS')continue;if(!sources[code])sources[code]={status:'fresh',source:code,records:[],checked_at:openSanctions.checked_at,coverage:{via:'OpenSanctions /match/default',mode:'aggregator'}};sources[code].records.push(rec);}}else{Object.assign(sources,await directFallback(name));}return new Response(JSON.stringify({ok:true,mode:'LIVE_NO_PERSIST',entity:{name:name||null,rut:rut||null,entity_type:entityType||null},sources,routing:{opensanctions_status:openSanctions?.status||'unknown',fallback_used:!osUsable,fallback_reason:osUsable?null:(openSanctions?.status||'unknown'),direct_sources:['UN_SANCTIONS','OFAC','EU_SANCTIONS','UK_SANCTIONS','IDB_SANCTIONS','WORLD_BANK']},guardrails:{persisted:false,score_mutation:false,risk_transfer:false,identity_promotion:false,possible_match_requires_review:true,icij_attribution_required:true,opensanctions_license_and_api_key_required:true,official_direct_fallback:true,world_bank_fallback_scope:'IDB WBG cross-debarment only'}}),{headers:cors});}catch(e){return new Response(JSON.stringify({ok:false,error:String(e)}),{status:500,headers:cors});}});
