import {N,csv,text,score,rec,bad} from './util.ts';
const UN='https://scsanctions.un.org/resources/xml/en/name/consolidated.xml';
const OFAC=['https://www.treasury.gov/ofac/downloads/sdn.csv','https://www.treasury.gov/ofac/downloads/alt.csv','https://www.treasury.gov/ofac/downloads/consolidated/cons_prim.csv','https://www.treasury.gov/ofac/downloads/consolidated/cons_alt.csv'];
const UK='https://sanctionslist.fcdo.gov.uk/docs/UK-Sanctions-List.csv';

export async function un(name:string){const checked_at=new Date().toISOString();try{const x=await text(UN),blocks=[...(x.match(/<INDIVIDUAL>[\s\S]*?<\/INDIVIDUAL>/g)||[]),...(x.match(/<ENTITY>[\s\S]*?<\/ENTITY>/g)||[])],out=[];for(const b of blocks){const v=(tag:string)=>String(b.match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`,'i'))?.[1]||'').replace(/<!\[CDATA\[|\]\]>/g,'').trim(),primary=[v('FIRST_NAME'),v('SECOND_NAME'),v('THIRD_NAME'),v('FOURTH_NAME')].filter(Boolean).join(' ')||v('NAME'),aliases=[...b.matchAll(/<ALIAS_NAME>([\s\S]*?)<\/ALIAS_NAME>/gi)].map(m=>m[1].replace(/<!\[CDATA\[|\]\]>/g,'').trim());for(const c of [primary,...aliases].filter(Boolean)){const s=score(name,c);if(s>=.62){const id=v('REFERENCE_NUMBER')||v('DATAID')||c;out.push(rec('UN_SANCTIONS',`un:${id}:${N(c)}`,c,s,'un_official_xml_name_match','https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',`ONU · ${id}`,{reference_number:id,official_direct:true}));break;}}if(out.length>=12)break;}return {status:'fresh',source:'UN_SANCTIONS',records:out,checked_at,coverage:{mode:'official_direct'}};}catch(e){return bad('UN_SANCTIONS',e);}}

export async function ofac(name:string){const checked_at=new Date().toISOString();try{const xs=await Promise.all(OFAC.map(u=>text(u))),out:any[]=[];const scan=(x:string,kind:string,alias=false)=>{for(const line of x.split(/\r?\n/)){if(!line.trim())continue;const r=csv(line),id=String(r[0]||''),c=String(alias?r[3]:r[1]||'').trim(),s=score(name,c);if(c&&s>=.68)out.push(rec('OFAC',`ofac:${kind}:${id}:${N(c)}`,c,s,alias?'ofac_official_alias_csv':'ofac_official_primary_csv','https://ofac.treasury.gov/sanctions-list-service',`OFAC ${kind}`,{ofac_id:id,list:kind,official_direct:true}));if(out.length>=14)break;}};scan(xs[0],'SDN');scan(xs[1],'SDN',true);scan(xs[2],'NON_SDN');scan(xs[3],'NON_SDN',true);const seen=new Set();return {status:'fresh',source:'OFAC',records:out.filter(r=>{const k=N(r.related_entity_name);if(seen.has(k))return false;seen.add(k);return true;}).slice(0,14),checked_at,coverage:{mode:'official_direct'}};}catch(e){return bad('OFAC',e);}}

export async function uk(name:string){const checked_at=new Date().toISOString();try{const x=await text(UK),lines=x.split(/\r?\n/).filter(Boolean),head=csv(lines.shift()||''),h=head.map(N),idxs=h.map((z,i)=>z.includes('name')&&!z.includes('language')?i:-1).filter(i=>i>=0),id=h.findIndex(z=>z==='unique id'||z.includes('unique id')),out=[];for(const line of lines){const r=csv(line),cs=idxs.map(i=>String(r[i]||'').trim()).filter(Boolean);let best='',s=0;for(const c of cs){const z=score(name,c);if(z>s){s=z;best=c;}}if(s>=.66){const uid=String(r[id]||best);out.push(rec('UK_SANCTIONS',`uk:${uid}:${N(best)}`,best,s,'uk_official_csv_name_match','https://www.gov.uk/government/publications/the-uk-sanctions-list',`UK Sanctions List · ${uid}`,{unique_id:uid,official_direct:true}));if(out.length>=12)break;}}return {status:'fresh',source:'UK_SANCTIONS',records:out,checked_at,coverage:{mode:'official_direct'}};}catch(e){return bad('UK_SANCTIONS',e);}}
