import {A,U,N,json,rec,bad} from './util.ts';
const ICIJ='https://offshoreleaks.icij.org/api/v1/reconcile';
const OS='https://api.opensanctions.org/match/default';

export async function icij(name:string){const checked_at=new Date().toISOString();if(!name)return {status:'no_name',source:'ICIJ_OFFSHORE',records:[],checked_at};try{const d=await json(ICIJ,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({queries:{entity:{query:name,type:'Entity'},officer:{query:name,type:'Officer'},intermediary:{query:name,type:'Intermediary'}}})});const out:any[]=[];for(const [kind,p] of Object.entries(d?.responses||d||{})){for(const c of A((p as any)?.result||(p as any)?.results)){const id=String(c?.id||c?.identifier||'').trim(),caption=String(c?.name||c?.caption||c?.label||id).trim();if(!id||!caption)continue;const raw=Number(c?.score),s=Number.isFinite(raw)?Math.max(0,Math.min(1,raw>1?raw/100:raw)):null;out.push({source_record_id:`icij:${id}`,signal_type:'offshore_database_candidate',signal_status:'possible_match',match_method:N(caption)===N(name)?'icij_reconciliation_exact_name':'icij_reconciliation_name',match_confidence:s,title:'Posible coincidencia en ICIJ Offshore Leaks',summary:`${caption} · candidato ${kind}`,related_entity_name:caption,relationship_type:'POSIBLE_COINCIDENCIA_OFFSHORE',event_date:null,source_url:`https://offshoreleaks.icij.org/nodes/${encodeURIComponent(id)}`,evidence:{icij_node_id:id,query_type:kind,identity_guardrail:'candidate_only_name_reconciliation'}});if(out.length>=8)break;}}return {status:'fresh',source:'ICIJ_OFFSHORE',records:out,checked_at,coverage:{mode:'official_api'}};}catch(e){return bad('ICIJ_OFFSHORE',e);}}

function schema(t:string){const x=N(t);return x.includes('persona')||x.includes('natural')||x==='person'?'Person':x.includes('empresa')||x.includes('jurid')||x.includes('company')||x.includes('organization')?'Organization':'LegalEntity';}
function family(ds:string[]){const d=ds.map(N).join(' ');if(d.includes('ofac'))return'OFAC';if(d.includes('un sc')||d.includes('un sanctions'))return'UN_SANCTIONS';if(d.includes('eu ')||d.includes('eu_'))return'EU_SANCTIONS';if(d.includes('uk ')||d.includes('gb_')||d.includes('fcdo'))return'UK_SANCTIONS';if(d.includes('world bank'))return'WORLD_BANK';if(d.includes('inter american development bank')||d.includes('iadb')||d.includes('idb'))return'IDB_SANCTIONS';return'OPENSANCTIONS';}
export async function opensanctions(name:string,rut:string,type:string){const checked_at=new Date().toISOString(),key=Deno.env.get('OPENSANCTIONS_API_KEY');if(!key)return {status:'credential_missing',source:'OPENSANCTIONS',records:[],checked_at};try{const props:any={};if(name)props.name=[name];if(rut)props.taxNumber=[rut.replace(/[^0-9kK]/g,'').toUpperCase()];const d=await json(OS,{method:'POST',headers:{'content-type':'application/json','accept':'application/json','authorization':`ApiKey ${key}`},body:JSON.stringify({queries:{atlas:{schema:schema(type),properties:props}}})});const out=[];for(const c of A(d?.responses?.atlas?.results).slice(0,10)){const raw=Number(c?.score),s=Number.isFinite(raw)?Math.max(0,Math.min(1,raw>1?raw/100:raw)):null;if(s!=null&&s<.5)continue;const p=c?.properties||{},ds=U(A(c?.datasets||p?.datasets).map(String)) as string[],caption=String(c?.caption||A(p?.name)[0]||c?.id||'Candidato');out.push({...rec(family(ds),`opensanctions:${c?.id||caption}`,caption,s??0,'opensanctions_match_api',c?.id?`https://www.opensanctions.org/entities/${encodeURIComponent(c.id)}/`:'https://www.opensanctions.org/',caption,{opensanctions_id:c?.id||null,datasets:ds}),match_confidence:s});}return {status:'fresh',source:'OPENSANCTIONS',records:out,checked_at,coverage:{mode:'aggregator'}};}catch(e){const x=bad('OPENSANCTIONS',e);if(String(e).includes('HTTP_429'))x.status='quota_exhausted';return x;}}
