-- ATLAS Observatorio · Infrastructure control plane
-- Stores low-frequency metric history and exposes aggregate Postgres telemetry
-- only to the trusted service role. Browser clients never receive DB secrets.

create table if not exists public.obs_infra_snapshot_history (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  provider text not null,
  metric_key text not null,
  value_numeric numeric,
  value_text text,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.obs_infra_snapshot_history enable row level security;
revoke all on table public.obs_infra_snapshot_history from anon, authenticated;
grant select, insert on table public.obs_infra_snapshot_history to service_role;
grant usage, select on sequence public.obs_infra_snapshot_history_id_seq to service_role;

create index if not exists obs_infra_snapshot_history_lookup_idx
  on public.obs_infra_snapshot_history (provider, metric_key, captured_at desc);

create or replace function public.obs_infra_local_metrics()
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_database_bytes bigint;
  v_connections_total integer;
  v_connections_active integer;
  v_public_tables integer;
  v_public_tables_bytes bigint;
  v_auth_users bigint;
  v_storage_objects bigint;
  v_storage_bytes bigint;
  v_largest_tables jsonb;
  v_unused_indexes integer;
  v_tables_without_pk integer;
  v_cache_hit_pct numeric;
  v_xact_commit bigint;
  v_deadlocks bigint;
  v_temp_bytes bigint;
begin
  select pg_database_size(current_database()) into v_database_bytes;

  select count(*)::int,
         count(*) filter (where state = 'active')::int
    into v_connections_total, v_connections_active
  from pg_stat_activity
  where datname = current_database();

  select count(*)::int,
         coalesce(sum(pg_total_relation_size(to_regclass(format('%I.%I', schemaname, tablename)))), 0)::bigint
    into v_public_tables, v_public_tables_bytes
  from pg_tables
  where schemaname = 'public';

  select count(*) into v_auth_users from auth.users;
  select count(*) into v_storage_objects from storage.objects;
  select coalesce(sum(
    case when coalesce(metadata->>'size','') ~ '^[0-9]+$'
      then (metadata->>'size')::bigint else 0 end
  ), 0)::bigint
    into v_storage_bytes
  from storage.objects;

  select count(*)::int
    into v_unused_indexes
  from pg_stat_user_indexes
  where idx_scan = 0;

  select count(*)::int
    into v_tables_without_pk
  from pg_tables t
  where t.schemaname not in ('pg_catalog', 'information_schema')
    and not exists (
      select 1
      from pg_index i
      join pg_class c on c.oid = i.indrelid
      join pg_namespace n on n.oid = c.relnamespace
      where i.indisprimary
        and n.nspname = t.schemaname
        and c.relname = t.tablename
    );

  select case when (blks_hit + blks_read) > 0
              then round((100.0 * blks_hit / (blks_hit + blks_read))::numeric, 2)
              else null end,
         xact_commit,
         deadlocks,
         temp_bytes
    into v_cache_hit_pct, v_xact_commit, v_deadlocks, v_temp_bytes
  from pg_stat_database
  where datname = current_database();

  select coalesce(jsonb_agg(x order by (x->>'bytes')::bigint desc), '[]'::jsonb)
    into v_largest_tables
  from (
    select jsonb_build_object(
      'table', tablename,
      'bytes', pg_total_relation_size(to_regclass(format('%I.%I', schemaname, tablename)))
    ) as x
    from pg_tables
    where schemaname = 'public'
    order by pg_total_relation_size(to_regclass(format('%I.%I', schemaname, tablename))) desc
    limit 6
  ) q;

  return jsonb_build_object(
    'generated_at', now(),
    'database_bytes', v_database_bytes,
    'connections_total', v_connections_total,
    'connections_active', v_connections_active,
    'max_connections', current_setting('max_connections')::int,
    'shared_buffers', current_setting('shared_buffers'),
    'public_tables', v_public_tables,
    'public_tables_bytes', v_public_tables_bytes,
    'auth_users', v_auth_users,
    'storage_objects', v_storage_objects,
    'storage_bytes', v_storage_bytes,
    'largest_tables', v_largest_tables,
    'unused_indexes', v_unused_indexes,
    'tables_without_primary_key', v_tables_without_pk,
    'cache_hit_pct', v_cache_hit_pct,
    'xact_commit', v_xact_commit,
    'deadlocks', v_deadlocks,
    'temp_bytes', v_temp_bytes
  );
end;
$$;

revoke all on function public.obs_infra_local_metrics() from public, anon, authenticated;
grant execute on function public.obs_infra_local_metrics() to service_role;
comment on function public.obs_infra_local_metrics() is
  'Aggregate infrastructure metrics; callable only by trusted service role through the authenticated infrastructure collector.';
