-- ATLAS Fintech continuous enrichment engine
-- Reproduces the production schema/runtime introduced after 0014.

alter table public.aml_fintech_entity
  add column if not exists business_model_basis text,
  add column if not exists business_model_confidence numeric(5,4),
  add column if not exists target_customer_basis text,
  add column if not exists target_customer_confidence numeric(5,4),
  add column if not exists revenue_model_basis text,
  add column if not exists revenue_model_confidence numeric(5,4),
  add column if not exists profile_refreshed_at timestamptz;

alter table public.aml_fintech_candidate
  add column if not exists enrichment_status text not null default 'PENDING',
  add column if not exists enrichment_refreshed_at timestamptz,
  add column if not exists identity_candidate_rut text,
  add column if not exists identity_candidate_legal_name text,
  add column if not exists identity_candidate_confidence numeric(5,4),
  add column if not exists identity_candidate_source_url text,
  add column if not exists classification_hint jsonb not null default '{}'::jsonb;

create table if not exists public.aml_fintech_enrichment_fact (
  fact_id bigint generated by default as identity primary key,
  evidence_key text not null unique,
  subject_type text not null check (subject_type in ('ENTITY','CANDIDATE')),
  subject_key text not null,
  field_code text not null,
  value_text text,
  value_json jsonb not null default '{}'::jsonb,
  evidence_class text not null check (evidence_class in ('OBSERVED_OFFICIAL','DECLARED','INFERRED')),
  confidence numeric(5,4) check (confidence between 0 and 1),
  source_code text references public.aml_fintech_source_catalog(source_code),
  source_url text,
  evidence_excerpt text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  observed_at timestamptz not null default now()
);

create table if not exists public.aml_fintech_enrichment_run (
  run_id bigint generated by default as identity primary key,
  run_type text not null default 'WEB_PROFILE',
  status text not null default 'STARTED',
  rows_requested integer not null default 0,
  rows_processed integer not null default 0,
  rows_failed integer not null default 0,
  payment_rows_seen integer not null default 0,
  detail jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists aml_fintech_enrichment_subject_idx on public.aml_fintech_enrichment_fact(subject_type,subject_key,last_seen_at desc);
create index if not exists aml_fintech_enrichment_field_idx on public.aml_fintech_enrichment_fact(field_code,subject_type);
create index if not exists aml_fintech_enrichment_source_idx on public.aml_fintech_enrichment_fact(source_code,last_seen_at desc);

alter table public.aml_fintech_enrichment_fact enable row level security;
alter table public.aml_fintech_enrichment_run enable row level security;
revoke all on public.aml_fintech_enrichment_fact from public,anon,authenticated;
revoke all on public.aml_fintech_enrichment_run from public,anon,authenticated;
grant select,insert,update,delete on public.aml_fintech_enrichment_fact to service_role;
grant select,insert,update,delete on public.aml_fintech_enrichment_run to service_role;
grant usage,select on sequence public.aml_fintech_enrichment_fact_fact_id_seq to service_role;
grant usage,select on sequence public.aml_fintech_enrichment_run_run_id_seq to service_role;

insert into public.aml_fintech_source_catalog(source_code,label,source_type,authority_level,source_url,cadence,active,notes)
values
('CMF_PAYMENTS','CMF · Registros de emisores y operadores de pago','REGULATORY_REGISTRY','OFFICIAL_OPEN','https://www.cmfchile.cl/','SEMANAL',true,'Emisores de tarjetas de crédito, emisores de prepago y operadores de tarjetas publicados por CMF.'),
('COMPANY_WEB','Sitios corporativos y documentación pública','CORPORATE_DISCLOSURE','DECLARED_OPEN',null,'MENSUAL',true,'Información declarada por la propia entidad en su sitio web y páginas legales.')
on conflict (source_code) do update set
  label=excluded.label,source_type=excluded.source_type,authority_level=excluded.authority_level,
  source_url=excluded.source_url,cadence=excluded.cadence,active=true,notes=excluded.notes,refreshed_at=now();

create or replace function public.aml_fintech_enrichment_batch(p_limit integer default 20)
returns jsonb language sql stable security definer set search_path='public','pg_temp' as $$
with q as (
  select 'CANDIDATE'::text subject_type,c.candidate_id::text subject_key,c.name_raw display_name,c.rut_raw rut,c.website,c.domain,c.source_code,c.source_url,c.enrichment_refreshed_at refreshed_at,
         case when c.source_code='FINTECHILE_MEMBERS' then 1 when c.source_code='CMF_PAYMENTS' then 2 else 4 end priority
  from public.aml_fintech_candidate c
  where c.matched_fintech_id is null and c.website is not null and btrim(c.website)<>''
  union all
  select 'ENTITY',e.fintech_id,coalesce(e.brand,e.legal_name),e.rut,e.website,null::text,'COMPANY_WEB',e.website,e.profile_refreshed_at,3
  from public.aml_fintech_entity e where e.website is not null and btrim(e.website)<>''
), ranked as (
  select * from q order by refreshed_at asc nulls first,priority,display_name limit greatest(1,least(coalesce(p_limit,20),40))
)
select coalesce(jsonb_agg(jsonb_build_object(
  'subject_type',subject_type,'subject_key',subject_key,'display_name',display_name,'rut',rut,'website',website,'domain',domain,
  'source_code',source_code,'source_url',source_url,'refreshed_at',refreshed_at
) order by refreshed_at asc nulls first,priority,display_name),'[]'::jsonb) from ranked;
$$;
revoke all on function public.aml_fintech_enrichment_batch(integer) from public,anon,authenticated;
grant execute on function public.aml_fintech_enrichment_batch(integer) to service_role;

create or replace function public.aml_fintech_ingest_enrichment(p_rows jsonb)
returns jsonb language plpgsql security definer set search_path='public','pg_temp' as $$
declare r jsonb; f jsonb; v_processed int:=0; v_facts int:=0; v_identity_hints int:=0; v_rut_norm text; v_sii_name text;
begin
  if p_rows is null or jsonb_typeof(p_rows)<>'array' then raise exception 'p_rows must be an array'; end if;
  for r in select value from jsonb_array_elements(p_rows) loop
    v_processed:=v_processed+1;
    for f in select value from jsonb_array_elements(coalesce(r->'facts','[]'::jsonb)) loop
      insert into public.aml_fintech_enrichment_fact(evidence_key,subject_type,subject_key,field_code,value_text,value_json,evidence_class,confidence,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
      values(f->>'evidence_key',r->>'subject_type',r->>'subject_key',f->>'field_code',f->>'value_text',coalesce(f->'value_json','{}'::jsonb),coalesce(f->>'evidence_class','INFERRED'),nullif(f->>'confidence','')::numeric,coalesce(f->>'source_code','COMPANY_WEB'),coalesce(f->>'source_url',r->>'website'),left(f->>'evidence_excerpt',1000),coalesce(nullif(f->>'observed_at','')::timestamptz,now()),now(),coalesce(nullif(f->>'observed_at','')::timestamptz,now()))
      on conflict (evidence_key) do update set value_text=excluded.value_text,value_json=excluded.value_json,evidence_class=excluded.evidence_class,confidence=excluded.confidence,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;
      v_facts:=v_facts+1;
    end loop;
    if r->>'subject_type'='CANDIDATE' then
      v_rut_norm:=public.aml_fintech_norm_rut(r->>'legal_rut'); v_sii_name:=null;
      if coalesce(v_rut_norm,'')<>'' and coalesce(nullif(r->>'legal_rut_confidence','')::numeric,0)>=0.96 then
        select sc.legal_name into v_sii_name from public.aml_sii_registry_company sc where public.aml_fintech_norm_rut(sc.rut)=v_rut_norm limit 1;
      end if;
      update public.aml_fintech_candidate c set
        enrichment_status=case when coalesce(r->>'fetch_status','')='OK' then 'ENRICHED' else 'FETCH_FAILED' end,
        enrichment_refreshed_at=now(),
        identity_candidate_rut=case when v_sii_name is not null then r->>'legal_rut' else c.identity_candidate_rut end,
        identity_candidate_legal_name=coalesce(v_sii_name,c.identity_candidate_legal_name),
        identity_candidate_confidence=case when v_sii_name is not null then nullif(r->>'legal_rut_confidence','')::numeric else c.identity_candidate_confidence end,
        identity_candidate_source_url=case when v_sii_name is not null then r->>'legal_rut_source_url' else c.identity_candidate_source_url end,
        classification_hint=jsonb_strip_nulls(jsonb_build_object(
          'business_model',r->>'business_model_hint','business_model_confidence',nullif(r->>'business_model_confidence','')::numeric,
          'target_customer',r->>'target_customer_hint','target_customer_confidence',nullif(r->>'target_customer_confidence','')::numeric,
          'revenue_model',r->>'revenue_model_hint','revenue_model_confidence',nullif(r->>'revenue_model_confidence','')::numeric,
          'products',coalesce(r->'product_hints','[]'::jsonb),'countries',coalesce(r->'country_hints','[]'::jsonb),
          'virtual_asset_signals',coalesce(r->'virtual_asset_signals','[]'::jsonb)))
      where c.candidate_id::text=r->>'subject_key';
      if v_sii_name is not null then v_identity_hints:=v_identity_hints+1; end if;
    elsif r->>'subject_type'='ENTITY' then
      update public.aml_fintech_entity e set
        business_model=case when e.business_model is null and nullif(r->>'business_model_confidence','')::numeric>=0.93 then r->>'business_model_hint' else e.business_model end,
        business_model_basis=case when e.business_model is null and nullif(r->>'business_model_confidence','')::numeric>=0.93 then 'INFERRED_COMPANY_WEB' else e.business_model_basis end,
        business_model_confidence=case when e.business_model is null and nullif(r->>'business_model_confidence','')::numeric>=0.93 then nullif(r->>'business_model_confidence','')::numeric else e.business_model_confidence end,
        target_customer=case when e.target_customer is null and nullif(r->>'target_customer_confidence','')::numeric>=0.93 then r->>'target_customer_hint' else e.target_customer end,
        target_customer_basis=case when e.target_customer is null and nullif(r->>'target_customer_confidence','')::numeric>=0.93 then 'INFERRED_COMPANY_WEB' else e.target_customer_basis end,
        target_customer_confidence=case when e.target_customer is null and nullif(r->>'target_customer_confidence','')::numeric>=0.93 then nullif(r->>'target_customer_confidence','')::numeric else e.target_customer_confidence end,
        revenue_model=case when e.revenue_model is null and nullif(r->>'revenue_model_confidence','')::numeric>=0.92 then r->>'revenue_model_hint' else e.revenue_model end,
        revenue_model_basis=case when e.revenue_model is null and nullif(r->>'revenue_model_confidence','')::numeric>=0.92 then 'INFERRED_COMPANY_WEB' else e.revenue_model_basis end,
        revenue_model_confidence=case when e.revenue_model is null and nullif(r->>'revenue_model_confidence','')::numeric>=0.92 then nullif(r->>'revenue_model_confidence','')::numeric else e.revenue_model_confidence end,
        profile_refreshed_at=now(),refreshed_at=now()
      where e.fintech_id=r->>'subject_key';
    end if;
  end loop;
  return jsonb_build_object('processed',v_processed,'facts_upserted',v_facts,'identity_hints_resolved_sii',v_identity_hints);
end;
$$;
revoke all on function public.aml_fintech_ingest_enrichment(jsonb) from public,anon,authenticated;
grant execute on function public.aml_fintech_ingest_enrichment(jsonb) to service_role;

create or replace function public.aml_fintech_enrichment_run_start(p_requested integer,p_payment_seen integer default 0)
returns bigint language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_id bigint; begin
  insert into public.aml_fintech_enrichment_run(rows_requested,payment_rows_seen) values(coalesce(p_requested,0),coalesce(p_payment_seen,0)) returning run_id into v_id;
  return v_id;
end; $$;
revoke all on function public.aml_fintech_enrichment_run_start(integer,integer) from public,anon,authenticated;
grant execute on function public.aml_fintech_enrichment_run_start(integer,integer) to service_role;

create or replace function public.aml_fintech_enrichment_run_finish(p_run_id bigint,p_processed integer,p_failed integer,p_payment_seen integer,p_status text,p_detail jsonb)
returns void language plpgsql security definer set search_path='public','pg_temp' as $$
begin
  update public.aml_fintech_enrichment_run set status=coalesce(p_status,'COMPLETED'),rows_processed=coalesce(p_processed,0),rows_failed=coalesce(p_failed,0),payment_rows_seen=coalesce(p_payment_seen,payment_rows_seen),detail=coalesce(p_detail,'{}'::jsonb),completed_at=now() where run_id=p_run_id;
end; $$;
revoke all on function public.aml_fintech_enrichment_run_finish(bigint,integer,integer,integer,text,jsonb) from public,anon,authenticated;
grant execute on function public.aml_fintech_enrichment_run_finish(bigint,integer,integer,integer,text,jsonb) to service_role;

create or replace function public.aml_fintech_sync_payment_regulatory()
returns jsonb language plpgsql security definer set search_path='public','pg_temp' as $$
declare rec record; service_code text; v_rows int:=0;
begin
  update public.aml_fintech_candidate cand set matched_fintech_id=e.fintech_id,candidate_status='MATCHED_EXISTING',match_method='EXACT_LEGAL_NAME_CMF_PAYMENT',match_score=0.99
  from public.aml_fintech_entity e
  where cand.source_code='CMF_PAYMENTS' and cand.matched_fintech_id is null and public.obs_normalize_text(cand.name_raw)=public.obs_normalize_text(e.legal_name);
  for rec in select candidate_id,matched_fintech_id,source_url,evidence from public.aml_fintech_candidate where source_code='CMF_PAYMENTS' and matched_fintech_id is not null loop
    for service_code in select jsonb_array_elements_text(coalesce(rec.evidence->'registries','[]'::jsonb)) loop
      insert into public.aml_fintech_regulatory_status(fintech_id,regulator,registry,service,status,source_url,observed_at)
      values(rec.matched_fintech_id,'CMF','CMF_PAYMENTS',service_code,'VIGENTE',rec.source_url,now())
      on conflict(fintech_id,regulator,registry,service) do update set status='VIGENTE',source_url=excluded.source_url,observed_at=now();
      v_rows:=v_rows+1;
    end loop;
  end loop;
  return jsonb_build_object('regulatory_rows_upserted',v_rows);
end; $$;
revoke all on function public.aml_fintech_sync_payment_regulatory() from public,anon,authenticated;
grant execute on function public.aml_fintech_sync_payment_regulatory() to service_role;

create or replace function public.obs_fintech_enrichment_status()
returns jsonb language plpgsql stable security definer set search_path='public','pg_temp' as $$
declare ok boolean; result jsonb;
begin
  select exists(select 1 from public.aml_allowed_users au where au.user_id=auth.uid() and au.enabled) into ok;
  if not ok then return jsonb_build_object('error','NOT_AUTHORIZED'); end if;
  select jsonb_build_object(
    'facts',(select count(*) from public.aml_fintech_enrichment_fact),
    'entity_profiles',(select count(*) from public.aml_fintech_entity where profile_refreshed_at is not null),
    'candidate_profiles',(select count(*) from public.aml_fintech_candidate where enrichment_refreshed_at is not null),
    'identity_hints',(select count(*) from public.aml_fintech_candidate where matched_fintech_id is null and identity_candidate_rut is not null),
    'business_model_classified',(select count(*) from public.aml_fintech_entity where business_model is not null),
    'target_customer_classified',(select count(*) from public.aml_fintech_entity where target_customer is not null),
    'revenue_model_classified',(select count(*) from public.aml_fintech_entity where revenue_model is not null),
    'virtual_asset_signal_subjects',(select count(distinct subject_type||':'||subject_key) from public.aml_fintech_enrichment_fact where field_code='VIRTUAL_ASSET_SIGNAL'),
    'latest_run',(select to_jsonb(x) from (select run_id,run_type,status,rows_requested,rows_processed,rows_failed,payment_rows_seen,started_at,completed_at from public.aml_fintech_enrichment_run order by started_at desc limit 1) x),
    'refreshed_at',(select max(last_seen_at) from public.aml_fintech_enrichment_fact)
  ) into result;
  return result;
end; $$;
revoke all on function public.obs_fintech_enrichment_status() from public,anon;
grant execute on function public.obs_fintech_enrichment_status() to authenticated;

create or replace function public.obs_fintech_enrichment_detail(p_subject_type text,p_subject_key text)
returns jsonb language plpgsql stable security definer set search_path='public','pg_temp' as $$
declare ok boolean; result jsonb;
begin
  select exists(select 1 from public.aml_allowed_users au where au.user_id=auth.uid() and au.enabled) into ok;
  if not ok then return jsonb_build_object('error','NOT_AUTHORIZED'); end if;
  select jsonb_build_object('facts',coalesce(jsonb_agg(jsonb_build_object(
    'field_code',field_code,'value_text',value_text,'value_json',value_json,'evidence_class',evidence_class,'confidence',confidence,
    'source_code',source_code,'source_url',source_url,'evidence_excerpt',evidence_excerpt,'observed_at',observed_at,'last_seen_at',last_seen_at
  ) order by field_code,confidence desc nulls last,last_seen_at desc),'[]'::jsonb)) into result
  from public.aml_fintech_enrichment_fact where subject_type=upper(p_subject_type) and subject_key=p_subject_key;
  return result;
end; $$;
revoke all on function public.obs_fintech_enrichment_detail(text,text) from public,anon;
grant execute on function public.obs_fintech_enrichment_detail(text,text) to authenticated;

create or replace function public.aml_fintech_trigger_enrichment()
returns bigint language plpgsql security definer set search_path='public','vault','net','pg_temp' as $$
declare v_token text; v_request bigint;
begin
  select decrypted_secret into v_token from vault.decrypted_secrets where name='atlas_fintech_cron_token' limit 1;
  if v_token is null then raise exception 'FINTECH_CRON_TOKEN_MISSING'; end if;
  select net.http_post(
    url:='https://ldmtlwzqaqmegedktlxr.supabase.co/functions/v1/atlas-fintech-enrichment',
    body:=jsonb_build_object('limit',8),
    headers:=jsonb_build_object('content-type','application/json','x-atlas-cron-token',v_token),
    timeout_milliseconds:=90000
  ) into v_request;
  return v_request;
end; $$;
revoke all on function public.aml_fintech_trigger_enrichment() from public,anon,authenticated;
grant execute on function public.aml_fintech_trigger_enrichment() to service_role;

do $$
begin
  if exists(select 1 from cron.job where jobname='atlas-fintech-enrichment') then
    perform cron.unschedule((select jobid from cron.job where jobname='atlas-fintech-enrichment' limit 1));
  end if;
  perform cron.schedule('atlas-fintech-enrichment','47 */3 * * *','select public.aml_fintech_trigger_enrichment();');
end $$;
