with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ENT-RUT-76837328-0','B2B','EMPRESAS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.999::numeric,'Betterfly es una plataforma de salud, beneficios y seguros contratada por empresas para sus colaboradores.','Los planes vigentes se contratan por empresa y se tarifican por colaborador; el usuario final es beneficiario, no el cliente contractual principal.','Betterfly publica planes mensuales por colaborador, con precios desde CLP 4.990 + IVA y planes con seguros integrados.','https://betterfly.com/es-cl/planes-y-precios/'),
 ('ENT-RUT-76414639-5','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Jooycar desarrolla plataformas telemáticas y de connected insurance que aseguradoras integran en su core para pricing, prevención y relación con asegurados.','Su cliente económico observable son aseguradoras/carriers de Latinoamérica.','La evidencia pública actual no expone una tarifa principal suficiente para clasificar monetización.','https://jooycar.com/'),
 ('ENT-RUT-76457365-K','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Simplee es corredora/plataforma digital de seguros para Pymes y empresas, con contratación 100% online y API para otros corredores.','La oferta vigente está orientada explícitamente a negocios/Pymes y a corredores que integran su API.','La evidencia pública no permite representar responsablemente la comisión de corretaje con un único código de ingresos.','https://www.simplee.cl/'),
 ('ENT-RUT-59250540-1','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'NICO combina software y asesoría para administrar, contratar y distribuir seguros dentro de empresas.','La plataforma está dirigida a empresas que gestionan seguros propios, de clientes, proveedores y contratistas.','NICO ofrece planes y venta de seguros, pero la evidencia pública no permite identificar una única fuente de ingresos dominante.','https://www.nicoseguros.com/'),
 ('ACTOR-D4F5C86D567A0EB3','B2B','EMPRESAS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.999::numeric,'FRISS provee software/IA de Trust Automation, fraude y risk assessment exclusivamente para aseguradoras P&C.','Sus clientes son compañías de seguros que integran sus soluciones en underwriting, claims e investigaciones.','FRISS comercializa una plataforma de software empresarial; se mantiene SUSCRIPCION_SAAS ya estructurada.','https://www.friss.com/'),
 ('ENT-RUT-76951996-3','B2B','EMPRESAS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.999::numeric,'LISA Insurtech automatiza punta a punta la gestión y liquidación de siniestros mediante IA para compañías de seguros.','La comunicación vigente está dirigida directamente a aseguradoras.','Se mantiene la clasificación SaaS ya estructurada para su plataforma empresarial.','https://www.lisainsurtech.com/'),
 ('ENT-RUT-76503643-7','B2B','EMPRESAS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.999::numeric,'Tutenlabs ofrece módulos de postventa y gestión de siniestros para aseguradoras, incluyendo autoservicio, asignación y automatización de procesos.','La solución se integra a operaciones de compañías/organizaciones de seguros y asistencia.','Se mantiene SUSCRIPCION_SAAS como monetización estructurada de su plataforma B2B.','https://www.tutenlabs.com/postventa-de-siniestros')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_INSURTECH_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,v.revenue_model,v.rev_conf,1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'cohort','INSURTECH_CORE') from vals v returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=v.revenue_model,business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=v.rev_basis,revenue_model_confidence=v.rev_conf,profile_classifier_version='MANUAL_OFFICIAL_INSURTECH_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|BETTERFLY|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-76837328-0','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'Betterfly integra seguros de salud, vida, dental y catastrófico en una plataforma digital para empresas y colaboradores.','COMPANY_OFFICIAL','https://betterfly.com/es-cl/seguros-salud-vida/','Seguros y coberturas integrados en una plataforma, comercializados mediante corredora relacionada.',now(),now(),now()),
('OFFICIAL|JOOYCAR|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-76414639-5','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'Jooycar provee tecnología de connected insurance y telemática que aseguradoras usan para riesgo, pricing, prevención y relación con asegurados.','COMPANY_OFFICIAL','https://jooycar.com/','Driving data and connected-insurance technology for insurers.',now(),now(),now()),
('OFFICIAL|SIMPLEE|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-76457365-K','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'Simplee permite cotizar/contratar seguros digitales para Pymes y ofrece API de seguros para corredores/plataformas.','COMPANY_OFFICIAL','https://www.simplee.cl/','Garantía, Minipyme y RC digital con contratación online y API.',now(),now(),now()),
('OFFICIAL|NICO|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-59250540-1','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'NICO usa software e IA para cotizar, contratar y administrar pólizas y seguros empresariales de forma remota.','COMPANY_OFFICIAL','https://www.nicoseguros.com/','Software y asesoría para gestión/contratación de seguros empresariales.',now(),now(),now()),
('OFFICIAL|FRISS|FIN_INSURTECH|2026-09-09','ENTITY','ACTOR-D4F5C86D567A0EB3','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'FRISS automatiza evaluación de riesgo, fraude, underwriting y claims para aseguradoras P&C.','COMPANY_OFFICIAL','https://www.friss.com/','Trust Automation platform for P&C insurers.',now(),now(),now()),
('OFFICIAL|LISA|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-76951996-3','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'LISA automatiza gestión y liquidación de siniestros mediante IA para aseguradoras.','COMPANY_OFFICIAL','https://www.lisainsurtech.com/','Automatización punta a punta de gestión de siniestros.',now(),now(),now()),
('OFFICIAL|TUTENLABS|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-76503643-7','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'Tutenlabs ofrece plataforma de gestión de siniestros, denuncias, asignación y autoservicio para operaciones aseguradoras.','COMPANY_OFFICIAL','https://www.tutenlabs.com/postventa-de-siniestros','Gestión digital de siniestros y coberturas.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

select public.aml_fintech_refresh_functional_profile();