with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ENT-RUT-77101928-5','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'SumUp provee POS, Tap to Pay, cuenta digital, links de pago y software de gestión a comercios y emprendimientos.','El cliente económico observable es el comercio/negocio que adquiere o arrienda el equipo y paga las comisiones; el consumidor final sólo actúa como pagador.','SumUp cobra comisiones porcentuales por transacción y, en algunos planes, un valor mensual por equipamiento/servicio.','https://www.sumup.com/es-cl/precios/'),
 ('ENT-RUT-76187287-7','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Khipu conecta comercios y plataformas con pagos cuenta a cuenta, pagos automáticos y APIs de Open Finance.','El producto de pagos requiere una cuenta de cobrador/comercio y sus APIs se integran a negocios, desarrolladores y organizaciones.','Khipu publica para pagos instantáneos una tarifa porcentual de 0,6% + IVA sobre el monto recaudado, con descuentos por volumen.','https://www.khipu.com/page/tarifas-instantaneos-argentina'),
 ('ENT-RUT-59226790-K','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Fintoc es infraestructura de pagos para empresas con checkout, pagos recurrentes, transferencias, cuentas empresa y conexiones bancarias.','La oferta vigente está diseñada para empresas que procesan pagos digitales y necesitan integración API/checkout/recaudación.','Fintoc comercializa pagos destacando una comisión por transacción y reducción de costo frente a tarjetas; se mantiene la clasificación ya observada como comisión transaccional.','https://www.fintoc.com/cl/producto/payments/transferencias'),
 ('ENT-RUT-77224915-2','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'tapi es infraestructura regional de pagos y cobros vía una única API para bancos, fintechs, billeteras y otras empresas.','La compañía se define como aliado tecnológico de empresas y permite que compañías incorporen pagos de servicios, cash in/out, recargas y gift cards a sus productos.','La evidencia pública revisada no expone una tarifa principal suficientemente precisa para asignar un único modelo de monetización.','https://tapi.la/')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_PAYMENTS_INFRA_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,v.revenue_model,v.rev_conf,1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'cohort','PAYMENTS_INFRA_III') from vals v returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=v.revenue_model,business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=v.rev_basis,revenue_model_confidence=v.rev_conf,profile_classifier_version='MANUAL_OFFICIAL_PAYMENTS_INFRA_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|SUMUP|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77101928-5','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'SumUp ofrece adquirencia/aceptación de pagos con tarjeta, Tap to Pay, links de pago y POS para comercios.','COMPANY_OFFICIAL','https://www.sumup.com/es-cl/precios/','Comisiones vigentes 2026 para pagos con tarjetas y soluciones de negocio.',now(),now(),now()),
('OFFICIAL|SUMUP|FIN_CARDS|2026-09-09','ENTITY','ENT-RUT-77101928-5','FIN_CARDS','OBSERVED','OFFICIAL_OPEN',1.0,'SumUp acepta pagos con tarjetas y ofrece una tarjeta Mastercard Business asociada a la Cuenta Digital del comercio.','COMPANY_OFFICIAL','https://www.sumup.com/es-cl/cobra-con-tap/','Cuenta Digital y tarjeta Mastercard Business para negocios.',now(),now(),now()),
('OFFICIAL|KHIPU|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76187287-7','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Khipu permite a comercios crear y recibir pagos inmediatos por transferencia bancaria y pagos automáticos.','COMPANY_OFFICIAL','https://www.khipu.com/','Pagos instantáneos y automáticos para comercios.',now(),now(),now()),
('OFFICIAL|KHIPU|FIN_OPEN_FINANCE|2026-09-09','ENTITY','ENT-RUT-76187287-7','FIN_OPEN_FINANCE','OBSERVED','OFFICIAL_OPEN',1.0,'Khipu ofrece APIs Open Finance para datos bancarios/financieros y conectividad multiinstitución.','COMPANY_OFFICIAL','https://www.khipu.com/page/api','Web scraping as a Service & Open Finance mediante API.',now(),now(),now()),
('OFFICIAL|FINTOC|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-59226790-K','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Fintoc ofrece checkout, transferencias, pagos recurrentes y recaudación a empresas mediante API y dashboard.','COMPANY_OFFICIAL','https://www.fintoc.com/cl','Sistema operativo de pagos para escalar negocios.',now(),now(),now()),
('OFFICIAL|FINTOC|FIN_OPEN_FINANCE|2026-09-09','ENTITY','ENT-RUT-59226790-K','FIN_OPEN_FINANCE','OBSERVED','OFFICIAL_OPEN',1.0,'Fintoc mantiene conexiones bancarias y APIs para movimientos, saldos, conciliación e información financiera/tributaria.','COMPANY_OFFICIAL','https://www.fintoc.com/cl/legal/terminos','API para traer información bancaria y tributaria hacia la plataforma del mandante.',now(),now(),now()),
('OFFICIAL|TAPI|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77224915-2','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'tapi permite a empresas integrar pago de servicios, cash in/out, recargas y gift cards mediante una API regional.','COMPANY_OFFICIAL','https://tapi.la/','Red de pagos y cobros regional para empresas.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values
('COMPANY_OFFICIAL|SUMUP|MERCHANTS|2026-09-09','ENTITY','ENT-RUT-77101928-5','MERCHANTS',4000000,'Más de 4 millones de comercios en el mundo usan SumUp','merchants',null,'AT_LEAST','GLOBAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.sumup.com/es-cl/compra-ahora/',now(),'Cifra global declarada por SumUp; no corresponde a Chile solamente.','Más de 4 millones de comercios en el mundo',jsonb_build_object('lower_bound',true,'not_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|SUMUP|COUNTRIES_SERVICE_REACH|2026-09-09','ENTITY','ENT-RUT-77101928-5','COUNTRIES_SERVICE_REACH',36,'Presente en 36 países','countries',null,'EXACT','GLOBAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.sumup.com/es-cl/cobra-con-tap/',now(),'Presencia internacional declarada por SumUp; no implica el mismo portafolio de productos en todos los países.','Presentes en 36 países',jsonb_build_object('semantics','corporate_presence'),now(),now()),
('COMPANY_OFFICIAL|FINTOC|BUSINESS_CLIENTS|2026-09-09','ENTITY','ENT-RUT-59226790-K','BUSINESS_CLIENTS',1200,'Más de 1.200 empresas confían en Fintoc','companies',null,'AT_LEAST','CHILE_MEXICO','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.fintoc.com/cl',now(),'Cifra corporativa declarada en la página Chile; no se interpreta como clientes exclusivamente chilenos.','+1200 empresas confían en nosotros',jsonb_build_object('lower_bound',true,'not_strictly_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|TAPI|COUNTRIES_SERVICE_REACH|2026-09-09','ENTITY','ENT-RUT-77224915-2','COUNTRIES_SERVICE_REACH',5,'API disponible en Argentina, Chile, Colombia, México y Perú','countries',null,'EXACT','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://tapi.la/servicios/',now(),'Cobertura regional de la API de pago de servicios.','Disponible en Argentina, Chile, Colombia, México y Perú',jsonb_build_object('semantics','service_reach'),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();