insert into public.aml_fintech_market_metric_catalog(metric_code,label,dimension,unit_kind,default_unit,default_currency,comparable_scope,higher_means_more_weight,description,sort_order)
values('TRANSACTIONS_QUARTERLY_COUNT','Operaciones trimestrales declaradas','BUSINESS_ACTIVITY','COUNT','transactions',null,'SAME_METRIC',true,'Número de operaciones/transacciones declarado para un trimestre o ventana trimestral. No equivale a volumen monetario.',25)
on conflict(metric_code) do update set label=excluded.label,dimension=excluded.dimension,unit_kind=excluded.unit_kind,default_unit=excluded.default_unit,default_currency=excluded.default_currency,comparable_scope=excluded.comparable_scope,higher_means_more_weight=excluded.higher_means_more_weight,description=excluded.description,sort_order=excluded.sort_order;

with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url,psav_basis,psav_conf) as (
 values
 ('ENT-RUT-76905736-6','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Ripio mantiene una app para usuarios y una oferta Ripio Business/Crypto as a Service para instituciones, bancos, fintechs y empresas.','La oferta vigente atiende simultáneamente personas y organizaciones mediante productos diferenciados.','Ripio publica comisión de 0,5% para compra/venta de criptomonedas, con excepciones específicas como BTC.','https://www.ripio.com/es/cl','Evidencia funcional abierta confirma compra/venta cripto, infraestructura fiat-cripto, trading/custodia y servicios para usuarios y empresas en Chile/LATAM.',0.999::numeric),
 ('ENT-RUT-76590133-2','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.99::numeric,0.99::numeric,0.999::numeric,'CryptoMarket/NotBank admite usuarios personas y cuentas institucionales para personas jurídicas; la plataforma combina exchange, wallet y servicios financieros cripto.','La documentación de cumplimiento contempla clientes persona natural y persona jurídica/cuenta institucional.','CryptoMarket publica tarifas por transacción/servicio, incluyendo Simple 1,5% y comisiones de trading/retiro según producto.','https://www.cryptomkt.com/es-cl/legal','Evidencia funcional y legal del Grupo CryptoMarket confirma compra/venta, wallet/custodia, conversión fiat-cripto y servicios cripto; el vehículo chileno CryptoMKT SpA procesa CLP y Dysopsis Limited Agencia en Chile presta/solicita servicios regulados de custodia/intermediación/SAT.',0.999::numeric),
 ('ENT-RUT-76949499-5','B2C','PERSONAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'SatoshiTango ofrece en Chile compra/venta, billetera y rendimientos cripto orientados principalmente a usuarios personas.','La comunicación, onboarding y oferta observada se dirige principalmente a personas/inversionistas individuales.','Los términos y páginas de producto publican comisión de 1% para compraventa fiat-cripto y 0,5% para compraventa cripto-cripto.','https://www.satoshitango.com/cl','La oferta Chile confirma compra/venta con moneda local, wallet, transferencias/retiros por redes y stablecoins; funcionalmente corresponde a servicios de activos virtuales.',0.999::numeric),
 ('ENT-RUT-77091316-0','B2B2C','AMBOS',null,0.999::numeric,0.999::numeric,null,'Nizzo declara soluciones para usuarios particulares, PYMES, startups y empresas, combinando cambio fiat-cripto y pagos internacionales.','Los términos aceptan personas y entidades legales como clientes de la plataforma.',null,'https://www.nizzocap.com/es','Términos vigentes de Nizzo Capital SpA confirman compra, venta e intercambio de activos digitales y pagos/transferencias nacionales e internacionales.',0.999::numeric)
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_DIGITAL_ASSETS_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,coalesce(v.revenue_model,e.revenue_model),coalesce(v.rev_conf,e.revenue_model_confidence),1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'psav_basis',v.psav_basis,'manual_validation',true,'cohort','DIGITAL_ASSETS')
 from vals v join public.aml_fintech_entity e using(fintech_id)
 returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=coalesce(v.revenue_model,e.revenue_model),business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=case when v.revenue_model is not null then v.rev_basis else e.revenue_model_basis end,revenue_model_confidence=case when v.revenue_model is not null then v.rev_conf else e.revenue_model_confidence end,profile_classifier_version='MANUAL_OFFICIAL_DIGITAL_ASSETS_2026_09_09',profile_refreshed_at=now(),psav_status='CONFIRMED',psav_basis=v.psav_basis,psav_confidence=v.psav_conf,psav_refreshed_at=now(),refreshed_at=now()
from vals v
where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

update public.aml_fintech_entity set psav_status='CONFIRMED',psav_basis='El aviso oficial de cierre 2026 confirma activos de clientes bajo custodia y restitución de activos, suficiente para acreditar función PSAV/custodia; no implica operación comercial normal vigente.',psav_confidence=0.999,psav_refreshed_at=now(),refreshed_at=now() where fintech_id='ENT-RUT-76801011-0';
update public.aml_fintech_entity set psav_status='EXPOSURE',psav_basis='Octopus Digital Distribution SpA figura públicamente como SO UAF y su marca ChileBitcoin mantiene presencia vinculada a Bitcoin/activos digitales; la web actual sólo muestra precio BTC/CLP y no permite confirmar por sí sola una función PSAV transaccional vigente.',psav_confidence=0.75,psav_refreshed_at=now(),refreshed_at=now() where fintech_id='ENT-RUT-76626762-9';

insert into public.aml_fintech_legal_vehicle(fintech_id,rut,atlas_entity_id,legal_name,role_code,is_primary,regulator,registry,source_code,source_url,evidence_basis,confidence,first_seen_at,last_seen_at,metadata)
values('ENT-RUT-76590133-2','59248990-2','ENT-RUT-59248990-2','DYSOPSIS LIMITED AGENCIA EN CHILE','REGULATED_SERVICE_PROVIDER',false,'CMF','LEY_FINTEC_NCG502_APPLICATION','COMPANY_OFFICIAL','https://www.notbank.com/es-cl/legal','Los términos vigentes de NotBank/Grupo CryptoMarket señalan que Dysopsis Limited Agencia en Chile es la entidad constituida bajo NCG 502 que solicitó registro/autorización para custodia, intermediación y sistema alternativo de transacción, y que presta el servicio de custodia a clientes en Chile.',0.999,now(),now(),jsonb_build_object('group','CryptoMarket/NotBank','status_note','solicitud en evaluación según términos vigentes','service_split','CryptoMKT SpA procesa/recauda CLP; Dysopsis presta custodia y solicita servicios Ley Fintec'))
on conflict(fintech_id,rut,role_code) do update set atlas_entity_id=excluded.atlas_entity_id,legal_name=excluded.legal_name,is_primary=false,regulator=excluded.regulator,registry=excluded.registry,source_code=excluded.source_code,source_url=excluded.source_url,evidence_basis=excluded.evidence_basis,confidence=excluded.confidence,last_seen_at=now(),metadata=excluded.metadata;

insert into public.aml_fintech_subject_relationship(subject_type,subject_key,relation_type,target_rut,target_atlas_entity_id,target_label,valid_from,source_code,source_url,evidence_basis,confidence,active,first_seen_at,last_seen_at,metadata)
select 'ENTITY','ENT-RUT-76590133-2','OPERATED_BY','59248990-2','ENT-RUT-59248990-2','DYSOPSIS LIMITED AGENCIA EN CHILE','2025-01-17','COMPANY_OFFICIAL','https://www.notbank.com/es-cl/legal','Para servicios de custodia y servicios Ley Fintec en Chile, los términos del Grupo CryptoMarket/NotBank identifican a Dysopsis Limited Agencia en Chile como entidad prestadora/solicitante; CryptoMKT SpA mantiene rol de procesamiento y recaudo de CLP.',0.999,true,now(),now(),jsonb_build_object('scope','regulated_fintech_services','not_identity_merge',true)
where not exists(select 1 from public.aml_fintech_subject_relationship r where r.subject_type='ENTITY' and r.subject_key='ENT-RUT-76590133-2' and r.relation_type='OPERATED_BY' and regexp_replace(coalesce(r.target_rut,''),'[^0-9K]','','g')='592489902' and r.active);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|RIPIO|VA_FIAT_EXCHANGE|2026-09-09','ENTITY','ENT-RUT-76905736-6','VA_FIAT_EXCHANGE','OBSERVED','OFFICIAL_OPEN',1.0,'Ripio permite depositar moneda local y comprar/vender criptoactivos.','COMPANY_OFFICIAL','https://www.ripio.com/es/cl','Compra, vende y gestiona tus cripto.',now(),now(),now()),
('OFFICIAL|RIPIO|VA_CUSTODY_ADMIN|2026-09-09','ENTITY','ENT-RUT-76905736-6','VA_CUSTODY_ADMIN','OBSERVED','OFFICIAL_OPEN',1.0,'Ripio App y Ripio Business declaran gestión/custodia de cripto e infraestructura institucional.','COMPANY_OFFICIAL','https://www.ripio.com/es/institucional','Trading y custodia cripto; custodia institucional.',now(),now(),now()),
('OFFICIAL|RIPIO|VA_TRANSFER|2026-09-09','ENTITY','ENT-RUT-76905736-6','VA_TRANSFER','OBSERVED','OFFICIAL_OPEN',1.0,'Ripio y su CaaS permiten enviar y recibir criptomonedas.','COMPANY_OFFICIAL','https://www.ripio.com/es/business/b2b','Comprar, vender, enviar y recibir criptomonedas.',now(),now(),now()),
('OFFICIAL|RIPIO|VA_STABLECOIN_SERVICES|2026-09-09','ENTITY','ENT-RUT-76905736-6','VA_STABLECOIN_SERVICES','OBSERVED','OFFICIAL_OPEN',1.0,'Ripio ofrece stablecoins locales y dólares cripto como parte de su infraestructura.','COMPANY_OFFICIAL','https://www.ripio.com/es','Stablecoins locales e infraestructura on-chain.',now(),now(),now()),
('OFFICIAL|RIPIO|VA_ON_OFF_RAMP|2026-09-09','ENTITY','ENT-RUT-76905736-6','VA_ON_OFF_RAMP','OBSERVED','OFFICIAL_OPEN',1.0,'Ripio ofrece rampas instantáneas fiat-a-cripto conectadas a rieles bancarios locales.','COMPANY_OFFICIAL','https://www.ripio.com/es','Rampas instantáneas fiat-a-cripto.',now(),now(),now()),
('OFFICIAL|RIPIO|FIN_CARDS|2026-09-09','ENTITY','ENT-RUT-76905736-6','FIN_CARDS','OBSERVED','OFFICIAL_OPEN',0.99,'Ripio publica Crypto Card asociada a su ecosistema.','COMPANY_OFFICIAL','https://www.ripio.com/es/criptomonedas/ripio-coin','Crypto Card y pagos con pesos o criptomonedas.',now(),now(),now()),
('OFFICIAL|CRYPTOMKT|VA_FIAT_EXCHANGE|2026-09-09','ENTITY','ENT-RUT-76590133-2','VA_FIAT_EXCHANGE','OBSERVED','OFFICIAL_OPEN',1.0,'CryptoMarket permite comprar/vender cripto con pesos chilenos y convertir a moneda local.','COMPANY_OFFICIAL','https://www.cryptomkt.com/es-cl/','Compra y vende con pesos; exchange cripto en Chile.',now(),now(),now()),
('OFFICIAL|CRYPTOMKT|VA_VA_EXCHANGE|2026-09-09','ENTITY','ENT-RUT-76590133-2','VA_VA_EXCHANGE','OBSERVED','OFFICIAL_OPEN',1.0,'Las tarifas vigentes contemplan operaciones Crypto-Crypto y trading spot.','COMPANY_OFFICIAL','https://www.cryptomkt.com/es-cl/tarifas','Tarifas Crypto-Crypto y spot.',now(),now(),now()),
('OFFICIAL|CRYPTOMKT|VA_CUSTODY_ADMIN|2026-09-09','ENTITY','ENT-RUT-76590133-2','VA_CUSTODY_ADMIN','OBSERVED','OFFICIAL_OPEN',1.0,'Los términos vigentes indican que la custodia a clientes en Chile es prestada por Dysopsis Limited Agencia en Chile dentro del Grupo CryptoMarket.','COMPANY_OFFICIAL','https://www.notbank.com/es-cl/legal','Servicio de custodia prestado por Dysopsis Limited Agencia en Chile.',now(),now(),now()),
('OFFICIAL|CRYPTOMKT|VA_TRANSFER|2026-09-09','ENTITY','ENT-RUT-76590133-2','VA_TRANSFER','OBSERVED','OFFICIAL_OPEN',1.0,'La plataforma contempla depósitos, retiros y wallet de criptomonedas.','COMPANY_OFFICIAL','https://www.cryptomkt.com/es-cl/','Billetera y depósitos/retiros cripto.',now(),now(),now()),
('OFFICIAL|CRYPTOMKT|VA_ON_OFF_RAMP|2026-09-09','ENTITY','ENT-RUT-76590133-2','VA_ON_OFF_RAMP','OBSERVED','OFFICIAL_OPEN',1.0,'CryptoMKT SpA procesa depósitos/retiros en CLP para la plataforma y permite conversión fiat-cripto.','COMPANY_OFFICIAL','https://www.cryptomkt.com/es-cl/legal','CryptoMarket Chile procesa/recauda CLP; compra/venta cripto con moneda local.',now(),now(),now()),
('OFFICIAL|SATOSHITANGO|VA_FIAT_EXCHANGE|2026-09-09','ENTITY','ENT-RUT-76949499-5','VA_FIAT_EXCHANGE','OBSERVED','OFFICIAL_OPEN',1.0,'SatoshiTango Chile permite cambiar pesos por cripto y comprar/vender más de 18 activos.','COMPANY_OFFICIAL','https://www.satoshitango.com/cl','Compra y vende criptomonedas en Chile.',now(),now(),now()),
('OFFICIAL|SATOSHITANGO|VA_VA_EXCHANGE|2026-09-09','ENTITY','ENT-RUT-76949499-5','VA_VA_EXCHANGE','OBSERVED','OFFICIAL_OPEN',1.0,'La estructura de comisiones publica compraventa cripto-cripto.','COMPANY_OFFICIAL','https://www.satoshitango.com/criptomonedas','Comisión por compraventa con cripto 0,5%.',now(),now(),now()),
('OFFICIAL|SATOSHITANGO|VA_CUSTODY_ADMIN|2026-09-09','ENTITY','ENT-RUT-76949499-5','VA_CUSTODY_ADMIN','OBSERVED','OFFICIAL_OPEN',0.99,'La plataforma mantiene cartera/cuenta cripto y declara resguardo de los ahorros de usuarios.','COMPANY_OFFICIAL','https://www.satoshitango.com/cl/billetera-cripto','Cartera cripto y resguardo de activos.',now(),now(),now()),
('OFFICIAL|SATOSHITANGO|VA_TRANSFER|2026-09-09','ENTITY','ENT-RUT-76949499-5','VA_TRANSFER','OBSERVED','OFFICIAL_OPEN',0.99,'La plataforma admite depósitos y retiros por distintas redes y envío de activos.','COMPANY_OFFICIAL','https://www.satoshitango.com/cl/criptomonedas/usdt/comprar','Retiro de USDT por varias redes.',now(),now(),now()),
('OFFICIAL|SATOSHITANGO|VA_STABLECOIN_SERVICES|2026-09-09','ENTITY','ENT-RUT-76949499-5','VA_STABLECOIN_SERVICES','OBSERVED','OFFICIAL_OPEN',1.0,'SatoshiTango ofrece USDT, USDC y DAI y productos de dólar cripto.','COMPANY_OFFICIAL','https://www.satoshitango.com/cl/dolar-cripto','Dólar cripto y stablecoins.',now(),now(),now()),
('OFFICIAL|NIZZO|VA_FIAT_EXCHANGE|2026-09-09','ENTITY','ENT-RUT-77091316-0','VA_FIAT_EXCHANGE','OBSERVED','OFFICIAL_OPEN',1.0,'Nizzo ofrece compra, venta, intercambio y conversión de moneda fiat por cripto.','COMPANY_OFFICIAL','https://www.nizzocap.com/es/terms-and-conditions','Compra, venta y conversión de activos digitales.',now(),now(),now()),
('OFFICIAL|NIZZO|VA_TRANSFER|2026-09-09','ENTITY','ENT-RUT-77091316-0','VA_TRANSFER','OBSERVED','OFFICIAL_OPEN',1.0,'Nizzo permite transferencias/retiros y vincular billetera Web3.','COMPANY_OFFICIAL','https://www.nizzocap.com/es','Retiros a billetera Web3.',now(),now(),now()),
('OFFICIAL|NIZZO|VA_ON_OFF_RAMP|2026-09-09','ENTITY','ENT-RUT-77091316-0','VA_ON_OFF_RAMP','OBSERVED','OFFICIAL_OPEN',1.0,'Nizzo intercambia fiat por cripto y ejecuta transferencias hacia cuentas/billeteras registradas.','COMPANY_OFFICIAL','https://www.nizzocap.com/es/terms-and-conditions','Intercambio fiat-cripto y transferencias/retiros.',now(),now(),now()),
('OFFICIAL|NIZZO|FIN_REMITTANCE_FX|2026-09-09','ENTITY','ENT-RUT-77091316-0','FIN_REMITTANCE_FX','OBSERVED','OFFICIAL_OPEN',1.0,'Nizzo ofrece pagos internacionales en moneda local.','COMPANY_OFFICIAL','https://www.nizzocap.com/es','Pagos internacionales en moneda local.',now(),now(),now()),
('OFFICIAL|NIZZO|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77091316-0','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Los términos de Nizzo contemplan instrucciones de pago nacionales e internacionales.','COMPANY_OFFICIAL','https://www.nizzocap.com/es/terms-and-conditions','Instrucciones de pago nacionales e internacionales.',now(),now(),now()),
('OFFICIAL|ORIONX|VA_CUSTODY_ADMIN|2026-09-09','ENTITY','ENT-RUT-76801011-0','VA_CUSTODY_ADMIN','OBSERVED','OFFICIAL_OPEN',1.0,'El aviso oficial de cierre confirma activos de clientes en custodia y un proceso de restitución.','COMPANY_OFFICIAL','https://orionx.com/status','Activos en custodia y restitución de activos a clientes.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values
('COMPANY_OFFICIAL|RIPIO|USERS|2026-09-09','ENTITY','ENT-RUT-76905736-6','USERS',28000000,'Más de 28 millones de usuarios','users',null,'AT_LEAST','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.ripio.com/es',now(),'Cifra regional/global declarada por Ripio; no corresponde sólo a Chile.','Usuarios +28M',jsonb_build_object('lower_bound',true,'scope','Ripio/LATAM-global','not_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|RIPIO|AUM|2026-09-09','ENTITY','ENT-RUT-76905736-6','AUM_AUC_USD',300000000,'US$300M en activos bajo gestión','USD','USD','APPROX','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.ripio.com/es',now(),'AUM declarado por Ripio en su sitio institucional; alcance regional/global, no sólo Chile.','Activos bajo gestión US 300M',jsonb_build_object('scope','Ripio/LATAM-global','not_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|CRYPTOMKT|USERS|2026-09-09','ENTITY','ENT-RUT-76590133-2','USERS',650000,'Más de 650.000 usuarios registrados','users',null,'AT_LEAST','LATAM','DECLARADO',0.99,'COMPANY_OFFICIAL','https://www.cryptomkt.com/api/en/referrals',now(),'Cifra declarada por CryptoMarket para su plataforma regional, no sólo Chile.','More than six hundred fifty thousand users registered',jsonb_build_object('lower_bound',true,'scope','regional','not_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|SATOSHITANGO|USERS|2026-09-09','ENTITY','ENT-RUT-76949499-5','USERS',800000,'Más de 800.000 personas','users',null,'AT_LEAST','REGIONAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.satoshitango.com/cl',now(),'SatoshiTango declara resguardar/potenciar ahorros de más de 800.000 personas; cifra regional, no Chile-only.','más de 800.000 personas',jsonb_build_object('lower_bound',true,'not_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|SATOSHITANGO|COUNTRIES|2026-09-09','ENTITY','ENT-RUT-76949499-5','COUNTRIES_OPERATING',3,'Opera en 3 países','countries',null,'EXACT','REGIONAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.satoshitango.com/cl',now(),'Presencia/operación declarada por la compañía.','Estamos en 3 países',jsonb_build_object('scope','regional'),now(),now()),
('COMPANY_OFFICIAL|SATOSHITANGO|TX_QUARTERLY|2026-09-09','ENTITY','ENT-RUT-76949499-5','TRANSACTIONS_QUARTERLY_COUNT',936000,'Más de 936.000 operaciones trimestrales','transactions',null,'AT_LEAST','REGIONAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.satoshitango.com/cl',now(),'Conteo de operaciones trimestrales declarado por la compañía; no es volumen monetario.','Operaciones trimestrales +936.000',jsonb_build_object('lower_bound',true,'period_semantics','quarterly','not_monetary_volume',true),now(),now()),
('COMPANY_OFFICIAL|NIZZO|USERS|2026-09-09','ENTITY','ENT-RUT-77091316-0','USERS',500,'Más de 500 personas se unieron','users',null,'AT_LEAST','REGIONAL','DECLARADO',0.90,'COMPANY_OFFICIAL','https://www.nizzocap.com/es',now(),'Cifra mínima declarada en sitio oficial; se mantiene con confianza menor por presentación poco precisa del contador.','+500 personas se unieron',jsonb_build_object('lower_bound',true,'display_quality','limited'),now(),now()),
('COMPANY_OFFICIAL|NIZZO|COUNTRIES|2026-09-09','ENTITY','ENT-RUT-77091316-0','COUNTRIES_OPERATING',3,'Presencia física en 3 países de Latinoamérica','countries',null,'EXACT','LATAM','DECLARADO',0.99,'COMPANY_OFFICIAL','https://www.nizzocap.com/es',now(),'Nizzo declara presencia física en tres países de Latinoamérica y servicio online global.','presencia en 3 países',jsonb_build_object('scope','physical_presence'),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();