with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
  values
  ('ENT-RUT-99546900-6','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Sitio oficial Klap ofrece POS, e-commerce, link de pago y servicios de adquirencia a comercios; tarifas 2026 están expresadas para comercios afiliados.','La oferta y contratación se dirige a comercios/personas con actividad económica que reciben pagos.','Tarifas oficiales 2026 incluyen comisión fija + porcentaje por transacción y tarifas de servicio POS.','https://www.klap.cl/home-comercios/tiendas-locales-comerciales'),
  ('ENT-RUT-77638982-K','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Koywe Chile se presenta como plataforma de tesorería internacional e infraestructura de pagos para empresas, importadores/exportadores, fintechs, plataformas y e-commerce.','La oferta Chile exige KYB/RUT de empresa y describe casos de uso corporativos: proveedores, cobros internacionales y tesorería.','Información legal oficial describe remuneración porcentual variable y comisiones por transacción; rampa y OTC cobran porcentajes sobre operación.','https://www.koywe.com/es/countries/cl'),
  ('ENT-RUT-76415528-9','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Buda.com mantiene cuentas personales y una Cuenta Empresa separada, con compra/venta de cripto, pagos internacionales, stablecoins y API/OTC.','La plataforma sirve tanto a personas naturales como a empresas mediante productos diferenciados.','Modelo de ingreso validado previamente por comisiones de operación/transacción publicadas por Buda.com.','https://www.buda.com/productos/cuenta-empresa'),
  ('ENT-RUT-76594721-9','B2B2C','AMBOS',null,0.999::numeric,0.999::numeric,null,'Creditú combina originación digital de créditos hipotecarios/pie para personas con servicios de financiamiento para inmobiliarias y soluciones para inversionistas institucionales.','La oferta vigente atiende familias/personas, inmobiliarias e inversionistas institucionales.',null,'https://creditu.com/cl/real-estate-cl/')
), logged as (
  insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
  select v.fintech_id,'MANUAL_OFFICIAL_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,coalesce(v.revenue_model,e.revenue_model),coalesce(v.rev_conf,e.revenue_model_confidence),1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true)
  from vals v join public.aml_fintech_entity e using(fintech_id)
  returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=coalesce(v.revenue_model,e.revenue_model),business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=case when v.revenue_model is not null then v.rev_basis else e.revenue_model_basis end,revenue_model_confidence=case when v.revenue_model is not null then v.rev_conf else e.revenue_model_confidence end,profile_classifier_version='MANUAL_OFFICIAL_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at) values
('COMPANY_OFFICIAL|KLAP|MERCHANTS|2026-09-09','ENTITY','ENT-RUT-99546900-6','MERCHANTS',61000,'Más de 61.000 comercios en todo el país','merchants',null,'AT_LEAST','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.klap.cl/home-comercios/tiendas-locales-comerciales',now(),'Klap declara más de 61.000 comercios en todo Chile. Se almacena como piso observable, no como cifra exacta.','más de 61.000 comercios en todo el país',jsonb_build_object('lower_bound',true,'scope','Chile','as_displayed','más de 61.000'),now(),now()),
('COMPANY_OFFICIAL|CREDITU|ORIGINATED_VOLUME_USD|2026-09-09','ENTITY','ENT-RUT-76594721-9','ORIGINATED_VOLUME_USD',900000000,'USD 900M en créditos hipotecarios otorgados','USD','USD','APPROX','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://creditu.com/cl/',now(),'Monto acumulado declarado en la portada oficial de Creditú. No se interpreta como volumen anual.','USD 900M en créditos hipotecarios otorgados',jsonb_build_object('scope','cumulative_declared','product','mortgage_credit'),now(),now()),
('COMPANY_OFFICIAL|CREDITU|CLIENTS|2026-09-09','ENTITY','ENT-RUT-76594721-9','CLIENTS',16000,'Más de 16.000 familias con hogar gracias a Creditú','clients',null,'AT_LEAST','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://creditu.com/cl/',now(),'Creditú declara más de 16.000 familias. Se usa CLIENTS con semántica explícita de familias y como piso observable.','+16.000 familias con hogar gracias a Creditú',jsonb_build_object('lower_bound',true,'client_semantics','families','scope','Chile'),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();