insert into public.aml_fintech_market_metric_catalog(metric_code,label,dimension,unit_kind,default_unit,default_currency,comparable_scope,higher_means_more_weight,description,sort_order)
values('TRANSACTIONS_ANNUAL_COUNT','Operaciones anuales declaradas','BUSINESS_ACTIVITY','COUNT','transactions',null,'SAME_METRIC',true,'Número de operaciones/transacciones declarado para una ventana anual. No equivale a volumen monetario.',24)
on conflict(metric_code) do update set label=excluded.label,dimension=excluded.dimension,unit_kind=excluded.unit_kind,default_unit=excluded.default_unit,default_currency=excluded.default_currency,comparable_scope=excluded.comparable_scope,higher_means_more_weight=excluded.higher_means_more_weight,description=excluded.description,sort_order=excluded.sort_order;

with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ENT-RUT-76917781-7','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Flow es una plataforma/pasarela de pagos y recaudación para comercios y negocios, con API, botón de pago, POS, pagos recurrentes y múltiples medios de pago.','Flow cobra el servicio a quien recibe el dinero y ofrece condiciones especiales para empresas/comercios según volumen.','Las tarifas vigentes cobran una tasa por transacción al comercio/receptor, con tasas diferenciadas por medio de pago y plazo de abono.','https://web.flow.cl/es-cl/tarifas/'),
 ('ENT-RUT-78008316-6','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Hpay centraliza medios de pago online para negocios y emprendimientos mediante app, links de pago y cobros digitales.','La comunicación vigente está dirigida explícitamente a negocios y emprendimientos que necesitan cobrar y organizar sus ventas.','Hpay publica una comisión de 2,0% + IVA por transacción para los medios de pago observados.','https://hpay.cl/tarifas'),
 ('ENT-RUT-76974041-4','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Vita Wallet combina billetera/remesas internacionales para personas con cuentas empresa, pagos a proveedores, nómina, API, enlaces de pago y operaciones cripto.','Los términos y productos vigentes admiten personas naturales y jurídicas y existe una oferta empresarial específica.','Vita cobra comisiones por operación, normalmente integradas en la tasa de cambio, y declara ausencia de suscripción o mensualidad.','https://vitawallet.io/limites-y-comisiones/'),
 ('ENT-RUT-76945003-3','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'UPago es una plataforma de pagos, cobranzas y aseguramiento de ingresos para empresas, con recaudación, cuentas vencidas y automatización de pagos.','La oferta vigente se dirige explícitamente a empresas que buscan automatizar pagos, cobros, facturas y recaudación.','La evidencia pública revisada describe el servicio y su automatización, pero no permite asignar de forma responsable un único modelo de monetización.','https://www.upago.cl/es/'),
 ('ENT-RUT-59121440-3','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Mercado Pago es un ecosistema multivehículo que ofrece cuenta digital y tarjeta para personas y soluciones de cobro, Point, crédito y pagos para comercios.','La oferta Chile observada atiende simultáneamente usuarios personas y comercios/negocios mediante productos diferenciados.','Los productos de cobro Point y sellers cobran comisiones porcentuales sobre ventas; se registra comisión transaccional como mecanismo observable principal del negocio de pagos, sin representar toda la economía del grupo.','https://www.mercadopago.cl/herramientas-para-vender/lectores-point'),
 ('ENT-RUT-76901962-6','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Retorna combina remesas digitales para personas con una plataforma B2B/API para pagos masivos, remesas, FX y on/off-ramp con stablecoins.','La oferta actual incluye usuarios personas y empresas que integran pagos/remesas mediante API o archivos masivos.','Retorna informa costos/comisiones por operación; para dólares digitales cobra una comisión de adquisición/conversión comunicada antes de confirmar la operación.','https://www.retorna.app/es/terminos-y-condiciones/billetera-en-dolares-digitales')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_PAYMENTS_II_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,v.revenue_model,v.rev_conf,1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'cohort','PAYMENTS_REMITTANCES_II') from vals v returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=v.revenue_model,business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=v.rev_basis,revenue_model_confidence=v.rev_conf,profile_classifier_version='MANUAL_OFFICIAL_PAYMENTS_II_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|FLOW|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76917781-7','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Flow procesa y recauda pagos por tarjetas, transferencias bancarias, billeteras digitales, efectivo, POS, links y API.','COMPANY_OFFICIAL','https://web.flow.cl/es-cl/tarifas/','Comisiones y medios de pago vigentes para comercios.',now(),now(),now()),
('OFFICIAL|HPAY|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-78008316-6','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Hpay centraliza pagos desde apps, transferencias y tarjetas para negocios y permite links de pago.','COMPANY_OFFICIAL','https://hpay.cl/tarifas','Comisión 2,0% + IVA por transacción.',now(),now(),now()),
('OFFICIAL|VITA|FIN_REMITTANCE_FX|2026-09-09','ENTITY','ENT-RUT-76974041-4','FIN_REMITTANCE_FX','OBSERVED','OFFICIAL_OPEN',1.0,'Vita Wallet permite transferencias internacionales desde Chile y pagos empresariales a múltiples destinos con conversión de moneda.','COMPANY_OFFICIAL','https://vitawallet.io/cl/','Transferencias internacionales y pagos a más de 35 destinos.',now(),now(),now()),
('OFFICIAL|VITA|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76974041-4','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Vita Business ofrece pagos a proveedores, nómina, enlaces de pago e integraciones API.','COMPANY_OFFICIAL','https://vitawallet.io/empresas/conoce-como-usar-el-menu-principal-de-tu-cuenta-empresa/','Enlaces de pago, pagos masivos e integraciones para empresas.',now(),now(),now()),
('OFFICIAL|VITA|VA_FIAT_EXCHANGE|2026-09-09','ENTITY','ENT-RUT-76974041-4','VA_FIAT_EXCHANGE','OBSERVED','OFFICIAL_OPEN',1.0,'Vita Wallet permite comprar y vender BTC, USDC y USDT y convertir entre CLP, USD y activos digitales.','COMPANY_OFFICIAL','https://vitawallet.io/limites-y-comisiones/','Intercambios BTC, USDC y USDT; comisiones y límites Chile.',now(),now(),now()),
('OFFICIAL|VITA|VA_TRANSFER|2026-09-09','ENTITY','ENT-RUT-76974041-4','VA_TRANSFER','OBSERVED','OFFICIAL_OPEN',1.0,'Vita Wallet permite enviar y recibir activos digitales entre cuentas y hacia/desde wallets externas.','COMPANY_OFFICIAL','https://vitawallet.io/cl/','Envía y recibe cripto y pesos chilenos; wallets externas.',now(),now(),now()),
('OFFICIAL|VITA|VA_HOSTED_WALLET|2026-09-09','ENTITY','ENT-RUT-76974041-4','VA_HOSTED_WALLET','OBSERVED','OFFICIAL_OPEN',0.99,'Vita Wallet mantiene saldos/billetera digital y permite recargas, retiros e intercambios dentro de la plataforma.','COMPANY_OFFICIAL','https://vitawallet.io/limites-y-comisiones/','Billetera digital con recargas, retiros e intercambios.',now(),now(),now()),
('OFFICIAL|UPAGO|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76945003-3','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'UPago automatiza recaudación, pagos y cobros de empresas y gestiona transacciones en línea.','COMPANY_OFFICIAL','https://www.upago.cl/es/','Plataforma de pagos y cobranzas online para empresas.',now(),now(),now()),
('OFFICIAL|MERCADOPAGO|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-59121440-3','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Mercado Pago ofrece Point, cobros con tarjeta, links/QR y cuenta digital; la estructura jurídica se mantiene separada por vehículos.','COMPANY_OFFICIAL','https://www.mercadopago.cl/herramientas-para-vender/lectores-point','Cobros con Point y comisiones según volumen de ventas.',now(),now(),now()),
('OFFICIAL|MERCADOPAGO|FIN_CARDS|2026-09-09','ENTITY','ENT-RUT-59121440-3','FIN_CARDS','OBSERVED','OFFICIAL_OPEN',1.0,'Mercado Pago ofrece tarjeta Mastercard y aceptación de tarjetas a través de Point; existe además vehículo emisor prepago relacionado.','COMPANY_OFFICIAL','https://www.mercadopago.cl/herramientas-para-vender/lectores-point','Cuenta digital, tarjeta y aceptación de débito/crédito/prepago.',now(),now(),now()),
('OFFICIAL|MERCADOPAGO|FIN_LENDING|2026-09-09','ENTITY','ENT-RUT-59121440-3','FIN_LENDING','OBSERVED','OFFICIAL_OPEN',0.99,'Mercado Pago ofrece créditos en línea para potenciar negocios; el grupo cuenta con un vehículo de lending separado ya modelado.','COMPANY_OFFICIAL','https://www.mercadopago.cl/herramientas-para-vender/lectores-point','Crédito para potenciar tu negocio.',now(),now(),now()),
('OFFICIAL|RETORNA|FIN_REMITTANCE_FX|2026-09-09','ENTITY','ENT-RUT-76901962-6','FIN_REMITTANCE_FX','OBSERVED','OFFICIAL_OPEN',1.0,'Retorna presta remesas y transferencias internacionales desde Chile y otros países con liquidación local.','COMPANY_OFFICIAL','https://www.retorna.app/es/envia-dinero-con-retorna','Envíos internacionales y mejor tipo de cambio.',now(),now(),now()),
('OFFICIAL|RETORNA|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76901962-6','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'La plataforma B2B de Retorna procesa pagos masivos y pagos internacionales vía API o archivos.','COMPANY_OFFICIAL','https://retorna.app/es/plataforma','Más de 2 millones de pagos al año y pagos masivos/API.',now(),now(),now()),
('OFFICIAL|RETORNA|VA_FIAT_EXCHANGE|2026-09-09','ENTITY','ENT-RUT-76901962-6','VA_FIAT_EXCHANGE','OBSERVED','OFFICIAL_OPEN',1.0,'Los términos Retorna contemplan adquisición, venta y liquidación de activos digitales por dinero fiat.','COMPANY_OFFICIAL','https://www.retorna.app/es/terminos-y-condiciones/terminos-y-condiciones-retorna','Adquisición, venta y liquidación de activos digitales por fiat.',now(),now(),now()),
('OFFICIAL|RETORNA|VA_CUSTODY_ADMIN|2026-09-09','ENTITY','ENT-RUT-76901962-6','VA_CUSTODY_ADMIN','OBSERVED','OFFICIAL_OPEN',1.0,'Los términos vigentes incluyen expresamente custodia de activos digitales como parte del servicio.','COMPANY_OFFICIAL','https://www.retorna.app/es/terminos-y-condiciones/terminos-y-condiciones-retorna','Custodia de activos digitales.',now(),now(),now()),
('OFFICIAL|RETORNA|VA_TRANSFER|2026-09-09','ENTITY','ENT-RUT-76901962-6','VA_TRANSFER','OBSERVED','OFFICIAL_OPEN',1.0,'La billetera de dólares digitales permite transferir a otro usuario y retirar USDC/USDT hacia billeteras externas.','COMPANY_OFFICIAL','https://www.retorna.app/es/terminos-y-condiciones/billetera-en-dolares-digitales','Transferencia a otro Retorner o billetera externa en USDC/USDT.',now(),now(),now()),
('OFFICIAL|RETORNA|VA_ON_OFF_RAMP|2026-09-09','ENTITY','ENT-RUT-76901962-6','VA_ON_OFF_RAMP','OBSERVED','OFFICIAL_OPEN',1.0,'Retorna ofrece conversión de moneda local a USD/stablecoins y liquidación desde stablecoins a moneda local.','COMPANY_OFFICIAL','https://retorna.app/es/plataforma','On y off-ramp con USDC/USDT y monedas locales.',now(),now(),now()),
('OFFICIAL|RETORNA|VA_STABLECOIN_SERVICES|2026-09-09','ENTITY','ENT-RUT-76901962-6','VA_STABLECOIN_SERVICES','OBSERVED','OFFICIAL_OPEN',1.0,'Retorna usa USDC y USDT en su solución de dólares digitales y plataforma de pagos B2B.','COMPANY_OFFICIAL','https://retorna.app/es/plataforma','Liquidación y pagos con stablecoins USDC/USDT.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values
('COMPANY_OFFICIAL|VITA|USERS|2026-09-09','ENTITY','ENT-RUT-76974041-4','USERS',30000,'Más de 30.000 personas usan Vita Wallet','users',null,'AT_LEAST','REGIONAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://vitawallet.io/cl/',now(),'Cifra declarada en la página Chile; se conserva como piso de usuarios y no como clientes Chile-only estrictos.','Más de 30.000 personas',jsonb_build_object('lower_bound',true,'not_strictly_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|VITA|COUNTRIES_SERVICE_REACH|2026-09-09','ENTITY','ENT-RUT-76974041-4','COUNTRIES_SERVICE_REACH',50,'Disponible en más de 50 países','countries',null,'AT_LEAST','GLOBAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://vitawallet.io/transferencias-internacionales-empresas/',now(),'Alcance de destinos de servicio declarado, no presencia societaria.','Disponibles en más de 50 países',jsonb_build_object('lower_bound',true,'semantics','service_reach_not_legal_presence'),now(),now()),
('COMPANY_OFFICIAL|RETORNA|USERS|2026-09-09','ENTITY','ENT-RUT-76901962-6','USERS',522306,'Más de 522.306 personas confían en Retorna','users',null,'AT_LEAST','REGIONAL','DECLARADO',0.95,'COMPANY_OFFICIAL','https://www.retorna.app/es/envia-dinero-con-retorna',now(),'Contador declarado por la página de envíos; se registra con confianza alta pero no máxima por ser un contador comercial dinámico.','+522.306 personas confían en Retorna',jsonb_build_object('lower_bound',true,'commercial_counter',true),now(),now()),
('COMPANY_OFFICIAL|RETORNA|TRANSACTIONS_ANNUAL|2026-09-09','ENTITY','ENT-RUT-76901962-6','TRANSACTIONS_ANNUAL_COUNT',2000000,'Más de 2 millones de pagos al año','transactions',null,'AT_LEAST','REGIONAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://retorna.app/es/plataforma',now(),'La plataforma B2B declara procesamiento de más de 2 millones de pagos anuales. No equivale a volumen monetario.','2 millones de transacciones anuales',jsonb_build_object('lower_bound',true,'not_monetary_volume',true),now(),now()),
('COMPANY_OFFICIAL|RETORNA|COUNTRIES_SERVICE_REACH|2026-09-09','ENTITY','ENT-RUT-76901962-6','COUNTRIES_SERVICE_REACH',40,'Precios OTC / pagos en más de 40 países','countries',null,'AT_LEAST','GLOBAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://retorna.app/es/plataforma',now(),'Alcance de red/servicio declarado, no presencia societaria local en cada país.','más de 40 países',jsonb_build_object('lower_bound',true,'semantics','service_reach_not_legal_presence'),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();