insert into public.aml_fintech_market_metric_catalog(metric_code,label,dimension,unit_kind,default_unit,default_currency,comparable_scope,higher_means_more_weight,description,sort_order)
values
('PROCESSED_VOLUME_MONTHLY_USD','Volumen procesado mensual declarado','BUSINESS_ACTIVITY','CURRENCY','USD','USD','SAME_METRIC',true,'Volumen monetario procesado declarado para una ventana mensual. No equivale a ingresos de la fintech.',22),
('TRANSACTIONS_MONTHLY_COUNT','Operaciones mensuales declaradas','BUSINESS_ACTIVITY','COUNT','transactions',null,'SAME_METRIC',true,'Número de operaciones/transacciones procesadas en una ventana mensual. No equivale a volumen monetario.',23),
('PAYMENT_METHODS_COUNT','Métodos de pago habilitados','REACH','COUNT','payment_methods',null,'SAME_METRIC',true,'Número de métodos de pago declarados por una plataforma; mide amplitud de cobertura funcional, no clientes.',52)
on conflict(metric_code) do update set label=excluded.label,dimension=excluded.dimension,unit_kind=excluded.unit_kind,default_unit=excluded.default_unit,default_currency=excluded.default_currency,comparable_scope=excluded.comparable_scope,higher_means_more_weight=excluded.higher_means_more_weight,description=excluded.description,sort_order=excluded.sort_order;

with vals(fintech_id,primary_vertical,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ENT-RUT-77066914-6','Procesamiento de pagos y remesas','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'ProntoPaga es una infraestructura regional de PayIns, PayOuts y pagos a terceros integrada mediante API para comercios y empresas.','La oferta vigente se dirige a negocios, e-commerce, servicios financieros y otras empresas que integran recaudación y dispersión de pagos.','La documentación pública describe la infraestructura y operación, pero no publica una tarifa principal suficientemente generalizable para asignar un único modelo de ingresos.','https://www2.prontopaga.com/home-chile-es/'),
 ('ENT-RUT-77645606-3','WealthTech / Asesoría de inversión','B2B','EMPRESAS','ASESORIA_HONORARIOS',0.999::numeric,0.999::numeric,0.99::numeric,'Farellones Capital es una boutique de inversión y asesor de inversión RPSF que actúa como portfolio/investment manager bajo mandato delegado.','Sus servicios están restringidos a inversionistas calificados, institucionales y family offices calificados.','La actividad observable consiste en asesoría/gestión bajo mandato para inversionistas y vehículos; se representa como honorarios de asesoría/gestión dentro de la taxonomía disponible.','https://www.farcap.cl/'),
 ('ENT-RUT-77227254-5','WealthTech / Asesoría de inversión','B2B2C','AMBOS',null,0.999::numeric,0.999::numeric,null,'Ursa desarrolla sistemas de inversión cuantitativa y ofrece asesoría de inversión y gestión patrimonial mediante estrategias multiactivo.','La oferta admite clientes/inversionistas y contempla expresamente la posibilidad de invertir como persona jurídica.','El sitio no publica una tarifa suficientemente explícita para representar una única monetización principal.','https://ursagroup.cl/'),
 ('ENT-RUT-77121015-5','Mercados / FX institucional','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'MesaDinero ofrece liquidez FX, cobertura, derivados, pagos transfronterizos y conectividad a mercados para empresas, instituciones financieras y family offices.','El sitio identifica explícitamente como clientes a corporativos, instituciones financieras y family offices.','La plataforma declara spreads institucionales sin márgenes ocultos y actúa como canal/referenciamiento hacia terceros; no se fuerza un modelo de ingresos único.','https://www.mesadinero.com/')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_REGULATED_ECONOMIC_VERTICAL_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,v.revenue_model,v.rev_conf,1,now(),jsonb_build_object('source_url',v.source_url,'economic_vertical',v.primary_vertical,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'cohort','REGULATED_ECONOMIC_VERTICALS') from vals v returning fintech_id
)
update public.aml_fintech_entity e
set primary_vertical=v.primary_vertical,business_model=v.business_model,target_customer=v.target_customer,revenue_model=v.revenue_model,business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=v.rev_basis,revenue_model_confidence=v.rev_conf,profile_classifier_version='MANUAL_OFFICIAL_REGULATED_ECONOMIC_VERTICAL_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|PRONTOPAGA|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77066914-6','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'ProntoPaga procesa PayIns, PayOuts, pagos a terceros y métodos de tarjeta, transferencia y wallet/QR mediante API regional.','COMPANY_OFFICIAL','https://www2.prontopaga.com/home-chile-es/','Plataforma regional de recaudación y dispersión de pagos.',now(),now(),now()),
('OFFICIAL|FARELLONES|FIN_INVESTMENT_ADVISORY|2026-09-09','ENTITY','ENT-RUT-77645606-3','FIN_INVESTMENT_ADVISORY','OBSERVED','OFFICIAL_OPEN',1.0,'Farellones Capital declara estar inscrita en RPSF como asesor de inversión bajo Ley 21.521 para inversionistas calificados.','COMPANY_OFFICIAL','https://www.farcap.cl/','Asesor de inversión RPSF para inversionistas calificados.',now(),now(),now()),
('OFFICIAL|FARELLONES|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-77645606-3','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',0.99,'Farellones actúa como portfolio/investment manager bajo mandato delegado en estrategias de renta variable y crédito.','COMPANY_OFFICIAL','https://www.farcap.cl/','Portfolio Manager / Investment Manager bajo mandato.',now(),now(),now()),
('OFFICIAL|URSA|FIN_INVESTMENT_ADVISORY|2026-09-09','ENTITY','ENT-RUT-77227254-5','FIN_INVESTMENT_ADVISORY','OBSERVED','OFFICIAL_OPEN',1.0,'Ursa declara asesoría de inversión basada en sistemas cuantitativos y aparece autorizada como asesor RPSF CMF.','COMPANY_OFFICIAL','https://ursagroup.cl/','Asesoría de inversión cuantitativa.',now(),now(),now()),
('OFFICIAL|URSA|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-77227254-5','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'Ursa ofrece gestión patrimonial activa mediante una estrategia multiactivo basada en sus sistemas de inversión.','COMPANY_OFFICIAL','https://ursagroup.cl/','Gestión patrimonial y estrategia multiactivo.',now(),now(),now()),
('OFFICIAL|MESADINERO|FIN_REMITTANCE_FX|2026-09-09','ENTITY','ENT-RUT-77121015-5','FIN_REMITTANCE_FX','OBSERVED','OFFICIAL_OPEN',1.0,'MesaDinero ofrece liquidez institucional FX spot/forwards, cobertura y pagos transfronterizos a corporativos e instituciones.','COMPANY_OFFICIAL','https://www.mesadinero.com/','Divisas, cobertura y pagos transfronterizos.',now(),now(),now()),
('OFFICIAL|MESADINERO|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77121015-5','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'MesaDinero facilita pagos globales de corporativos a proveedores extranjeros y liquidación de divisas a través de entidades financieras reguladas.','COMPANY_OFFICIAL','https://www.mesadinero.com/','Pagos transfronterizos corporativos.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values
('COMPANY_OFFICIAL|PRONTOPAGA|PROCESSED_VOLUME_MONTHLY_USD|2026-09-09','ENTITY','ENT-RUT-77066914-6','PROCESSED_VOLUME_MONTHLY_USD',250000000,'Más de USD 250 millones procesados mensualmente','USD','USD','AT_LEAST','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www2.prontopaga.com/home-chile-es/',now(),'Métrica corporativa/regional declarada por ProntoPaga; no se interpreta como volumen Chile-only ni como ingresos.','+250MM USD procesado mensualmente',jsonb_build_object('lower_bound',true,'not_chile_only',true,'not_revenue',true),now(),now()),
('COMPANY_OFFICIAL|PRONTOPAGA|TRANSACTIONS_MONTHLY_COUNT|2026-09-09','ENTITY','ENT-RUT-77066914-6','TRANSACTIONS_MONTHLY_COUNT',8000000,'Más de 8.000.000 transacciones procesadas mensualmente','transactions',null,'AT_LEAST','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www2.prontopaga.com/home-chile-es/',now(),'Conteo regional declarado; no equivale a volumen monetario.','+8.000.000 tx procesadas mensualmente',jsonb_build_object('lower_bound',true,'not_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|PRONTOPAGA|PAYMENT_METHODS_COUNT|2026-09-09','ENTITY','ENT-RUT-77066914-6','PAYMENT_METHODS_COUNT',50,'Más de 50 métodos de pago','payment_methods',null,'AT_LEAST','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www2.prontopaga.com/home-chile-es/',now(),'Amplitud funcional declarada por ProntoPaga en su red regional.','+50 métodos de pago',jsonb_build_object('lower_bound',true),now(),now()),
('COMPANY_OFFICIAL|PRONTOPAGA|COUNTRIES_SERVICE_REACH|2026-09-09','ENTITY','ENT-RUT-77066914-6','COUNTRIES_SERVICE_REACH',5,'Operación local en 5 países','countries',null,'EXACT','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www2.prontopaga.com/home-chile-es/',now(),'ProntoPaga declara operación local en Argentina, Chile, Perú, Ecuador y Brasil.','Actualmente estamos presentes en 5 países',jsonb_build_object('semantics','local_operation_declared'),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();