create table if not exists public.aml_fintech_scope_assessment (
  assessment_id bigint generated by default as identity primary key,
  subject_type text not null check (subject_type in ('ENTITY','CANDIDATE')),
  subject_key text not null,
  scope_status text not null check (scope_status in ('CORE_FINTECH','FINANCIAL_TECH_INFRASTRUCTURE','ADJACENT_FINANCIAL_TECH','HISTORICAL_FINTECH','OUT_OF_SCOPE_CURRENT','UNCERTAIN')),
  include_in_current_universe boolean null,
  assessed_vertical text null,
  effective_date date not null default current_date,
  source_code text null references public.aml_fintech_source_catalog(source_code) on update cascade on delete set null,
  source_url text null,
  evidence_basis text not null,
  confidence numeric(5,4) not null default 0.8 check (confidence between 0 and 1),
  observed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists aml_fintech_scope_assessment_uq
on public.aml_fintech_scope_assessment(subject_type,subject_key,effective_date,scope_status);

create index if not exists aml_fintech_scope_assessment_subject_idx
on public.aml_fintech_scope_assessment(subject_type,subject_key,effective_date desc,observed_at desc);

alter table public.aml_fintech_scope_assessment enable row level security;
revoke all on table public.aml_fintech_scope_assessment from public, anon, authenticated;
grant select,insert,update,delete on table public.aml_fintech_scope_assessment to service_role;
grant usage,select on sequence public.aml_fintech_scope_assessment_assessment_id_seq to service_role;

create or replace view public.aml_v_fintech_scope_current
with (security_invoker=true)
as
select distinct on (subject_type,subject_key)
  assessment_id,subject_type,subject_key,scope_status,include_in_current_universe,
  assessed_vertical,effective_date,source_code,source_url,evidence_basis,confidence,observed_at,metadata
from public.aml_fintech_scope_assessment
order by subject_type,subject_key,effective_date desc,observed_at desc,assessment_id desc;

revoke all on public.aml_v_fintech_scope_current from public,anon,authenticated;
grant select on public.aml_v_fintech_scope_current to service_role;
