create table if not exists public.atlas_user_access_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null,
  actor_email text,
  target_user_id uuid not null,
  target_email text not null,
  action text not null check (action in ('grant','role_change','enable','disable')),
  old_role text,
  new_role text not null check (new_role in ('viewer','analyst','admin')),
  old_enabled boolean,
  new_enabled boolean not null,
  created_at timestamptz not null default now()
);

create index if not exists atlas_user_access_audit_created_idx
  on public.atlas_user_access_audit (created_at desc);
create index if not exists atlas_user_access_audit_target_idx
  on public.atlas_user_access_audit (target_user_id, created_at desc);

alter table public.atlas_user_access_audit enable row level security;
revoke all on public.atlas_user_access_audit from public, anon, authenticated;
grant select, insert on public.atlas_user_access_audit to service_role;
grant usage, select on sequence public.atlas_user_access_audit_id_seq to service_role;

create or replace function public.atlas_admin_apply_access_change(
  p_actor_user_id uuid,
  p_actor_email text,
  p_target_user_id uuid,
  p_target_email text,
  p_role text,
  p_enabled boolean,
  p_action text
)
returns table (
  user_id uuid,
  email text,
  role text,
  enabled boolean,
  updated_at timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_old_role text;
  v_old_enabled boolean;
  v_exists boolean := false;
begin
  if p_role not in ('viewer','analyst','admin') then
    raise exception using errcode = '22023', message = 'ATLAS_INVALID_ROLE';
  end if;
  if p_action not in ('grant','role_change','enable','disable') then
    raise exception using errcode = '22023', message = 'ATLAS_INVALID_ACTION';
  end if;
  if p_target_email is null or btrim(p_target_email) = '' then
    raise exception using errcode = '22023', message = 'ATLAS_TARGET_EMAIL_REQUIRED';
  end if;

  perform pg_advisory_xact_lock(194913821);

  select a.role, a.enabled
    into v_old_role, v_old_enabled
  from public.aml_allowed_users a
  where a.user_id = p_target_user_id
  for update;
  v_exists := found;

  if not v_exists and p_action <> 'grant' then
    raise exception using errcode = 'P0001', message = 'ATLAS_ACCESS_RECORD_NOT_FOUND';
  end if;

  if v_exists
     and v_old_role = 'admin'
     and v_old_enabled
     and (p_role <> 'admin' or not p_enabled)
     and not exists (
       select 1
       from public.aml_allowed_users other
       where other.user_id <> p_target_user_id
         and other.role = 'admin'
         and other.enabled
     ) then
    raise exception using errcode = 'P0001', message = 'ATLAS_LAST_ADMIN_PROTECTED';
  end if;

  insert into public.aml_allowed_users as a
    (user_id, email, role, enabled, created_at, updated_at)
  values
    (p_target_user_id, lower(btrim(p_target_email)), p_role, p_enabled, now(), now())
  on conflict (user_id) do update
    set email = excluded.email,
        role = excluded.role,
        enabled = excluded.enabled,
        updated_at = now();

  insert into public.atlas_user_access_audit (
    actor_user_id, actor_email, target_user_id, target_email,
    action, old_role, new_role, old_enabled, new_enabled
  ) values (
    p_actor_user_id, lower(nullif(btrim(p_actor_email), '')),
    p_target_user_id, lower(btrim(p_target_email)),
    p_action, v_old_role, p_role, v_old_enabled, p_enabled
  );

  return query
  select a.user_id, a.email, a.role, a.enabled, a.updated_at
  from public.aml_allowed_users a
  where a.user_id = p_target_user_id;
end;
$$;

revoke all on function public.atlas_admin_apply_access_change(uuid,text,uuid,text,text,boolean,text) from public, anon, authenticated;
grant execute on function public.atlas_admin_apply_access_change(uuid,text,uuid,text,text,boolean,text) to service_role;
