insert into public.aml_fintech_market_metric_observation(
  observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,
  evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at
)
values
('COMPANY_OFFICIAL|HACKMETRIX|BUSINESS_CLIENTS_NAMED_FLOOR|2026-09-09','ENTITY','ENT-RUT-76868755-2','BUSINESS_CLIENTS',18,'Al menos 18 clientes corporativos identificables publicados en la página oficial','companies',null,'AT_LEAST','LATAM','OBSERVADO_OFICIAL',0.999,'COMPANY_OFFICIAL','https://www.hackmetrix.com/clientes/',now(),'Piso verificable a partir de 18 logos/nombres de clientes visibles en la página oficial. La propia página declara adicionalmente que cientos de empresas latinoamericanas confían en Hackmetrix, pero esa expresión no se transforma en una cifra estimada.','Betterfly, Xepelin, Global66, Datamart, Lemontech, Fairplay, BenFrank, Buk, Meli, Truora, Vozy, Buda, AgendaPro, Talana, Khipu, Chattigo, Ubits y Healthatom.',jsonb_build_object('lower_bound',true,'named_clients_floor',true,'not_total_clients',true,'not_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|BETTERFLY|INSURED_PERSONS|2026-09-09','ENTITY','ENT-RUT-76837328-0','INSURED_PERSONS',1000000,'Un millón de vidas protegidas mediante diferentes seguros','insured_persons',null,'EXACT','INTERNATIONAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://betterfly.com/nueva-experiencia/',now(),'La página oficial celebra un millón de vidas/personas que acceden a protección mediante diferentes seguros. Se usa como alcance asegurado de la plataforma y no como pólizas individuales ni Chile-only.','Un millón de vidas que ahora disfrutan la tranquilidad a través de diferentes seguros.',jsonb_build_object('persons_not_policies',true,'not_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|NICO|INSURED_PERSONS|2026-09-09','ENTITY','ENT-RUT-59250540-1','INSURED_PERSONS',15000,'Más de 15.000 personas protegidas','insured_persons',null,'AT_LEAST','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.nicoseguros.com/corredor/',now(),'NICO declara más de 15.000 personas protegidas en su página para corredores. Se conserva separado de sus más de 900 pólizas vigentes y de la cartera en UF.','+15.000 personas protegidas.',jsonb_build_object('lower_bound',true,'persons_not_policies',true),now(),now()),
('COMPANY_OFFICIAL|SIMPLEE|INSURED_PERSONS|2026-09-09','ENTITY','ENT-RUT-76457365-K','INSURED_PERSONS',9000,'Más de 9.000 clientes asegurados','insured_persons',null,'AT_LEAST','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://simplee.cl/nosotros',now(),'Simplee declara más de 9.000 clientes asegurados. Se utiliza como aproximación directa al alcance asegurado de clientes, no como número de pólizas ni personas cubiertas por pólizas colectivas.','+ 9.000 clientes asegurados.',jsonb_build_object('lower_bound',true,'insured_clients_proxy',true,'not_policies',true),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,unit=excluded.unit,currency=excluded.currency,qualifier=excluded.qualifier,geography=excluded.geography,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_code=excluded.source_code,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select atlas_private.aml_fintech_refresh_market_weight();
