create table if not exists public.aml_fintech_profile_audit (
  audit_id bigint generated by default as identity primary key,
  fintech_id text not null,
  classifier_version text not null,
  business_model text,
  business_model_confidence numeric,
  target_customer text,
  target_customer_confidence numeric,
  revenue_model text,
  revenue_model_confidence numeric,
  pages_scanned integer,
  observed_at timestamptz not null default now(),
  evidence jsonb not null default '{}'::jsonb
);

alter table public.aml_fintech_profile_audit enable row level security;
revoke all on public.aml_fintech_profile_audit from public,anon,authenticated;
grant select,insert,update,delete on public.aml_fintech_profile_audit to service_role;

create index if not exists idx_fintech_profile_audit_entity_time on public.aml_fintech_profile_audit(fintech_id,observed_at desc);