insert into public.aml_fintech_market_metric_catalog(metric_code,label,dimension,unit_kind,default_unit,default_currency,comparable_scope,higher_means_more_weight,description,sort_order)
values
('BUSINESS_CLIENTS','Clientes empresa observados','REACH','COUNT','companies',null,'SAME_METRIC',true,'Número de empresas/clientes corporativos declarado u observado. No se mezcla con usuarios personas, hogares ni comercios afiliados.',45),
('HOUSEHOLDS','Hogares / familias alcanzadas','REACH','COUNT','households',null,'SAME_METRIC',true,'Número de hogares o familias declarado u observado. Se mantiene separado de usuarios y clientes empresa.',46),
('COUNTRIES_SERVICE_REACH','Países de alcance del servicio','REACH','COUNT','countries',null,'SAME_METRIC',true,'Países a los que el producto o infraestructura permite prestar/emitir el servicio; no equivale necesariamente a presencia societaria u operación local.',47)
on conflict(metric_code) do update set label=excluded.label,dimension=excluded.dimension,unit_kind=excluded.unit_kind,default_unit=excluded.default_unit,default_currency=excluded.default_currency,comparable_scope=excluded.comparable_scope,higher_means_more_weight=excluded.higher_means_more_weight,description=excluded.description,sort_order=excluded.sort_order;

delete from public.aml_fintech_market_metric_observation where observation_key='COMPANY_OFFICIAL|CREDITU|CLIENTS|2026-09-09';
insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values('COMPANY_OFFICIAL|CREDITU|HOUSEHOLDS|2026-09-09','ENTITY','ENT-RUT-76594721-9','HOUSEHOLDS',16000,'Más de 16.000 familias con hogar gracias a Creditú','households',null,'AT_LEAST','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://creditu.com/cl/',now(),'Creditú declara más de 16.000 familias. Se almacena como hogares/familias y no como clientes genéricos.','+16.000 familias con hogar gracias a Creditú',jsonb_build_object('lower_bound',true,'scope','Chile'),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ENT-RUT-76788282-3','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Fpay mantiene simultáneamente app para personas y portal/soluciones de cobro para comercios y sellers.','La oferta vigente observada incluye usuarios personas y comercios/sellers.','Fpay publica tasas por transacción de 2,9% para perfil básico y 2,6% para perfil completo en ventas directas de comercios.','https://fpay.cl/comercios/tasas/'),
 ('ENT-RUT-77096794-5','B2B2C','AMBOS','SPREAD_FX',0.999::numeric,0.999::numeric,0.99::numeric,'Global66 ofrece Cuenta Global para personas y Global66 Empresas/Business para compañías con pagos, cobros, FX y tesorería.','El sitio oficial declara más de 2,5 millones de personas y más de 10.000 empresas LATAM operando con la plataforma.','Global66 declara que en transferencias internacionales su costo principal es un margen/costo sobre el tipo de cambio, visible antes de confirmar.','https://www.global66.com/cl/'),
 ('ENT-RUT-77977667-0','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Haulmer/TUU desarrolla soluciones de pagos, facturación y tecnología para emprendedores, micro, pequeños y medianos negocios.','La contratación TUU se dirige a comercios y negocios que reciben pagos con tarjetas.','Los términos TUU 2026 establecen tarifas por plan/transacción y margen adquirente/PSP; el sitio publica comisión para crédito y débito.','https://www.haulmer.com/legal/terminos-y-condiciones-de-servicio-del-ecosistema-tuu/'),
 ('ENT-RUT-77268674-9','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Pomelo provee infraestructura de emisión, procesamiento y rieles de pagos mediante integración tecnológica para bancos, fintechs y empresas.','La oferta se dirige a organizaciones que lanzan productos financieros, programas de tarjetas y soluciones de pagos.',null,'https://www.pomelo.la/blog/tarjetas-globales-pomelo-global-card'),
 ('ENT-RUT-77126383-6','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Toku se presenta como infraestructura de pagos, recaudación y agentes para grandes empresas.','El producto está dirigido explícitamente a empresas y grandes organizaciones de múltiples industrias.',null,'https://trytoku.com/'),
 ('ENT-RUT-76967692-9','B2C','PERSONAS',null,0.999::numeric,0.999::numeric,null,'Tenpo ofrece cuenta digital, tarjetas, pagos, inversiones, seguros y billetera en dólares para clientes personas.','La oferta principal observada está dirigida a personas/clientes individuales.',null,'https://www.tenpo.cl/una-cuenta-muy-tu'),
 ('ENT-RUT-76584147-K','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.98::numeric,0.98::numeric,0.98::numeric,'Payku opera una pasarela/API de pagos y recaudación integrable a tiendas y comercios, con payouts y pagos recurrentes.','La documentación oficial de integración exige una tienda/comercio y cuentas Payku para procesar pagos.','Documentos tributarios alojados por Payku describen servicio de pago/recaudación y comisiones payout como conceptos cobrados.','https://cdn.payku.cl/public/ecommerce-plugins/jumpseller/manualjumpseller.pdf'),
 ('ENT-RUT-99584660-8','B2B','EMPRESAS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'PayU presta procesamiento, validación y transferencia de pagos a comercios.','Los términos chilenos regulan explícitamente el uso de PayU por comercios.','Los términos de comercios establecen tarifas cobradas por los servicios PayU.','https://chile.payu.com/wp-content/uploads/sites/4/2020/04/T%C3%89RMINOS-Y-CONDICIONES-GENERALES-DE-USO-PARA-COMERCIOS-PAYU.pdf')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_PAYMENTS_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,coalesce(v.revenue_model,e.revenue_model),coalesce(v.rev_conf,e.revenue_model_confidence),1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'cohort','PAYMENTS')
 from vals v join public.aml_fintech_entity e using(fintech_id)
 returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=coalesce(v.revenue_model,e.revenue_model),business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=case when v.revenue_model is not null then v.rev_basis else e.revenue_model_basis end,revenue_model_confidence=case when v.revenue_model is not null then v.rev_conf else e.revenue_model_confidence end,profile_classifier_version='MANUAL_OFFICIAL_PAYMENTS_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v
where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|FPAY|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76788282-3','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Fpay permite pagos en app y cobros/ventas para comercios y sellers.','COMPANY_OFFICIAL','https://fpay.cl/comercios/tasas/','Tasas por transacción para ventas con Fpay.',now(),now(),now()),
('OFFICIAL|FPAY|FIN_CARDS|2026-09-09','ENTITY','ENT-RUT-76788282-3','FIN_CARDS','OBSERVED','OFFICIAL_OPEN',1.0,'Fpay mantiene tarjeta virtual prepago asociada a la plataforma.','COMPANY_OFFICIAL','https://fpay.cl/tarjeta-fpay/','Tarjeta Fpay virtual con provisión de fondos.',now(),now(),now()),
('OFFICIAL|GLOBAL66|FIN_REMITTANCE_FX|2026-09-09','ENTITY','ENT-RUT-77096794-5','FIN_REMITTANCE_FX','OBSERVED','OFFICIAL_OPEN',1.0,'Global66 permite transferencias internacionales, compra/venta de divisas y cuentas multimoneda.','COMPANY_OFFICIAL','https://www.global66.com/cl/envios-de-dinero/','Envía dinero a más de 70 países y convierte monedas.',now(),now(),now()),
('OFFICIAL|GLOBAL66|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77096794-5','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Global66 ofrece pagos, cobros y transferencias para personas y empresas.','COMPANY_OFFICIAL','https://www.global66.com/empresas/por-que-global66/','Cuenta empresa para cobrar, pagar y manejar monedas.',now(),now(),now()),
('OFFICIAL|GLOBAL66|FIN_CARDS|2026-09-09','ENTITY','ENT-RUT-77096794-5','FIN_CARDS','OBSERVED','OFFICIAL_OPEN',1.0,'Global66 ofrece Smart Card para compras nacionales e internacionales.','COMPANY_OFFICIAL','https://www.global66.com/cl/tarjeta/','Smart Card usable en Chile y más de 160 países.',now(),now(),now()),
('OFFICIAL|GLOBAL66|VA_STABLECOIN_SERVICES|2026-09-09','ENTITY','ENT-RUT-77096794-5','VA_STABLECOIN_SERVICES','OBSERVED','OFFICIAL_OPEN',0.99,'Global66 permite recibir y operar stablecoins desde Cuenta Global/Business.','COMPANY_OFFICIAL','https://www.global66.com/cl/envios-de-dinero/','Recepción de USDC, USDT o PYUSD.',now(),now(),now()),
('OFFICIAL|HAULMER|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77977667-0','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Haulmer/TUU presta procesamiento de pagos con tarjetas y servicios PSP para comercios.','COMPANY_OFFICIAL','https://www.haulmer.com/legal/terminos-y-condiciones-de-servicio-del-ecosistema-tuu/','Autorización y registro de transacciones y afiliación de comercios.',now(),now(),now()),
('OFFICIAL|POMELO|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77268674-9','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Pomelo provee infraestructura de pagos multi-riel para organizaciones.','COMPANY_OFFICIAL','https://www.pomelo.la/blog/pomelo-expansion-global-emision-tarjetas-globales','Infraestructura de pagos local y global.',now(),now(),now()),
('OFFICIAL|POMELO|FIN_CARDS|2026-09-09','ENTITY','ENT-RUT-77268674-9','FIN_CARDS','OBSERVED','OFFICIAL_OPEN',1.0,'Pomelo permite a empresas lanzar programas de tarjetas mediante integración tecnológica.','COMPANY_OFFICIAL','https://www.pomelo.la/blog/tarjetas-globales-pomelo-global-card','Emisión de tarjetas Visa o Mastercard en más de 150 países.',now(),now(),now()),
('OFFICIAL|TOKU|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77126383-6','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Toku ofrece recaudación, pagos masivos y orquestación de infraestructura de pagos para grandes empresas.','COMPANY_OFFICIAL','https://trytoku.com/','Pagos y agentes para grandes empresas.',now(),now(),now()),
('OFFICIAL|TENPO|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76967692-9','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Tenpo ofrece cuenta digital y pago de cuentas para personas.','COMPANY_OFFICIAL','https://www.tenpo.cl/una-cuenta-muy-tu','Cuenta digital y pago de cuentas.',now(),now(),now()),
('OFFICIAL|TENPO|FIN_CARDS|2026-09-09','ENTITY','ENT-RUT-76967692-9','FIN_CARDS','OBSERVED','OFFICIAL_OPEN',1.0,'Tenpo ofrece tarjeta de crédito y servicios de cuenta/tarjeta a personas.','COMPANY_OFFICIAL','https://www.tenpo.cl/una-cuenta-muy-tu','Tarjeta de Crédito.',now(),now(),now()),
('OFFICIAL|TENPO|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-76967692-9','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'Tenpo ofrece productos de inversión desde su cuenta digital.','COMPANY_OFFICIAL','https://www.tenpo.cl/una-cuenta-muy-tu','Inversiones.',now(),now(),now()),
('OFFICIAL|PAYKU|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76584147-K','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',0.99,'Payku opera pasarela/API, payouts y pagos recurrentes para comercios.','COMPANY_OFFICIAL','https://status.payku.cl/','Servicios production, payouts, recurring payments y APIs operativos.',now(),now(),now()),
('OFFICIAL|KUSHKI|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76693142-1','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Kushki documenta para Chile modelos de adquirencia y agregación para pagos con tarjeta.','COMPANY_OFFICIAL','https://docs.kushki.com/cl/card-payments/model/','Pagos con tarjeta disponibles para adquirente/agregador.',now(),now(),now()),
('OFFICIAL|PAYU|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-99584660-8','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'PayU presta procesamiento, validación y transferencia de pagos a comercios.','COMPANY_OFFICIAL','https://chile.payu.com/wp-content/uploads/sites/4/2020/04/T%C3%89RMINOS-Y-CONDICIONES-GENERALES-DE-USO-PARA-COMERCIOS-PAYU.pdf','Servicios de procesamiento, validación y transferencia de pagos.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values
('COMPANY_OFFICIAL|GLOBAL66|USERS|2026-09-09','ENTITY','ENT-RUT-77096794-5','USERS',2500000,'Más de 2,5 millones de personas usan Global66','users',null,'AT_LEAST','GLOBAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.global66.com/cl',now(),'Cifra de usuarios personas declarada en sitio oficial.','Más de 2.5 millones de personas ya usan Global66',jsonb_build_object('lower_bound',true,'semantics','people'),now(),now()),
('COMPANY_OFFICIAL|GLOBAL66|BUSINESS_CLIENTS|2026-09-09','ENTITY','ENT-RUT-77096794-5','BUSINESS_CLIENTS',10000,'Más de 10.000 empresas en LATAM operan con Global66','companies',null,'AT_LEAST','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.global66.com/empresas/por-que-global66/',now(),'Cifra de clientes corporativos declarada por Global66 Business.','+10.000 empresas en todo latam ya operan con nosotros',jsonb_build_object('lower_bound',true,'semantics','companies'),now(),now()),
('COMPANY_OFFICIAL|HAULMER|BUSINESS_CLIENTS|2026-09-09','ENTITY','ENT-RUT-77977667-0','BUSINESS_CLIENTS',65000,'65K+ clientes felices','companies',null,'AT_LEAST','CHILE','DECLARADO',0.99,'COMPANY_OFFICIAL','https://www.haulmer.com/',now(),'Haulmer declara 65K+ clientes y orienta sus soluciones a emprendedores y MIPYMES. Se interpreta como clientes de negocio, no usuarios persona.','Clientes felices 65K+',jsonb_build_object('lower_bound',true,'semantics','business_customers'),now(),now()),
('COMPANY_OFFICIAL|POMELO|COUNTRIES_SERVICE_REACH|2026-09-09','ENTITY','ENT-RUT-77268674-9','COUNTRIES_SERVICE_REACH',150,'Más de 150 países disponibles para emisión global','countries',null,'AT_LEAST','GLOBAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.pomelo.la/blog/tarjetas-globales-pomelo-global-card',now(),'Alcance del producto Global Card; no implica presencia societaria local de Pomelo en cada país.','programas de tarjetas en más de 150 países',jsonb_build_object('lower_bound',true,'semantics','service_reach_not_presence'),now(),now()),
('COMPANY_OFFICIAL|TENPO|USERS|2026-09-09','ENTITY','ENT-RUT-76967692-9','USERS',2500000,'Más de 2.500.000 clientes/personas','users',null,'AT_LEAST','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.tenpo.cl/una-cuenta-muy-tu',now(),'Tenpo declara más de 2,5 millones en su cuenta digital para personas.','Somos más de 2.500.000',jsonb_build_object('lower_bound',true,'semantics','people'),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();