-- Elimina inferencias automáticas que la evidencia vigente no sostiene como funciones propias del actor Chile.
delete from public.aml_fintech_function_observation
where subject_type='ENTITY' and evidence_class='INFERRED_FROM_DECLARED' and (
  (subject_key='ENT-RUT-96637250-8' and function_code in ('FIN_LENDING','FIN_CARDS'))
  or (subject_key='ENT-RUT-77176962-4' and function_code='FIN_LENDING')
  or (subject_key='ENT-RUT-76893817-2' and function_code in ('FIN_LENDING','FIN_REGTECH','FIN_CARDS','VA_FIAT_EXCHANGE','VA_ON_OFF_RAMP','VA_STABLECOIN_SERVICES'))
  or (subject_key='ENT-RUT-77691219-0' and function_code in ('FIN_INVESTMENT','VA_FIAT_EXCHANGE'))
  or (subject_key='ENT-RUT-76113274-1' and function_code in ('FIN_LENDING','FIN_REGTECH'))
  or (subject_key='ENT-RUT-76704047-4' and function_code='FIN_REGTECH')
);

with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ENT-RUT-96637250-8','B2B2C','AMBOS','SPREAD_FX',0.999::numeric,0.999::numeric,0.99::numeric,'AFEX ofrece remesas/cambio de divisas para personas y transferencias corporativas/comercio exterior para empresas.','La oferta vigente cubre personas que envían/reciben dinero o cambian divisas y empresas que realizan transferencias corporativas.','El negocio observable se basa principalmente en cambio de divisas y transferencias/remesas; se conserva SPREAD_FX como mejor representación disponible.','https://www.afex.cl/'),
 ('ENT-RUT-77176962-4','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Ebury Chile ofrece a empresas cuentas multidivisa, pagos/recaudación, FX, cobertura y APIs/embedded finance.','La página Chile dirige la oferta a empresas en crecimiento, grandes empresas, instituciones y plataformas asociadas.','La oferta combina pagos, comisiones y margen/operativa FX; no se fuerza un único modelo de ingresos con la taxonomía actual.','https://ebury.com/es-cl'),
 ('ENT-RUT-76893817-2','B2B','EMPRESAS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.999::numeric,'Pagai/Factur-ai es software de facturación, cobranza y pagos para freelancers y Pymes, con panel, automatización e integraciones de medios de pago.','La propuesta de valor está dirigida a freelancers, Pymes y negocios que facturan/cobran.','La página publica planes Freemium/mensuales y precios transparentes; los medios de pago son integraciones de terceros.','https://factur-ai.cl/'),
 ('ENT-RUT-76113274-1','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Real-Time ofrece autenticación 3DS, consultoría e integración tecnológica de medios de pago para emisores/empresas.','Sus soluciones son empresariales y de infraestructura para sistemas de pago, no productos financieros de consumo.',null,'https://real-time.cl/'),
 ('ENT-RUT-76704047-4','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Supefina se presenta como plataforma regional de payins/payouts, pagos transfronterizos y gestión operativa para industrias y empresas.','Los casos de uso publicados se dirigen a gaming, lending, empresas y e-commerce como clientes de infraestructura de pagos.',null,'https://supefina.com/'),
 ('ENT-RUT-76727674-5','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.999::numeric,'Cleo es una plataforma de pagos de dos lados: consumidores usan BNPL/pagos y comercios integran BNPL, Transfer-In y Transfer-Out.','La oferta atiende personas y negocios/comercios mediante productos diferenciados.','La página empresarial muestra liquidaciones con comisiones y el modelo BNPL/pagos cobra al comercio por la operación; se conserva comisión transaccional.','https://cleo.cl/empresas'),
 ('ENT-RUT-76965744-4','B2B2C','AMBOS',null,0.999::numeric,0.999::numeric,null,'Tapp mantiene cuenta/tarjeta para personas y una oferta Tapp Empresas para Pymes/empresas.','La oferta vigente combina clientes personas y empresas.','No se fuerza monetización principal; tarjeta, remesas, pagos y servicios empresariales pueden tener mecanismos distintos.','https://www.tapp.cl/')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_QUALITY_PROVIDER_GEO_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,v.revenue_model,v.rev_conf,1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'quality_rule','do_not_attribute_third_party_or_other_country_functions') from vals v returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=v.revenue_model,business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=v.rev_basis,revenue_model_confidence=v.rev_conf,profile_classifier_version='MANUAL_QUALITY_PROVIDER_GEO_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

delete from public.aml_fintech_function_observation
where subject_type='ENTITY' and evidence_class='INFERRED_FROM_DECLARED' and (
 (subject_key='ENT-RUT-76965744-4' and function_code='FIN_LENDING')
 or (subject_key='ENT-RUT-76413747-7' and function_code='FIN_CARDS')
 or (subject_key='ENT-RUT-76727674-5' and function_code in ('FIN_LENDING','FIN_PAYMENTS'))
);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|AFEX|FIN_REMITTANCE_FX|2026-09-09','ENTITY','ENT-RUT-96637250-8','FIN_REMITTANCE_FX','OBSERVED','OFFICIAL_OPEN',1.0,'AFEX ofrece envíos/recepción de dinero, cambio de divisas y transferencias corporativas internacionales.','COMPANY_OFFICIAL','https://www.afex.cl/','Envíos de dinero, cambio de divisas y transferencias corporativas.',now(),now(),now()),
('OFFICIAL|AFEX|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-96637250-8','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',0.99,'AFEX gestiona pagos en Chile y transferencias corporativas SWIFT.','COMPANY_OFFICIAL','https://www.afex.cl/','Pagos en Chile y transferencias corporativas.',now(),now(),now()),
('OFFICIAL|EBURY|FIN_REMITTANCE_FX|2026-09-09','ENTITY','ENT-RUT-77176962-4','FIN_REMITTANCE_FX','OBSERVED','OFFICIAL_OPEN',1.0,'Ebury Chile ofrece cuentas multidivisa, pagos internacionales, conversiones spot y cobertura FX para empresas.','COMPANY_OFFICIAL','https://ebury.com/es-cl','Pagos internacionales y operaciones de divisas.',now(),now(),now()),
('OFFICIAL|EBURY|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77176962-4','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Ebury Chile permite pagos, recaudación, pagos masivos y APIs de pagos empresariales.','COMPANY_OFFICIAL','https://ebury.com/es-cl/products/business-accounts','Pagos y recaudación para empresas.',now(),now(),now()),
('OFFICIAL|PAGAI|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76893817-2','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Pagai genera links de cobro e integra siete proveedores de pago para que Pymes/freelancers cobren facturas. La función propia es orquestación/gestión de cobros, no los servicios cripto o adquirentes subyacentes.','COMPANY_OFFICIAL','https://factur-ai.cl/','Un link, siete medios/proveedores de pago.',now(),now(),now()),
('OFFICIAL|REALTIME|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76113274-1','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',0.99,'Real-Time presta infraestructura y consultoría tecnológica para medios de pago, incluyendo autenticación 3DS y procesos de tarjetas.','COMPANY_OFFICIAL','https://real-time.cl/','Soluciones de medios de pago y autenticación 3DS.',now(),now(),now()),
('OFFICIAL|SUPEFINA|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76704047-4','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Supefina ofrece payins, payouts, pagos transfronterizos y dispersión en tiempo real en LATAM.','COMPANY_OFFICIAL','https://supefina.com/','Payins y payouts en LATAM.',now(),now(),now()),
('OFFICIAL|CLEO|FIN_LENDING|2026-09-09','ENTITY','ENT-RUT-76727674-5','FIN_LENDING','OBSERVED','OFFICIAL_OPEN',1.0,'Cleo ofrece BNPL/cuotas sin tarjeta, evalúa al comprador, paga al comercio y asume el riesgo de cobranza.','COMPANY_OFFICIAL','https://cleo.cl/empresas/buy-now-pay-later','Cleo financia clientes y asume 100% del riesgo de cobranza.',now(),now(),now()),
('OFFICIAL|CLEO|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76727674-5','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Cleo ofrece BNPL, Transfer-In y Transfer-Out como soluciones de pago para comercios y usuarios.','COMPANY_OFFICIAL','https://cleo.cl/empresas','BNPL, transferencias de entrada y retiros masivos.',now(),now(),now()),
('OFFICIAL|TAPP|FIN_CARDS|2026-09-09','ENTITY','ENT-RUT-76965744-4','FIN_CARDS','OBSERVED','OFFICIAL_OPEN',1.0,'Los Andes Tarjetas de Prepago S.A. opera Tapp como cuenta/tarjeta prepago para clientes en Chile.','COMPANY_OFFICIAL','https://www.tapp.cl/','La tarjeta de Caja Los Andes.',now(),now(),now()),
('OFFICIAL|TAPP|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76965744-4','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Tapp permite pagos de cuentas, compras, retiros y servicios de pago desde la app.','COMPANY_OFFICIAL','https://www.tapp.cl/','Paga cuentas desde la app y usa saldo/tarjeta.',now(),now(),now()),
('OFFICIAL|TAPP|FIN_REMITTANCE_FX|2026-09-09','ENTITY','ENT-RUT-76965744-4','FIN_REMITTANCE_FX','OBSERVED','OFFICIAL_OPEN',0.99,'Tapp ofrece envío de dinero al extranjero desde la aplicación.','COMPANY_OFFICIAL','https://www.tapp.cl/','Envía dinero al extranjero con Tapp.',now(),now(),now()),
('OFFICIAL|TAPP|FIN_LENDING_CHANNEL|2026-09-09','ENTITY','ENT-RUT-76965744-4','FIN_LENDING','OBSERVED','OFFICIAL_OPEN',1.0,'Tapp funciona como canal digital para solicitar un crédito social otorgado por Caja Los Andes; esta evidencia no atribuye a Tapp la originación del crédito.','COMPANY_OFFICIAL','https://simuladorcredito.tapp.cl/','Crédito ofrecido por Caja Los Andes y disponibilizado a través de Tapp.',now(),now(),now()),
('OFFICIAL|DESTACAME|FIN_CARDS_PARTNER|2026-09-09','ENTITY','ENT-RUT-76413747-7','FIN_CARDS','OBSERVED','OFFICIAL_OPEN',0.99,'Destácame ofrece una Tarjeta Prepago Destácame by Tapp; se registra como producto distribuido/aliado y no como emisión propia de Destácame.','COMPANY_OFFICIAL','https://www.destacame.cl/','Tarjeta Prepago Destácame by Tapp.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,period_start,period_end,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values
('COMPANY_OFFICIAL|CLEO|USERS|2026-09-09','ENTITY','ENT-RUT-76727674-5','USERS',94000,'Más de 94.000 usuarios','users',null,'AT_LEAST',null,null,'CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://cleo.cl/',now(),'Cifra de usuarios declarada en la portada de Cleo Chile.','+94.000 usuarios ya usan Cleo',jsonb_build_object('lower_bound',true),now(),now()),
('COMPANY_OFFICIAL|CLEO|TPV_2025|2026-09-09','ENTITY','ENT-RUT-76727674-5','TPV_USD',104000000,'Más de USD 104 millones procesados en 2025','USD','USD','AT_LEAST','2025-01-01','2025-12-31','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://cleo.cl/empresas',now(),'Volumen procesado declarado para 2025; se conserva como TPV anual 2025, no como run-rate 2026.','+104 MM USD Procesados en 2025',jsonb_build_object('lower_bound',true,'period_semantics','calendar_2025'),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,period_start=excluded.period_start,period_end=excluded.period_end,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();