insert into public.aml_fintech_market_metric_catalog(metric_code,label,dimension,unit_kind,default_unit,default_currency,comparable_scope,higher_means_more_weight,description,sort_order)
values('API_CONNECTIONS','Conexiones API / financieras','REACH','COUNT','connections',null,'SAME_METRIC',true,'Número de conexiones financieras/API declaradas por una plataforma de infraestructura. No equivale a clientes ni instituciones únicas.',48)
on conflict(metric_code) do update set label=excluded.label,dimension=excluded.dimension,unit_kind=excluded.unit_kind,default_unit=excluded.default_unit,default_currency=excluded.default_currency,comparable_scope=excluded.comparable_scope,higher_means_more_weight=excluded.higher_means_more_weight,description=excluded.description,sort_order=excluded.sort_order;

with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ACTOR-14A99396232741F7','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Prometeo se define como infraestructura financiera B2B vía API para validar cuentas, pagos, tesorería y conectividad bancaria regional.','Los casos de uso y la contratación están dirigidos a bancos, plataformas financieras, pasarelas, e-commerce y empresas.','La evidencia pública actual describe una infraestructura API, pero no permite representar responsablemente la tarifa principal con un único modelo de ingresos.','https://prometeoapi.com/es/'),
 ('ENT-RUT-77532023-0','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Shinkansen se presenta como infraestructura financiera end-to-end que conecta empresas con bancos para pagos, tesorería y conciliación.','El producto está explícitamente diseñado para empresas, equipos financieros y bancos.',null,'https://shinkansen.finance/?country=CL'),
 ('ENT-RUT-77270553-0','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Geopagos provee infraestructura tecnológica de aceptación y adquirencia como servicio para bancos y agregadores de pago.','La oferta se dirige a bancos, adquirentes, agregadores y organizaciones que operan aceptación de pagos.',null,'https://blog.geopagos.com/nota/geopagos-impulsa-la-adquirencia-como-servicio-y-reduce-las-barreras-para-bancos-y-agregadores-de-pagos-en-america-latina'),
 ('ENT-RUT-77285658-K','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Regcheq es software de compliance corporativo que automatiza onboarding KYC, gestión de riesgos, monitoreo, listas y obligaciones UAF.','La oferta vigente está dirigida a organizaciones y empresas sujetas a obligaciones regulatorias o de compliance.','La oferta es una plataforma de software, pero no se fuerza SUSCRIPCION_SAAS sin tarifa/contrato público suficientemente explícito.','https://regcheq.com/es-cl'),
 ('ENT-RUT-59153640-0','B2B','EMPRESAS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.999::numeric,'Worldsys ofrece Compliance One como infraestructura de cumplimiento para sujetos obligados, bancos, fintechs y otras organizaciones.','La plataforma está dirigida a empresas y organizaciones que gestionan cumplimiento regulatorio.','Compliance One se describe expresamente como software como servicio, plataforma 100% cloud y modular.','https://www.worldsys.io/compliance-one'),
 ('ENT-RUT-77258323-0','B2B','EMPRESAS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.99::numeric,'Metriks comercializa soluciones modulares de onboarding, evaluación de riesgo y factoring digital como servicio para instituciones financieras y empresas.','Sus clientes declarados son bancos, cajas, cooperativas, factoring, seguros, leasing, fintechs, proptechs, inmobiliarias y otras empresas.','La compañía declara que comercializa sus soluciones As a Service; se representa como SUSCRIPCION_SAAS dentro de la taxonomía actual.','https://www.metriks.cl/'),
 ('ENT-RUT-76868755-2','B2B','EMPRESAS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.999::numeric,'Hackmetrix ofrece una plataforma de ciberseguridad y compliance para empresas, certificaciones y gestión continua de controles.','El acuerdo de suscripción define al cliente como compañía/entidad legal y la oferta Chile está dirigida a empresas.','Sus términos regulan expresamente un Acuerdo de Suscripción para la adquisición del servicio Hackmetrix.','https://www.hackmetrix.com/termsandconditions/'),
 ('ENT-RUT-76749144-1','B2B','EMPRESAS',null,0.99::numeric,0.99::numeric,null,'Datamart provee APIs y procesamiento de datos para evaluación comercial, financiera, riesgo, contratación y verificación de personas/empresas.','La documentación describe destinatarios empresariales que utilizan Datamart para procesos de evaluación y decisión.',null,'https://docs.datamart.cl/')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_INFRA_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,v.revenue_model,v.rev_conf,1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'cohort','FINANCIAL_INFRASTRUCTURE') from vals v returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=v.revenue_model,business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=v.rev_basis,revenue_model_confidence=v.rev_conf,profile_classifier_version='MANUAL_OFFICIAL_INFRA_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|PROMETEO|FIN_OPEN_FINANCE|2026-09-09','ENTITY','ACTOR-14A99396232741F7','FIN_OPEN_FINANCE','OBSERVED','OFFICIAL_OPEN',1.0,'Prometeo unifica conectividad bancaria, validación de cuentas e iniciación de pagos mediante APIs.','COMPANY_OFFICIAL','https://prometeoapi.com/es/','API bancaria, validación de cuentas e iniciación de pagos.',now(),now(),now()),
('OFFICIAL|PROMETEO|FIN_PAYMENTS|2026-09-09','ENTITY','ACTOR-14A99396232741F7','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Prometeo permite recibir/enviar pagos mediante rieles bancarios locales y transferencias account-to-account.','COMPANY_OFFICIAL','https://prometeoapi.com/servicio-transferencia-bancaria','Pagos por transferencia bancaria integrados vía API.',now(),now(),now()),
('OFFICIAL|SHINKANSEN|FIN_OPEN_FINANCE|2026-09-09','ENTITY','ENT-RUT-77532023-0','FIN_OPEN_FINANCE','OBSERVED','OFFICIAL_OPEN',1.0,'Shinkansen ofrece conexiones multibanco y una capa de infraestructura financiera para automatizar tesorería.','COMPANY_OFFICIAL','https://shinkansen.finance/?country=CL','Conexiones seguras a bancos y APIs multibanco.',now(),now(),now()),
('OFFICIAL|SHINKANSEN|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77532023-0','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Shinkansen ejecuta payins, payouts, pagos y conciliación de flujos empresariales.','COMPANY_OFFICIAL','https://shinkansen.finance/?country=CL','Pagos, Payouts, Payins y tesorería.',now(),now(),now()),
('OFFICIAL|GEOPAGOS|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-77270553-0','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',1.0,'Geopagos ofrece procesamiento adquirente y Acquiring as a Service desde el procesamiento al punto de venta.','COMPANY_OFFICIAL','https://blog.geopagos.com/nota/geopagos-impulsa-la-adquirencia-como-servicio-y-reduce-las-barreras-para-bancos-y-agregadores-de-pagos-en-america-latina','Adquirencia como servicio y aceptación de pagos digitales.',now(),now(),now()),
('OFFICIAL|REGCHEQ|FIN_REGTECH|2026-09-09','ENTITY','ENT-RUT-77285658-K','FIN_REGTECH','OBSERVED','OFFICIAL_OPEN',1.0,'Regcheq automatiza onboarding KYC, screening, riesgo, monitoreo y cumplimiento UAF.','COMPANY_OFFICIAL','https://regcheq.com/es-cl/cumplimiento-uaf','KYC, PEP, listas, monitoreo y reportes UAF.',now(),now(),now()),
('OFFICIAL|WORLDSYS|FIN_REGTECH|2026-09-09','ENTITY','ENT-RUT-59153640-0','FIN_REGTECH','OBSERVED','OFFICIAL_OPEN',1.0,'Compliance One cubre onboarding, screening, monitoreo transaccional, debida diligencia, riesgos y reporting.','COMPANY_OFFICIAL','https://www.worldsys.io/compliance-one','KYC/KYB, monitoreo transaccional y reporting regulatorio.',now(),now(),now()),
('OFFICIAL|METRIKS|FIN_OPEN_FINANCE|2026-09-09','ENTITY','ENT-RUT-77258323-0','FIN_OPEN_FINANCE','OBSERVED','OFFICIAL_OPEN',1.0,'Metriks ofrece Onboarding Open Finance como solución modular para empresas e instituciones financieras.','COMPANY_OFFICIAL','https://www.metriks.cl/','Onboarding Open Finance.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values
('COMPANY_OFFICIAL|PROMETEO|API_CONNECTIONS|2026-09-09','ENTITY','ACTOR-14A99396232741F7','API_CONNECTIONS',7500,'Más de 7.500 conexiones API','connections',null,'AT_LEAST','AMERICAS','DECLARADO',0.999,'COMPANY_OFFICIAL','https://prometeoapi.com/es/',now(),'Cifra de alcance API declarada por Prometeo en su sitio vigente.','+7,500 conexiones',jsonb_build_object('lower_bound',true),now(),now()),
('COMPANY_OFFICIAL|PROMETEO|COUNTRIES_SERVICE_REACH|2026-09-09','ENTITY','ACTOR-14A99396232741F7','COUNTRIES_SERVICE_REACH',110,'Presencia/alcance declarado en más de 110 países','countries',null,'AT_LEAST','GLOBAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://prometeoapi.com/es/',now(),'Se registra como alcance de servicio, no como presencia societaria confirmada en cada país.','+110 países',jsonb_build_object('lower_bound',true,'semantics','service_reach_not_legal_presence'),now(),now()),
('COMPANY_OFFICIAL|REGCHEQ|BUSINESS_CLIENTS|2026-09-09','ENTITY','ENT-RUT-77285658-K','BUSINESS_CLIENTS',600,'Más de 600 empresas de LATAM','companies',null,'AT_LEAST','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://regcheq.com/es-cl/nosotros',now(),'Regcheq declara más de 600 clientes/empresas en Chile, Brasil, México y Perú.','+600 Clientes',jsonb_build_object('lower_bound',true),now(),now()),
('COMPANY_OFFICIAL|REGCHEQ|COUNTRIES_SERVICE_REACH|2026-09-09','ENTITY','ENT-RUT-77285658-K','COUNTRIES_SERVICE_REACH',4,'Clientes en Chile, Brasil, México y Perú','countries',null,'EXACT','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://regcheq.com/es-cl/nosotros',now(),'Se registra alcance comercial declarado en cuatro países; no implica una sociedad local en cada uno.','En Chile, Brasil, México y Perú',jsonb_build_object('semantics','commercial_reach'),now(),now()),
('COMPANY_OFFICIAL|WORLDSYS|BUSINESS_CLIENTS|2026-09-09','ENTITY','ENT-RUT-59153640-0','BUSINESS_CLIENTS',300,'Más de 300 compañías usan sus soluciones','companies',null,'AT_LEAST','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.worldsys.io/',now(),'Cifra de compañías usuarias declarada por Worldsys.','+300 compañías',jsonb_build_object('lower_bound',true),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();