insert into public.aml_fintech_market_metric_catalog(metric_code,label,dimension,unit_kind,default_unit,default_currency,comparable_scope,higher_means_more_weight,description,sort_order)
values
('POLICIES_ENABLED_COUNT','Pólizas habilitadas / vendidas vía plataforma','BUSINESS_ACTIVITY','COUNT','policies',null,'SAME_METRIC',true,'Número de pólizas cuya venta/emisión fue habilitada por una plataforma tecnológica. No equivale necesariamente a pólizas propias ni a clientes únicos.',26),
('INSURANCE_SALES_ENABLED_USD','Ventas de seguros habilitadas por plataforma','BUSINESS_ACTIVITY','CURRENCY','USD','USD','SAME_METRIC',true,'Valor declarado de ventas de seguros procesadas/habilitadas por una plataforma. No corresponde a ingresos propios de la fintech.',27),
('INSURED_PERSONS','Asegurados alcanzados','REACH','COUNT','insured_persons',null,'SAME_METRIC',true,'Número de personas aseguradas alcanzadas por la plataforma o red; no equivale a clientes contractuales de la fintech.',49),
('HEALTH_PROVIDERS_NETWORK','Prestadores de salud en red','REACH','COUNT','providers',null,'SAME_METRIC',true,'Número de profesionales o prestadores de salud conectados a la red/plataforma.',50),
('AGREEMENTS_COUNT','Convenios / acuerdos de red','REACH','COUNT','agreements',null,'SAME_METRIC',true,'Número de convenios o acuerdos declarados por la plataforma.',51)
on conflict(metric_code) do update set label=excluded.label,dimension=excluded.dimension,unit_kind=excluded.unit_kind,default_unit=excluded.default_unit,default_currency=excluded.default_currency,comparable_scope=excluded.comparable_scope,higher_means_more_weight=excluded.higher_means_more_weight,description=excluded.description,sort_order=excluded.sort_order;

update public.aml_fintech_entity
set website='https://home.embedx.io/',refreshed_at=now()
where fintech_id='ENT-RUT-77277142-8';

with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ENT-RUT-76052998-2','B2B2C','AMBOS',null,0.999::numeric,0.999::numeric,null,'ComparaOnline opera un marketplace digital de seguros y productos financieros para consumidores y, mediante su corredora relacionada, intermedia seguros con compañías aseguradoras.','La plataforma atiende usuarios finales que comparan/contratan y mantiene relaciones B2B con aseguradoras/proveedores financieros.','El sitio explica que la corredora intermedia pólizas y que la sociedad titular compara/redirige productos, pero no expone una estructura de remuneración suficientemente homogénea para asignar un único código.','https://www.comparaonline.cl/'),
 ('ENT-RUT-77277142-8','B2B','EMPRESAS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.99::numeric,'EmbedX provee un core modular y soluciones de embedded insurance que aseguradoras y empresas integran para venta, postventa, siniestros y canales affinity.','Los clientes observados son aseguradoras, corredores y empresas que incorporan seguros a sus canales digitales.','La solución se comercializa como plataforma tecnológica B2B modular; se mantiene la monetización SaaS ya estructurada.','https://home.embedx.io/'),
 ('ENT-RUT-76894372-9','B2B2C','AMBOS',null,0.999::numeric,0.999::numeric,null,'Gerty combina marketplace de salud para pacientes con infraestructura para clínicas, aseguradoras y empresas que gestiona beneficios, siniestros y pagos de salud.','La oferta vigente atiende pacientes/personas y organizaciones: clínicas, aseguradoras y empresas.','La evidencia pública revisada describe la red y servicios, pero no publica una estructura de precios suficientemente representativa para asignar un único modelo de ingresos.','https://www.gerty.com/aseguradoras-y-empresas'),
 ('ENT-RUT-77576082-6','B2B2C','AMBOS','SUSCRIPCION_SAAS',0.999::numeric,0.999::numeric,0.99::numeric,'Pawer ofrece planes individuales de salud/seguro veterinario y una solución Pawer Empresas como beneficio para colaboradores.','La oferta vigente atiende personas directamente y empresas que contratan o facilitan planes a sus colaboradores.','Los planes funcionan bajo pago recurrente/suscripción; en empresas el valor depende de colaboradores y coberturas y puede ser pagado por la empresa o directamente por el colaborador.','https://ayuda.somospawer.com/es/articles/7992028-precios-de-planes-pawer-empresas-valores-y-formas-de-pago')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_INSURTECH_COMPLETION_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,coalesce(v.revenue_model,e.revenue_model),coalesce(v.rev_conf,e.revenue_model_confidence),1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'cohort','INSURTECH_COMPLETION')
 from vals v join public.aml_fintech_entity e using(fintech_id)
 returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=coalesce(v.revenue_model,e.revenue_model),business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=case when v.revenue_model is not null then v.rev_basis else e.revenue_model_basis end,revenue_model_confidence=case when v.revenue_model is not null then v.rev_conf else e.revenue_model_confidence end,profile_classifier_version='MANUAL_OFFICIAL_INSURTECH_COMPLETION_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|COMPARAONLINE|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-76052998-2','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'ComparaOnline compara y facilita contratación de seguros, mientras su corredora relacionada intermedia pólizas y recauda primas.','COMPANY_OFFICIAL','https://www.comparaonline.cl/blog/informacion-al-publico/','Compara Online Corredora de Seguros SpA actúa como intermediario entre clientes y compañías.',now(),now(),now()),
('OFFICIAL|EMBEDX|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-77277142-8','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'EmbedX digitaliza venta/postventa, emisión, clientes, siniestros y embedded insurance para aseguradoras y empresas.','COMPANY_OFFICIAL','https://home.embedx.io/','Core modular y ecosistema end-to-end de seguros.',now(),now(),now()),
('OFFICIAL|GERTY|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-76894372-9','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'Gerty presta a aseguradoras y empresas soluciones de beneficios de salud, control de fraude/siniestralidad, liquidación y pago de siniestros y red de prestadores.','COMPANY_OFFICIAL','https://www.gerty.com/aseguradoras-y-empresas','Seguros de salud a medida, liquidación y pago de siniestros.',now(),now(),now()),
('OFFICIAL|PAWER|FIN_INSURTECH|2026-09-09','ENTITY','ENT-RUT-77576082-6','FIN_INSURTECH','OBSERVED','OFFICIAL_OPEN',1.0,'Pawer ofrece coberturas veterinarias digitales, reembolsos, telemedicina y planes personales/empresa para mascotas.','COMPANY_OFFICIAL','https://somospawer.com/','Seguro de mascotas para empresas y planes personales.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values
('COMPANY_OFFICIAL|EMBEDX|POLICIES_ENABLED|2026-09-09','ENTITY','ENT-RUT-77277142-8','POLICIES_ENABLED_COUNT',5000000,'Más de 5.000.000 de pólizas vendidas a través de la tecnología EmbedX','policies',null,'AT_LEAST','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://home.embedx.io/',now(),'Cifra de pólizas habilitadas/vendidas mediante la plataforma; no corresponde a pólizas propias de EmbedX.','+5.000.000 de pólizas vendidas',jsonb_build_object('lower_bound',true,'platform_enabled',true,'not_own_policies',true),now(),now()),
('COMPANY_OFFICIAL|EMBEDX|INSURANCE_SALES_ENABLED_USD|2026-09-09','ENTITY','ENT-RUT-77277142-8','INSURANCE_SALES_ENABLED_USD',200000000,'USD 200 millones en ventas habilitadas por la plataforma','USD','USD','APPROX','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://home.embedx.io/',now(),'Valor de ventas de seguros habilitadas por EmbedX; no constituye ingresos de EmbedX.','200 MM USD en ventas',jsonb_build_object('platform_enabled',true,'not_company_revenue',true),now(),now()),
('COMPANY_OFFICIAL|GERTY|INSURED_PERSONS|2026-09-09','ENTITY','ENT-RUT-76894372-9','INSURED_PERSONS',1000000,'Más de 1.000.000 de asegurados','insured_persons',null,'AT_LEAST','REGIONAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.gerty.com/aseguradoras-y-empresas',now(),'Cifra declarada por Gerty para su ecosistema/red; no equivale a clientes contractuales únicos.','+1.000.000 de asegurados',jsonb_build_object('lower_bound',true,'ecosystem_reach',true),now(),now()),
('COMPANY_OFFICIAL|GERTY|HEALTH_PROVIDERS_NETWORK|2026-09-09','ENTITY','ENT-RUT-76894372-9','HEALTH_PROVIDERS_NETWORK',25000,'Más de 25.000 profesionales de salud conectados','providers',null,'AT_LEAST','REGIONAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.gerty.com/aseguradoras-y-empresas',now(),'Prestadores/profesionales que usan alguna solución tecnológica Gerty.','Más de 25.000 profesionales de la salud',jsonb_build_object('lower_bound',true),now(),now()),
('COMPANY_OFFICIAL|GERTY|AGREEMENTS|2026-09-09','ENTITY','ENT-RUT-76894372-9','AGREEMENTS_COUNT',3500,'Más de 3.500 convenios','agreements',null,'AT_LEAST','REGIONAL','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.gerty.com/prestadores',now(),'Número de convenios declarados por Gerty dentro de su red.','+3.500 convenios',jsonb_build_object('lower_bound',true),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();