with vals(fintech_id,primary_vertical,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ENT-RUT-76116575-5','WealthTech','B2B2C','AMBOS','ASESORIA_HONORARIOS',0.999::numeric,0.999::numeric,0.999::numeric,'Nauta presta asesoría de inversión digital y planificación financiera mediante una plataforma propia; acepta personas naturales y jurídicas.','Los términos vigentes definen como cliente tanto a persona natural como a persona jurídica.','Nauta recibe remuneración por inversiones referidas a fondos y cobra fee fijo + fee de implementación en su producto de planificación financiera.','https://www.nauta.pro/paginas-footer/terminos-y-condiciones'),
 ('ENT-RUT-76445652-1','WealthTech','B2C','PERSONAS','ASESORIA_HONORARIOS',0.999::numeric,0.999::numeric,0.999::numeric,'Fintual ofrece inversión digital y administración de fondos/portafolios a clientes personas.','La oferta Chile observada está orientada principalmente a personas que ahorran e invierten mediante la plataforma.','Fintual cobra comisión anual de administración sobre el monto invertido, con tarifas publicadas para fondos y APV.','https://ayuda.fintual.cl/es/articles/4671366-como-me-cobran-las-comisiones'),
 ('ENT-RUT-76969638-5','WealthTech','B2C','PERSONAS','ASESORIA_HONORARIOS',0.999::numeric,0.999::numeric,0.999::numeric,'Racional ofrece portafolios, acciones/ETF y asesoría de inversión mediante app para inversionistas individuales.','La oferta vigente está dirigida a personas que ahorran e invierten en Portafolios y Stocks.','Racional Portafolios cobra 1% anual IVA incluido sobre el valor promedio invertido; otros productos pueden tener estructura diferenciada.','https://racional.cl/portafolios'),
 ('ENT-RUT-77084652-8','WealthTech','B2B2C','AMBOS','ASESORIA_HONORARIOS',0.999::numeric,0.999::numeric,0.999::numeric,'Betterplan ofrece asesoría de inversión y wealth management a personas y también estrategias de inversión para sociedades/empresas.','La oferta vigente contempla inversionistas personas y sociedades/personas jurídicas.','Betterplan cobra fee anual sobre patrimonio asesorado, con tramos y una comisión de corredora en ciertos segmentos.','https://betterplan.cl/pricing'),
 ('ENT-RUT-77057272-K','WealthTech','B2C','PERSONAS','ASESORIA_HONORARIOS',0.999::numeric,0.999::numeric,0.999::numeric,'SoyFocus administra inversiones mediante fondos mutuos y portafolios pasivos para personas.','La oferta vigente está orientada a personas/inversionistas individuales.','SoyFocus declara que su única fuente de ingresos es la comisión de administración de sus fondos, actualmente 0,95% anual serie B y 0,45% APV.','https://soyfocus.com/ayuda/articulos/cuales-son-las-comisiones-de-soyfocus/'),
 ('ENT-RUT-77299015-4','WealthTech','B2B2C','AMBOS','ASESORIA_HONORARIOS',0.999::numeric,0.999::numeric,0.999::numeric,'Holdo ofrece inversión y asesoría automatizada/humana para personas y una cuenta específica para empresas y sociedades.','La plataforma atiende personas y también empresas/sociedades para gestión de patrimonio y excedentes de caja.','Holdo declara una comisión máxima de 1% + IVA anual por asesoría sobre el monto invertido; esta es su fuente de remuneración por el servicio.','https://www.holdo.cl/comisiones'),
 ('ENT-RUT-76632437-1','WealthTech','B2B','EMPRESAS','ASESORIA_HONORARIOS',0.999::numeric,0.999::numeric,0.99::numeric,'DVA Capital quedó dedicada a la administración de cartera de fondos gestionados por una AGF, tras separar en 2024 la plataforma de asesoría hacia Nauta.','Su contraparte económica directa observada es la AGF/vehículos de fondos cuya cartera administra.','La remuneración por administración de cartera es pagada por la Administradora General de Fondos, según la información legal publicada por DVA.','https://www.dvacapital.com/fondos'),
 ('ENT-RUT-76538670-5','WealthTech','B2C','PERSONAS','SPREAD_FX',0.999::numeric,0.999::numeric,0.999::numeric,'Capitaria ofrece plataforma de trading/inversión apalancada para clientes que operan instrumentos financieros globales.','La comunicación y tipos de cuenta observados están dirigidos principalmente a traders/inversionistas personas.','Capitaria declara no cobrar comisión por transacción; el costo principal para el cliente es el spread de mercado.','https://www.capitaria.com/aspectos-operativos/'),
 ('ENT-RUT-77554238-1','Activos Digitales / WealthTech','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.999::numeric,0.999::numeric,0.95::numeric,'Skipo combina inversión en cripto, acciones tokenizadas y stablecoins para personas con servicios OTC/API e integración de stablecoins para empresas.','La oferta vigente distingue usuarios personas y empresas que integran stablecoins u operan institucionalmente.','Las operaciones internas se publicitan sin comisión al usuario; Skipo declara que recibe pagos de proveedores de liquidez por el flujo de órdenes y cobra determinadas tarifas por servicios externos.','https://skipo.com/es/faq/')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_WEALTH_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,v.revenue_model,v.rev_conf,1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'cohort','WEALTH_CORE') from vals v returning fintech_id
)
update public.aml_fintech_entity e
set primary_vertical=v.primary_vertical,business_model=v.business_model,target_customer=v.target_customer,revenue_model=v.revenue_model,
    business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,
    revenue_model_basis=v.rev_basis,revenue_model_confidence=v.rev_conf,profile_classifier_version='MANUAL_OFFICIAL_WEALTH_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_operating_status_audit(fintech_id,previous_status,new_status,confidence,method,basis,source_codes,source_urls,status_as_of,validator_version)
select 'ENT-RUT-76116575-5',operating_status,'ACTIVE',0.999,'MANUAL_OFFICIAL','Nauta S.A. figura activa en SII, vigente en RPSF CMF y mantiene plataforma/servicios públicos operativos.',array['SII_PUBLIC','CMF_RPSF','COMPANY_OFFICIAL'],array['https://www.sii.cl/','https://www.cmfchile.cl/institucional/mercados/entidad.php?auth=&send=&mercado=O&rut=76116575&grupo=&tipoentidad=RGPSF&vig=VI&row=AAAwy2ACTAAABzfAAH&control=svs&pestania=1','https://www.nauta.pro/'],current_date,'MANUAL_OFFICIAL_WEALTH_2026_09_09'
from public.aml_fintech_entity where fintech_id='ENT-RUT-76116575-5';

update public.aml_fintech_entity
set operating_status='ACTIVE',operating_status_basis='SII activo + RPSF CMF vigente + plataforma Nauta operativa y términos actuales.',operating_status_source_code='CMF_RPSF',operating_status_source_url='https://www.cmfchile.cl/institucional/mercados/entidad.php?auth=&send=&mercado=O&rut=76116575&grupo=&tipoentidad=RGPSF&vig=VI&row=AAAwy2ACTAAABzfAAH&control=svs&pestania=1',operating_status_as_of=current_date,lifecycle_basis='Nauta opera desde la reestructuración del Grupo DVA como plataforma independiente de asesoría de inversión.',lifecycle_validated_at=now(),refreshed_at=now()
where fintech_id='ENT-RUT-76116575-5';

insert into public.aml_fintech_regulatory_status(fintech_id,regulator,registry,service,status,registration_no,effective_date,source_url,observed_at)
values('ENT-RUT-76116575-5','CMF','RPSF','ASESORIA_DE_INVERSION','VIGENTE','88','2023-02-03','https://www.cmfchile.cl/institucional/mercados/entidad.php?auth=&send=&mercado=O&rut=76116575&grupo=&tipoentidad=RGPSF&vig=VI&row=AAAwy2ACTAAABzfAAH&control=svs&pestania=1',now())
on conflict(fintech_id,regulator,registry,service) do update set status=excluded.status,registration_no=excluded.registration_no,effective_date=excluded.effective_date,source_url=excluded.source_url,observed_at=now();

insert into public.aml_fintech_actor_alias(fintech_id,alias_text,alias_type,domain,source_code,source_url,evidence_basis,confidence,active,first_seen_at,last_seen_at,metadata)
select 'ENT-RUT-76116575-5','Mi DVA','BRAND','nauta.pro','COMPANY_OFFICIAL','https://www.nauta.pro/migracion','La plataforma Mi DVA migró a Nauta durante la reestructuración 2024; se conserva como alias histórico de la experiencia/plataforma, no como identidad jurídica.',0.999,false,now(),now(),jsonb_build_object('historical',true,'scope','platform')
where not exists(select 1 from public.aml_fintech_actor_alias where fintech_id='ENT-RUT-76116575-5' and lower(alias_text)='mi dva');

insert into public.aml_fintech_subject_relationship(subject_type,subject_key,relation_type,target_fintech_id,target_rut,target_atlas_entity_id,target_label,valid_from,source_code,source_url,evidence_basis,confidence,active,first_seen_at,last_seen_at,metadata)
select 'ENTITY','ENT-RUT-76116575-5','SUCCESSOR_OF','ENT-RUT-76632437-1','76632437-1','ENT-RUT-76632437-1','DVA Capital','2024-08-02','COMPANY_OFFICIAL','https://www.nauta.pro/paginas-footer/relacion-con-dva','Nauta sucede a Mi DVA/DVA en el alcance específico de plataforma y asesoría de inversión. DVA Capital continúa como entidad independiente dedicada a administración de cartera.',0.999,true,now(),now(),jsonb_build_object('scope','Mi DVA platform and investment advisory business only','not_full_corporate_successor',true)
where not exists(select 1 from public.aml_fintech_subject_relationship where subject_type='ENTITY' and subject_key='ENT-RUT-76116575-5' and relation_type='SUCCESSOR_OF' and target_fintech_id='ENT-RUT-76632437-1' and active);

insert into public.aml_fintech_subject_relationship(subject_type,subject_key,relation_type,target_fintech_id,target_rut,target_atlas_entity_id,target_label,valid_from,source_code,source_url,evidence_basis,confidence,active,first_seen_at,last_seen_at,metadata)
select 'ENTITY','ENT-RUT-76632437-1','PREDECESSOR_OF','ENT-RUT-76116575-5','76116575-5','ENT-RUT-76116575-5','Nauta','2024-08-02','COMPANY_OFFICIAL','https://www.dvacapital.com/nauta','DVA Capital fue el antecedente de la plataforma Mi DVA; la asesoría/plataforma migró a Nauta en 2024, mientras DVA continuó con administración de cartera.',0.999,true,now(),now(),jsonb_build_object('scope','Mi DVA platform and investment advisory business only','not_full_corporate_predecessor',true)
where not exists(select 1 from public.aml_fintech_subject_relationship where subject_type='ENTITY' and subject_key='ENT-RUT-76632437-1' and relation_type='PREDECESSOR_OF' and target_fintech_id='ENT-RUT-76116575-5' and active);

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|NAUTA|FIN_INVESTMENT_ADVISORY|2026-09-09','ENTITY','ENT-RUT-76116575-5','FIN_INVESTMENT_ADVISORY','OBSERVED','OFFICIAL_OPEN',1.0,'Nauta está autorizada por la CMF exclusivamente para asesoría de inversión y genera recomendaciones personalizadas según perfil y objetivos.','COMPANY_OFFICIAL','https://www.nauta.pro/paginas-footer/terminos-y-condiciones','Servicio de asesoría de inversión autorizado bajo Ley 21.521/NCG 502.',now(),now(),now()),
('OFFICIAL|FINTUAL|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-76445652-1','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'Fintual ofrece y administra fondos/portafolios de inversión digitales para sus clientes.','COMPANY_OFFICIAL','https://ayuda.fintual.cl/es/articles/4671366-como-me-cobran-las-comisiones','Comisión anual aplicada sobre fondos administrados.',now(),now(),now()),
('OFFICIAL|RACIONAL|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-76969638-5','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'Racional permite invertir en portafolios, acciones y ETF desde su plataforma.','COMPANY_OFFICIAL','https://racional.cl/','Portafolios, Stocks y ETF.',now(),now(),now()),
('OFFICIAL|RACIONAL|FIN_INVESTMENT_ADVISORY|2026-09-09','ENTITY','ENT-RUT-76969638-5','FIN_INVESTMENT_ADVISORY','OBSERVED','OFFICIAL_OPEN',1.0,'Racional SpA declara ser asesor de inversión y enrutador de órdenes inscrito/autorizado bajo Ley Fintec.','COMPANY_OFFICIAL','https://racional.cl/','Asesor de inversión inscrito en RPSF CMF.',now(),now(),now()),
('OFFICIAL|BETTERPLAN|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-77084652-8','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'Betterplan facilita estrategias y acceso a fondos/ETF para construir portafolios.','COMPANY_OFFICIAL','https://betterplan.cl/opciones-de-inversion','Portafolios con ETF y fondos.',now(),now(),now()),
('OFFICIAL|BETTERPLAN|FIN_INVESTMENT_ADVISORY|2026-09-09','ENTITY','ENT-RUT-77084652-8','FIN_INVESTMENT_ADVISORY','OBSERVED','OFFICIAL_OPEN',1.0,'Betterplan ofrece asesoría de inversión independiente y wealth management.','COMPANY_OFFICIAL','https://betterplan.cl/','Asesoría de inversión independiente regulada por CMF.',now(),now(),now()),
('OFFICIAL|SOYFOCUS|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-77057272-K','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'SoyFocus administra fondos mutuos/portafolios de inversión pasivos.','COMPANY_OFFICIAL','https://soyfocus.com/como-invertimos/','Fondos mutuos diversificados y estrategia pasiva.',now(),now(),now()),
('OFFICIAL|HOLDO|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-77299015-4','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'Holdo ofrece portafolios, ETF, deuda privada y soluciones de inversión para personas y sociedades.','COMPANY_OFFICIAL','https://www.holdo.cl/comisiones','Productos de inversión y gestión de patrimonio.',now(),now(),now()),
('OFFICIAL|HOLDO|FIN_INVESTMENT_ADVISORY|2026-09-09','ENTITY','ENT-RUT-77299015-4','FIN_INVESTMENT_ADVISORY','OBSERVED','OFFICIAL_OPEN',1.0,'Holdo cobra por asesoría de inversión y combina asesoría automatizada con apoyo humano.','COMPANY_OFFICIAL','https://ayuda.holdo.cl/es/articles/6026986-cual-es-la-comision-de-holdo','Comisión por servicio de asesoría.',now(),now(),now()),
('OFFICIAL|DVA|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-76632437-1','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'DVA Capital administra carteras de fondos de Vinci/Compass en calidad de administrador de cartera.','COMPANY_OFFICIAL','https://www.dvacapital.com/fondos','Administrador de cartera de fondos temáticos.',now(),now(),now()),
('OFFICIAL|CAPITARIA|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-76538670-5','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'Capitaria permite a clientes operar instrumentos globales como acciones, commodities, ETF y divisas mediante plataforma de trading.','COMPANY_OFFICIAL','https://www.capitaria.com/','Operación de instrumentos financieros globales.',now(),now(),now()),
('OFFICIAL|SKIPO|FIN_INVESTMENT|2026-09-09','ENTITY','ENT-RUT-77554238-1','FIN_INVESTMENT','OBSERVED','OFFICIAL_OPEN',1.0,'Skipo ofrece inversión en acciones tokenizadas, cripto y otros activos digitales desde una misma plataforma.','COMPANY_OFFICIAL','https://skipo.com/es/','Inversión en stocks tokenizados, cripto y stablecoins.',now(),now(),now()),
('OFFICIAL|SKIPO|VA_FIAT_EXCHANGE|2026-09-09','ENTITY','ENT-RUT-77554238-1','VA_FIAT_EXCHANGE','OBSERVED','OFFICIAL_OPEN',1.0,'Skipo permite comprar y vender criptomonedas directamente con pesos chilenos.','COMPANY_OFFICIAL','https://skipo.com/es/faq/','Compra y venta de criptomonedas.',now(),now(),now()),
('OFFICIAL|SKIPO|VA_TRANSFER|2026-09-09','ENTITY','ENT-RUT-77554238-1','VA_TRANSFER','OBSERVED','OFFICIAL_OPEN',1.0,'Skipo permite transferencias entre usuarios y retiros hacia billeteras externas.','COMPANY_OFFICIAL','https://skipo.com/es/faq/','Transferencias y retiros cripto.',now(),now(),now()),
('OFFICIAL|SKIPO|VA_HOSTED_WALLET|2026-09-09','ENTITY','ENT-RUT-77554238-1','VA_HOSTED_WALLET','OBSERVED','OFFICIAL_OPEN',0.99,'Skipo mantiene billeteras dentro de la plataforma y publica creación/mantención de billeteras como funcionalidad.','COMPANY_OFFICIAL','https://skipo.com/es/fees/','Creación y mantención de billeteras.',now(),now(),now()),
('OFFICIAL|SKIPO|VA_STABLECOIN_SERVICES|2026-09-09','ENTITY','ENT-RUT-77554238-1','VA_STABLECOIN_SERVICES','OBSERVED','OFFICIAL_OPEN',1.0,'Skipo ofrece stablecoins y servicios para integrar stablecoins en empresas.','COMPANY_OFFICIAL','https://skipo.com/es/','Stablecoins para personas y empresas.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

update public.aml_fintech_entity
set psav_status='CONFIRMED',psav_basis='La oferta vigente de Skipo confirma compra/venta de criptomonedas, billetera, transferencias y stablecoins para personas y empresas; funcionalmente presta servicios PSAV. La clasificación funcional no sustituye el análisis jurídico del alcance de su autorización CMF.',psav_confidence=0.999,psav_refreshed_at=now(),refreshed_at=now()
where fintech_id='ENT-RUT-77554238-1';

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values('COMPANY_OFFICIAL|HOLDO|CLIENTS|2026-09-09','ENTITY','ENT-RUT-77299015-4','CLIENTS',1000,'Más de 1.000 clientes','clients',null,'AT_LEAST','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.holdo.cl/',now(),'Holdo declara más de 1.000 clientes; la cifra no distingue personas de empresas y por eso se mantiene como CLIENTS genérico.','+1.000 clientes ya confían en nosotros',jsonb_build_object('lower_bound',true,'mixed_client_types',true),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();