with vals(fintech_id,business_model,target_customer,revenue_model,bm_conf,tc_conf,rev_conf,bm_basis,tc_basis,rev_basis,source_url) as (
 values
 ('ENT-RUT-59294680-7','B2B','EMPRESAS','INTERES_ORIGINACION',0.999::numeric,0.999::numeric,0.97::numeric,'Xepelin ofrece factoring, crédito, financiamiento directo y financiamiento de pagos a Pymes y empresas mediante una plataforma 100% digital.','La oferta vigente está dirigida explícitamente a empresas, desde Pymes hasta corporativos.','Los productos de crédito muestran tasa de interés y los productos de factoring descuentan comisión/costo de financiamiento; se clasifica como margen financiero/originación dentro de la taxonomía actual.','https://xepelin.com/credito-chile'),
 ('ENT-RUT-76400275-K','B2B2C','AMBOS','COMISION_TRANSACCIONAL',0.999::numeric,0.97::numeric,0.95::numeric,'RedCapital es una plataforma de financiamiento colectivo que conecta Pymes solicitantes con inversionistas.','La plataforma atiende empresas/Pymes que buscan financiamiento y una contraparte de inversionistas; se representa como ecosistema de dos lados.','La documentación vigente describe derechos/comisiones por participar en operaciones de inversión, por lo que la remuneración observable se modela como comisión por operación dentro de la taxonomía actual.','https://redcapital.cl/como-funciona-solicitar'),
 ('ENT-RUT-77073836-9','B2B2C','AMBOS',null,0.999::numeric,0.999::numeric,null,'Banca.me combina crédito/BNPL para personas con soluciones para comercios e inmobiliarias y software de evaluación/financiamiento.','La oferta vigente atiende personas que compran o financian vivienda y empresas/comercios que integran BNPL o financiamiento de pie.','La plataforma muestra simultáneamente intereses y comisión de servicio, y utiliza vehículos de crédito separados; no se fuerza un único modelo principal de ingresos.','https://www.banca.me/'),
 ('ENT-RUT-76865845-5','B2B','EMPRESAS',null,0.999::numeric,0.999::numeric,null,'Los términos de Simpli indican expresamente servicios financieros a empresas/personas jurídicas; la oferta actual incluye factoring, payments, ordering, confirming y dashboard empresarial.','El cliente observado es empresa/persona jurídica, principalmente Pymes y corporativas.','La oferta combina factoring y servicios de pagos; la evidencia actual no permite representar responsablemente toda la monetización con un único código existente.','https://simpli.cl/')
), logged as (
 insert into public.aml_fintech_profile_audit(fintech_id,classifier_version,business_model,business_model_confidence,target_customer,target_customer_confidence,revenue_model,revenue_model_confidence,pages_scanned,observed_at,evidence)
 select v.fintech_id,'MANUAL_OFFICIAL_LENDING_2026_09_09',v.business_model,v.bm_conf,v.target_customer,v.tc_conf,v.revenue_model,v.rev_conf,1,now(),jsonb_build_object('source_url',v.source_url,'business_model_basis',v.bm_basis,'target_customer_basis',v.tc_basis,'revenue_model_basis',v.rev_basis,'manual_validation',true,'cohort','LENDING_CORE') from vals v returning fintech_id
)
update public.aml_fintech_entity e
set business_model=v.business_model,target_customer=v.target_customer,revenue_model=v.revenue_model,business_model_basis=v.bm_basis,business_model_confidence=v.bm_conf,target_customer_basis=v.tc_basis,target_customer_confidence=v.tc_conf,revenue_model_basis=v.rev_basis,revenue_model_confidence=v.rev_conf,profile_classifier_version='MANUAL_OFFICIAL_LENDING_2026_09_09',profile_refreshed_at=now(),refreshed_at=now()
from vals v where e.fintech_id=v.fintech_id and exists(select 1 from logged l where l.fintech_id=e.fintech_id);

insert into public.aml_fintech_legal_vehicle(fintech_id,rut,atlas_entity_id,legal_name,role_code,is_primary,regulator,registry,source_code,source_url,evidence_basis,confidence,first_seen_at,last_seen_at,metadata)
values
('ENT-RUT-77073836-9','77673115-3','ENT-RUT-77673115-3','BANCAME TRUST SPA','CREDIT_ORIGINATION_VEHICLE',false,'UAF','OBLIGATED_SUBJECT','COMPANY_OFFICIAL','https://www.banca.me/','Banca.me declara que Bancame Trust SpA es una de las sociedades que ofrece créditos de consumo, avance en efectivo, cuotas sin tarjeta y financiamiento de pie. SII la mantiene activa.',0.999,now(),now(),jsonb_build_object('actor','Banca.me','service_scope','consumer_credit_bnpl_downpayment_financing')),
('ENT-RUT-77073836-9','77748021-9','ENT-RUT-77748021-9','BANCAME TRUST II SPA','CREDIT_ORIGINATION_VEHICLE',false,'UAF','OBLIGATED_SUBJECT','COMPANY_OFFICIAL','https://www.banca.me/','Banca.me declara que Bancame Trust II SpA es una de las sociedades que ofrece créditos de consumo, avance en efectivo, cuotas sin tarjeta y financiamiento de pie. SII la mantiene activa.',0.999,now(),now(),jsonb_build_object('actor','Banca.me','service_scope','consumer_credit_bnpl_downpayment_financing'))
on conflict(fintech_id,rut,role_code) do update set atlas_entity_id=excluded.atlas_entity_id,legal_name=excluded.legal_name,is_primary=false,regulator=excluded.regulator,registry=excluded.registry,source_code=excluded.source_code,source_url=excluded.source_url,evidence_basis=excluded.evidence_basis,confidence=excluded.confidence,last_seen_at=now(),metadata=excluded.metadata;

insert into public.aml_fintech_function_observation(observation_key,subject_type,subject_key,function_code,evidence_status,evidence_class,confidence,basis,source_code,source_url,evidence_excerpt,first_seen_at,last_seen_at,observed_at)
values
('OFFICIAL|XEPELIN|FIN_LENDING|2026-09-09','ENTITY','ENT-RUT-59294680-7','FIN_LENDING','OBSERVED','OFFICIAL_OPEN',1.0,'Xepelin ofrece factoring, crédito empresarial, capital de trabajo y financiamiento directo a empresas.','COMPANY_OFFICIAL','https://xepelin.com/credito-chile','Capital de trabajo, crédito y factoring 100% digital.',now(),now(),now()),
('OFFICIAL|REDCAPITAL|FIN_CROWDFUNDING|2026-09-09','ENTITY','ENT-RUT-76400275-K','FIN_CROWDFUNDING','OBSERVED','OFFICIAL_OPEN',1.0,'RedCapital declara una plataforma de financiamiento colectivo que conecta Pymes con inversionistas.','COMPANY_OFFICIAL','https://redcapital.cl/','Plataforma de financiamiento colectivo; proceso de inscripción como PFC.',now(),now(),now()),
('OFFICIAL|REDCAPITAL|FIN_LENDING|2026-09-09','ENTITY','ENT-RUT-76400275-K','FIN_LENDING','OBSERVED','OFFICIAL_OPEN',1.0,'La plataforma ofrece crédito, factoring, confirming y otras formas de financiamiento para Pymes.','COMPANY_OFFICIAL','https://redcapital.cl/como-funciona-solicitar','Factoring, crédito/pagaré y financiamiento para Pymes.',now(),now(),now()),
('OFFICIAL|BANCAME|FIN_LENDING|2026-09-09','ENTITY','ENT-RUT-77073836-9','FIN_LENDING','OBSERVED','OFFICIAL_OPEN',1.0,'Banca.me y sus vehículos ofrecen cuotas sin tarjeta, crédito de consumo, avance, financiamiento de pie y gestión de hipotecarios.','COMPANY_OFFICIAL','https://www.banca.me/','Créditos de consumo, BNPL, pie e hipotecario.',now(),now(),now()),
('OFFICIAL|SIMPLI|FIN_LENDING|2026-09-09','ENTITY','ENT-RUT-76865845-5','FIN_LENDING','OBSERVED','OFFICIAL_OPEN',1.0,'Simpli ofrece factoring, ordering y confirming para financiar liquidez, órdenes de compra y pagos de proveedores.','COMPANY_OFFICIAL','https://simpli.cl/','Factoring, confirming y financiamiento empresarial.',now(),now(),now()),
('OFFICIAL|SIMPLI|FIN_PAYMENTS|2026-09-09','ENTITY','ENT-RUT-76865845-5','FIN_PAYMENTS','OBSERVED','OFFICIAL_OPEN',0.99,'Simpli Payments permite gestionar pagos de proveedores y remuneraciones.','COMPANY_OFFICIAL','https://simpli.cl/','Gestiona pago de proveedores y remuneraciones.',now(),now(),now())
on conflict(observation_key) do update set evidence_status=excluded.evidence_status,evidence_class=excluded.evidence_class,confidence=excluded.confidence,basis=excluded.basis,source_code=excluded.source_code,source_url=excluded.source_url,evidence_excerpt=excluded.evidence_excerpt,last_seen_at=now(),observed_at=excluded.observed_at;

insert into public.aml_fintech_market_metric_observation(observation_key,subject_type,subject_key,metric_code,value_numeric,value_text,unit,currency,qualifier,geography,evidence_type,confidence,source_code,source_url,observed_at,basis,evidence_excerpt,metadata,first_seen_at,last_seen_at)
values
('COMPANY_OFFICIAL|XEPELIN|BUSINESS_CLIENTS|2026-09-09','ENTITY','ENT-RUT-59294680-7','BUSINESS_CLIENTS',70000,'Más de 70.000 empresas confían en Xepelin','companies',null,'AT_LEAST','LATAM','DECLARADO',0.999,'COMPANY_OFFICIAL','https://xepelin.com/cl/factoring-chile',now(),'Cifra de empresas declarada en la oferta vigente; se usa como piso y no se interpreta como clientes Chile-only.','+70.000 empresas confían en xepelin',jsonb_build_object('lower_bound',true,'not_chile_only',true),now(),now()),
('COMPANY_OFFICIAL|BANCAME|USERS|2026-09-09','ENTITY','ENT-RUT-77073836-9','USERS',4600,'4.600+ usuarios en Chile','users',null,'AT_LEAST','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.banca.me/',now(),'Cifra vigente declarada por banca.me.','4600+ Usuarios en Chile',jsonb_build_object('lower_bound',true),now(),now()),
('COMPANY_OFFICIAL|BANCAME|MERCHANTS|2026-09-09','ENTITY','ENT-RUT-77073836-9','MERCHANTS',1500,'1.500+ comercios afiliados','merchants',null,'AT_LEAST','CHILE','DECLARADO',0.999,'COMPANY_OFFICIAL','https://www.banca.me/',now(),'Cifra vigente declarada por banca.me para su red BNPL.','1500+ Comercios afiliados',jsonb_build_object('lower_bound',true),now(),now()),
('COMPANY_OFFICIAL|BANCAME|ORIGINATED_VOLUME_USD|2026-09-09','ENTITY','ENT-RUT-77073836-9','ORIGINATED_VOLUME_USD',10000000,'Más de USD 10 millones entregados','USD','USD','AT_LEAST','CHILE','DECLARADO',0.98,'COMPANY_OFFICIAL','https://www.banca.me/',now(),'Monto declarado por banca.me como USD entregados; se interpreta como piso acumulado de financiamiento, no volumen anual.','$10 MM + USD entregados',jsonb_build_object('lower_bound',true,'scope','cumulative_declared','not_annual',true),now(),now())
on conflict(observation_key) do update set value_numeric=excluded.value_numeric,value_text=excluded.value_text,qualifier=excluded.qualifier,evidence_type=excluded.evidence_type,confidence=excluded.confidence,source_url=excluded.source_url,observed_at=excluded.observed_at,basis=excluded.basis,evidence_excerpt=excluded.evidence_excerpt,metadata=excluded.metadata,last_seen_at=now();

select public.aml_fintech_refresh_functional_profile();