create table if not exists public.aml_fintech_subject_relationship (
  relationship_id bigint generated by default as identity primary key,
  subject_type text not null check (subject_type in ('ENTITY','CANDIDATE')),
  subject_key text not null,
  relation_type text not null check (relation_type in ('PRODUCT_OF','BRAND_OF','LEGAL_VEHICLE_OF','ACQUIRED_BY','SUCCESSOR_OF','PREDECESSOR_OF','OPERATED_BY','CONTROLLED_BY')),
  target_fintech_id text null references public.aml_fintech_entity(fintech_id) on update cascade on delete set null,
  target_rut text null,
  target_atlas_entity_id text null,
  target_label text not null,
  valid_from date null,
  valid_to date null,
  source_code text null references public.aml_fintech_source_catalog(source_code) on update cascade on delete set null,
  source_url text null,
  evidence_basis text not null,
  confidence numeric(5,4) not null default 0.8 check (confidence between 0 and 1),
  active boolean not null default true,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint aml_fintech_subject_relationship_target_ck check (
    target_fintech_id is not null or target_rut is not null or target_atlas_entity_id is not null
  )
);

create unique index if not exists aml_fintech_subject_relationship_uq
on public.aml_fintech_subject_relationship (
  subject_type, subject_key, relation_type,
  coalesce(target_fintech_id,''), coalesce(target_rut,''), coalesce(target_atlas_entity_id,'')
);

create index if not exists aml_fintech_subject_relationship_subject_idx
on public.aml_fintech_subject_relationship(subject_type,subject_key,active);

create index if not exists aml_fintech_subject_relationship_target_idx
on public.aml_fintech_subject_relationship(target_rut,target_fintech_id,active);

alter table public.aml_fintech_subject_relationship enable row level security;
revoke all on table public.aml_fintech_subject_relationship from public, anon, authenticated;
grant select, insert, update, delete on table public.aml_fintech_subject_relationship to service_role;
grant usage, select on sequence public.aml_fintech_subject_relationship_relationship_id_seq to service_role;

create or replace function public.aml_fintech_upsert_subject_relationship(
  p_subject_type text,
  p_subject_key text,
  p_relation_type text,
  p_target_label text,
  p_target_rut text default null,
  p_target_fintech_id text default null,
  p_target_atlas_entity_id text default null,
  p_source_code text default null,
  p_source_url text default null,
  p_evidence_basis text default null,
  p_confidence numeric default 0.9,
  p_valid_from date default null,
  p_valid_to date default null,
  p_metadata jsonb default '{}'::jsonb
) returns bigint
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
  v_subject_type text := upper(trim(p_subject_type));
  v_relation_type text := upper(trim(p_relation_type));
  v_rut text := case when p_target_rut is null then null else public.aml_fintech_norm_rut(p_target_rut) end;
begin
  if v_subject_type not in ('ENTITY','CANDIDATE') then raise exception 'invalid subject_type'; end if;
  if v_relation_type not in ('PRODUCT_OF','BRAND_OF','LEGAL_VEHICLE_OF','ACQUIRED_BY','SUCCESSOR_OF','PREDECESSOR_OF','OPERATED_BY','CONTROLLED_BY') then raise exception 'invalid relation_type'; end if;
  if coalesce(p_target_fintech_id,v_rut,p_target_atlas_entity_id) is null then raise exception 'target required'; end if;
  if v_subject_type='ENTITY' and not exists(select 1 from public.aml_fintech_entity where fintech_id=p_subject_key) then raise exception 'entity subject not found'; end if;
  if v_subject_type='CANDIDATE' and not exists(select 1 from public.aml_fintech_candidate where candidate_id::text=p_subject_key) then raise exception 'candidate subject not found'; end if;

  insert into public.aml_fintech_subject_relationship(
    subject_type,subject_key,relation_type,target_fintech_id,target_rut,target_atlas_entity_id,target_label,
    valid_from,valid_to,source_code,source_url,evidence_basis,confidence,active,last_seen_at,metadata
  ) values (
    v_subject_type,p_subject_key,v_relation_type,p_target_fintech_id,v_rut,p_target_atlas_entity_id,p_target_label,
    p_valid_from,p_valid_to,p_source_code,p_source_url,coalesce(nullif(trim(p_evidence_basis),''),'Open-source relationship evidence'),
    least(1,greatest(0,p_confidence)),true,now(),coalesce(p_metadata,'{}'::jsonb)
  )
  on conflict (subject_type,subject_key,relation_type,coalesce(target_fintech_id,''),coalesce(target_rut,''),coalesce(target_atlas_entity_id,''))
  do update set
    target_label=excluded.target_label,
    valid_from=coalesce(excluded.valid_from,public.aml_fintech_subject_relationship.valid_from),
    valid_to=excluded.valid_to,
    source_code=coalesce(excluded.source_code,public.aml_fintech_subject_relationship.source_code),
    source_url=coalesce(excluded.source_url,public.aml_fintech_subject_relationship.source_url),
    evidence_basis=excluded.evidence_basis,
    confidence=greatest(public.aml_fintech_subject_relationship.confidence,excluded.confidence),
    active=true,
    last_seen_at=now(),
    metadata=public.aml_fintech_subject_relationship.metadata||excluded.metadata
  returning relationship_id into v_id;
  return v_id;
end;
$$;

revoke all on function public.aml_fintech_upsert_subject_relationship(text,text,text,text,text,text,text,text,text,text,numeric,date,date,jsonb) from public, anon, authenticated;
grant execute on function public.aml_fintech_upsert_subject_relationship(text,text,text,text,text,text,text,text,text,text,numeric,date,date,jsonb) to service_role;

create or replace view public.aml_v_fintech_subject_relationship_current
with (security_invoker=true)
as
select r.*,
       c.name_raw as candidate_name,
       f.brand as entity_brand,
       f.legal_name as entity_legal_name
from public.aml_fintech_subject_relationship r
left join public.aml_fintech_candidate c on r.subject_type='CANDIDATE' and c.candidate_id::text=r.subject_key
left join public.aml_fintech_entity f on r.subject_type='ENTITY' and f.fintech_id=r.subject_key
where r.active=true and (r.valid_to is null or r.valid_to>=current_date);

revoke all on public.aml_v_fintech_subject_relationship_current from public, anon, authenticated;
grant select on public.aml_v_fintech_subject_relationship_current to service_role;
