import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Max-Age":"86400","Content-Type":"application/json"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:CORS});
const decode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&#x27;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/gi,' ');
const strip=(h:string)=>decode(h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<(br|\/p|\/div|\/li|\/h\d|\/tr)>/gi,'\n').replace(/<[^>]+>/g,' ')).replace(/\r/g,'').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();
const norm=(v:unknown)=>String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const rut=(v:unknown)=>String(v??'').toUpperCase().replace(/[^0-9K]/g,'');
const host=(raw:string)=>{try{return new URL(raw).hostname.toLowerCase().replace(/^www\./,'')}catch{return''}};
const publicUrl=(raw:string)=>{try{const u=new URL(raw);if(!/^https?:$/.test(u.protocol))return false;const h=u.hostname.toLowerCase();if(h==='localhost'||h.endsWith('.local')||h==='0.0.0.0'||h.startsWith('127.')||h.startsWith('10.')||h.startsWith('192.168.'))return false;const m=h.match(/^172\.(\d+)\./);return !(m&&Number(m[1])>=16&&Number(m[1])<=31)}catch{return false}};
const official=(d:string)=>d.endsWith('.gob.cl')||d.endsWith('.gov.cl')||d==='gob.cl'||d==='interior.gob.cl'||d.endsWith('.interior.gob.cl')||d==='bcn.cl'||d.endsWith('.bcn.cl')||d.endsWith('.leychile.cl')||d==='sii.cl'||d.endsWith('.sii.cl')||d==='cmfchile.cl'||d.endsWith('.cmfchile.cl')||d.endsWith('.contraloria.cl')||d.endsWith('.dipres.gob.cl');
const STOP=new Set(['de','del','la','las','los','y','en','para','por','spa','ltda','limitada','sa','eirl','sociedad','empresa','servicio','servicios','regional','provincial','region']);
const tokens=(name:string)=>norm(name).split(' ').filter(x=>x.length>=4&&!STOP.has(x)).slice(0,8);
const identity=(text:string,name:string,rawRut:string)=>{const n=norm(text),ts=tokens(name),hits=ts.filter(t=>n.includes(t)).length,rr=rut(rawRut);return (rr.length>=7&&rut(text).includes(rr))||n.includes(norm(name))||(ts.length>0&&hits/ts.length>=.75)};

async function fetchText(raw:string,timeout=7000){if(!publicUrl(raw))return null;const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),timeout);try{const r=await fetch(raw,{signal:ac.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (compatible; ATLAS-AML-OpenContext/1.0)','accept':'text/html,text/plain;q=0.9,*/*;q=0.1','accept-language':'es-CL,es;q=0.9,en;q=0.5'}});if(!r.ok)return null;const ct=(r.headers.get('content-type')||'').toLowerCase();if(!(ct.includes('text/html')||ct.includes('text/plain')||ct.includes('application/xhtml')))return null;const b=new Uint8Array(await r.arrayBuffer());return new TextDecoder().decode(b.slice(0,520000))}catch{return null}finally{clearTimeout(timer)}}

function decodeUrl(raw:string){let href=decode(raw);try{if(href.startsWith('//'))href='https:'+href;if(href.includes('duckduckgo.com/l/?')){const u=new URL(href.startsWith('http')?href:'https://duckduckgo.com'+href);href=decodeURIComponent(u.searchParams.get('uddg')||'')}return publicUrl(href)?href:''}catch{return''}}
type Hit={title:string;snippet:string;url:string;domain:string;engine:string;official:boolean;page?:string};
function parseDdg(html:string){const out:Hit[]=[];const blocks=html.match(/<div[^>]+class="[^"]*result[^"]*"[\s\S]*?<\/div>\s*<\/div>/gi)||[];for(const block of blocks.slice(0,12)){const a=block.match(/<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;const url=decodeUrl(a[1]),d=host(url);if(!url||!d||d.includes('duckduckgo.com'))continue;const sm=block.match(/class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)<\/(?:a|div|span)>/i);out.push({title:strip(a[2]).replace(/\s+/g,' ').slice(0,220),snippet:sm?strip(sm[1]).replace(/\s+/g,' ').slice(0,700):'',url,domain:d,engine:'DuckDuckGo',official:official(d)})}return out}
function parseBing(html:string){const out:Hit[]=[];const blocks=html.match(/<li[^>]+class="[^"]*b_algo[^"]*"[\s\S]*?<\/li>/gi)||[];for(const block of blocks.slice(0,12)){const a=block.match(/<h2[^>]*>\s*<a[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;const url=decodeUrl(a[1]),d=host(url);if(!url||!d||d.includes('bing.com')||d.includes('microsoft.com'))continue;const sm=block.match(/<p[^>]*>([\s\S]*?)<\/p>/i);out.push({title:strip(a[2]).replace(/\s+/g,' ').slice(0,220),snippet:sm?strip(sm[1]).replace(/\s+/g,' ').slice(0,700):'',url,domain:d,engine:'Bing',official:official(d)})}return out}
async function search(q:string){const [d,b]=await Promise.all([fetchText('https://html.duckduckgo.com/html/?q='+encodeURIComponent(q),7500),fetchText('https://www.bing.com/search?q='+encodeURIComponent(q)+'&setlang=es-CL',7500)]);return [...(d?parseDdg(d):[]),...(b?parseBing(b):[])]}

type Signal='INSTITUTIONAL_REPLACEMENT'|'MERGER'|'DISSOLUTION'|'CLOSURE'|'TRANSFORMATION';
const SIGNALS:{id:Signal;label:string;rx:RegExp[]}[]=[
{id:'INSTITUTIONAL_REPLACEMENT',label:'reemplazo o continuidad institucional',rx:[/\b(reemplazad[oa]s?|sustituid[oa]s?|suprimid[oa]s?|continuador(?:a)? legal|extingu(?:e|ida|ido)|se extingui[oó])\b/i,/\b(funciones|atribuciones)\b.{0,120}\b(a cargo de|traspasad[oa]s?|ejercid[oa]s?)\b/i,/\bdelegaci[oó]n presidencial\b.{0,120}\b(gobernaci[oó]n|intendencia)\b/i]},
{id:'MERGER',label:'fusión, absorción o integración',rx:[/\b(fusionad[oa]s?|fusi[oó]n|absorbida|absorbido|absorci[oó]n|integrada|integrado)\b/i]},
{id:'DISSOLUTION',label:'disolución, liquidación o insolvencia',rx:[/\b(disoluci[oó]n|disuelta|disuelto|liquidaci[oó]n|liquidada|liquidado|quiebra|insolvencia|reorganizaci[oó]n)\b/i]},
{id:'CLOSURE',label:'cierre o cese de operaciones',rx:[/\b(cierre definitivo|cerr[oó] sus puertas|cese de operaciones|ces[oó] operaciones|dej[oó] de operar|deja de operar|fin de operaciones)\b/i]},
{id:'TRANSFORMATION',label:'cambio de nombre o transformación',rx:[/\b(cambi[oó] su nombre|cambio de denominaci[oó]n|se transform[oó] en|pas[oó] a denominarse|pas[oó] a ser)\b/i]},
];
const detect=(text:string)=>SIGNALS.filter(s=>s.rx.some(r=>r.test(text))).map(s=>s.id);
function cleanSuccessor(v:string){let x=decode(v).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();x=x.split(/\s+(?:tras|desde|debido|producto|a partir|luego|que reemplaz|que asum|conforme|seg[uú]n)\b/i)[0].trim().replace(/^[,:;\-–—\s]+|[,:;\-–—\s]+$/g,'');return x.length>=5&&x.length<=130?x:null}
function successor(text:string){for(const r of [/a cargo de (?:la|el)\s+([^.;\n]{5,150})/i,/fusionad[oa]s?.{0,100}?\ben (?:la|el)\s+([^.;\n]{5,150})/i,/reemplazad[oa]s?.{0,100}?\bpor (?:la|el)\s+([^.;\n]{5,150})/i,/sustituid[oa]s?.{0,100}?\bpor (?:la|el)\s+([^.;\n]{5,150})/i,/pas(?:o|ó|aron) a (?:conformar|ser) (?:la|el)\s+([^.;\n]{5,150})/i,/se transform(?:o|ó|aron) en (?:la|el)\s+([^.;\n]{5,150})/i]){const m=text.match(r);if(m?.[1]){const c=cleanSuccessor(m[1]);if(c)return c}}return null}
function dateFrom(text:string){const n=text.match(/\b(\d{1,2})[\/.\-](\d{1,2})[\/.\-](20\d{2})\b/);if(n)return`${n[1].padStart(2,'0')}/${n[2].padStart(2,'0')}/${n[3]}`;const w=text.match(/\b(\d{1,2})\s+de\s+(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)\s+de\s+(20\d{2})\b/i);return w?w[0]:null}
function summary(name:string,s:Signal,next:string|null,date:string|null,count:number,off:boolean){const src=off?'fuentes oficiales':`${count} fuentes abiertas independientes`,when=date?` desde/alrededor de ${date}`:'';if(s==='INSTITUTIONAL_REPLACEMENT')return next?`${src} indican que ${name} dejó de operar bajo esa estructura institucional y sus funciones pasaron a ${next}${when}. Este antecedente ofrece una explicación plausible del término de giro registral; Atlas lo presenta como contexto y no como causalidad jurídica acreditada.`:`${src} indican que ${name} fue extinguida, reemplazada o sucedida institucionalmente${when}. Este antecedente ofrece una explicación plausible del término de giro registral; Atlas lo presenta como contexto y no como causalidad jurídica acreditada.`;if(s==='MERGER')return next?`${src} indican que ${name} fue fusionada, absorbida o integrada en ${next}${when}. El antecedente es consistente con el término de giro observado y debe contrastarse con la documentación de la fuente.`:`${src} contienen evidencia consistente con una fusión, absorción o integración de ${name}${when}. El antecedente es compatible con el término de giro observado y debe contrastarse con la documentación de la fuente.`;if(s==='DISSOLUTION')return`${src} contienen evidencia consistente con disolución, liquidación, quiebra o insolvencia de ${name}${when}. El antecedente puede explicar el término de giro observado y debe validarse con la fuente original.`;if(s==='CLOSURE')return`${src} contienen evidencia consistente con cierre o cese de operaciones de ${name}${when}. El antecedente puede explicar el término de giro observado y debe validarse con la fuente original.`;return next?`${src} indican que ${name} cambió de denominación o se transformó en ${next}${when}. Este cambio puede contextualizar el término de giro y debe contrastarse con la fuente original.`:`${src} contienen evidencia consistente con un cambio de denominación o transformación de ${name}${when}. Este cambio puede contextualizar el término de giro y debe contrastarse con la fuente original.`}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'method_not_allowed'},405);const auth=req.headers.get('Authorization')||'',url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:{user},error:ue}=await uc.auth.getUser();if(ue||!user)return json({error:'unauthorized'},401);const admin=createClient(url,service,{auth:{persistSession:false}});const{data:allowed}=await admin.from('aml_allowed_users').select('user_id').eq('user_id',user.id).eq('enabled',true).maybeSingle();if(!allowed)return json({error:'forbidden'},403);const body=await req.json().catch(()=>({})),name=String(body.name||'').trim(),rawRut=String(body.rut||'').trim(),region=String(body.region||'').trim();if(!name)return json({error:'name_required'},400);
const qs=[`"${name}"${rawRut?` "${rawRut}"`:''}`,`"${name}" reemplazada reemplazado sucesor funciones`,`"${name}" fusionada fusionado disolución liquidación cierre`,`"${name}" "dejó de existir" "pasó a ser"${region?` ${region}`:''}`];const batches=await Promise.all(qs.map(search)),map=new Map<string,Hit>();for(const h of batches.flat()){const k=h.url.replace(/[#?].*$/,'');const p=map.get(k);if(!p||(h.official&&!p.official)||h.snippet.length>p.snippet.length)map.set(k,h)}const ranked=[...map.values()].filter(h=>identity(`${h.title} ${h.snippet}`,name,rawRut)).sort((a,b)=>Number(b.official)-Number(a.official)).slice(0,10);const enriched=await Promise.all(ranked.slice(0,7).map(async h=>({...h,page:(await fetchText(h.url,6500))||''})));const ev=enriched.map(h=>{const text=[h.title,h.snippet,h.page?strip(h.page).slice(0,140000):''].filter(Boolean).join('\n');return{...h,text,signals:detect(text),successor:successor(text),date:dateFrom(text)}}).filter(x=>identity(x.text,name,rawRut)&&x.signals.length);
let best:null|{signal:Signal;items:typeof ev;official:boolean;domains:string[];confidence:number}=null;for(const s of SIGNALS){const items=ev.filter(x=>x.signals.includes(s.id));if(!items.length)continue;const domains=[...new Set(items.map(x=>x.domain).filter(Boolean))],off=items.some(x=>x.official),confidence=off?Math.min(98,90+Math.min(8,Math.max(0,domains.length-1)*4)):domains.length>=3?90:domains.length>=2?84:58;if(!best||confidence>best.confidence||(confidence===best.confidence&&items.length>best.items.length))best={signal:s.id,items,official:off,domains,confidence}}
if(!best||best.confidence<80)return json({visible:false,status:'NO_CONCLUSION',confidence:best?.confidence||0,reason:'No se reunió evidencia suficientemente consistente para mostrar una conclusión al analista.',searched_queries:qs.length,candidate_sources:ranked.length});const preferred=best.items.find(x=>x.official&&x.successor)||best.items.find(x=>x.official)||best.items.find(x=>x.successor)||best.items[0],next=preferred?.successor||null,effective=preferred?.date||best.items.find(x=>x.date)?.date||null,text=summary(name,best.signal,next,effective,best.domains.length,best.official),label=SIGNALS.find(x=>x.id===best!.signal)?.label||'contexto explicativo';const evidence=best.items.slice().sort((a,b)=>Number(b.official)-Number(a.official)).filter((x,i,a)=>a.findIndex(y=>y.domain===x.domain)===i).slice(0,3).map(x=>({title:x.title||x.domain,url:x.url,domain:x.domain,official:x.official,snippet:(x.snippet||(x.page?strip(x.page):'')).replace(/\s+/g,' ').trim().slice(0,360)}));return json({visible:true,status:'CONCLUSIVE_CONTEXT',confidence:best.confidence,signal:best.signal,signal_label:label,successor:next,effective_date:effective,summary:text,evidence,searched_queries:qs.length,candidate_sources:ranked.length,independent_domains:best.domains.length,official_support:best.official,generated_at:new Date().toISOString()})});
